import Link from "next/link";
import { unsealHrCredential } from "@/lib/hr/auth/crypto";
import { totpProvisioningUri } from "@/lib/hr/auth/totp";
import { requireAuthenticatedUser } from "@/lib/hr/permissions/authorize";
import { beginMfaEnrollmentAction, disableMfaAction, enableMfaAction } from "./actions";

export default async function HrSecurityPage() {
  const auth = await requireAuthenticatedUser({ allowMfaEnrollment: true });
  const pendingSecret = !auth.user.mfaEnabled && auth.user.mfaSecretEncrypted ? unsealHrCredential(auth.user.mfaSecretEncrypted) : null;
  return <main className="min-h-screen bg-slate-100 px-4 py-12"><section className="mx-auto max-w-2xl rounded-3xl bg-white p-7 shadow-sm"><p className="text-sm font-bold uppercase tracking-widest text-teal-700">Account security</p><h1 className="mt-2 text-3xl font-bold">Authenticator MFA</h1><p className="mt-2 text-slate-600">Protect {auth.user.email} with a time-based one-time password. Privileged production accounts must enable MFA.</p><div className="mt-6 rounded-2xl border border-slate-200 p-5"><p className="font-semibold">Status: {auth.user.mfaEnabled ? "Enabled" : pendingSecret ? "Enrollment waiting for verification" : "Not enabled"}</p>{!auth.user.mfaEnabled && !pendingSecret && <form action={beginMfaEnrollmentAction} className="mt-4"><button className="btn btn-primary">Start MFA enrollment</button></form>}{pendingSecret && <div className="mt-4 space-y-4"><p className="text-sm">Add an account manually in your authenticator app with issuer <strong>Zentric Analytics</strong> and this secret:</p><code className="block break-all rounded-xl bg-slate-950 p-4 text-sm text-white">{pendingSecret}</code><details className="text-sm"><summary className="cursor-pointer font-semibold">Provisioning URI</summary><code className="mt-2 block break-all rounded-xl bg-slate-100 p-3">{totpProvisioningUri(auth.user.email, pendingSecret)}</code></details><form action={enableMfaAction} className="flex gap-3"><input className="input" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="6-digit code" required /><button className="btn btn-primary">Verify and enable</button></form></div>}{auth.user.mfaEnabled && <form action={disableMfaAction} className="mt-4 grid gap-3"><p className="text-sm text-slate-600">Disabling MFA requires your password and a current authenticator code, then revokes every session.</p><input className="input" name="password" type="password" autoComplete="current-password" placeholder="Current password" required /><input className="input" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" placeholder="6-digit code" required /><button className="font-semibold text-red-700">Disable MFA and sign out everywhere</button></form>}</div><Link className="mt-6 inline-block font-semibold text-teal-700" href="/hr">Return to workspace</Link></section></main>;
}
