import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

export const dynamic = "force-dynamic";
export default async function Unit9RunPage({ params }: { params: Promise<{ id: string }> }) {
  const auth = await requirePermission("payroll.read"); const { id } = await params;
  const run = await prisma.hrPayrollAuthoritativeRun.findFirst({ where: { id, organizationId: auth.user.organizationId } });
  if (!run) notFound();
  const [issues,snapshots,attempts,results,reconciliations,risks,approvals,payments,journals,liabilities,remittances] = await Promise.all([
    prisma.hrPayrollCertificationIssue.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollInputSnapshot.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollCalculationAttempt.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollAuthoritativeResult.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollReconciliation.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollRiskFinding.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollRunApproval.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollPaymentBatch.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollJournalBatch.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollStatutoryLiability.findMany({where:{organizationId:auth.user.organizationId,payrollRunId:id}}), prisma.hrPayrollRemittanceBatch.findMany({where:{organizationId:auth.user.organizationId}})
  ]);
  const payslips=await prisma.hrPayrollPayslipVersion.count({where:{organizationId:auth.user.organizationId,payrollResultId:{in:results.map(result=>result.id)}}});
  const cards=[['Status',run.status],['Population',String(snapshots.length)],['Open blockers',String(issues.filter(x=>!x.resolvedAt).length)],['Attempts',String(attempts.length)],['Results',String(results.length)],['Reconciliations',String(reconciliations.length)],['Open risks',String(risks.filter(x=>x.status==='OPEN').length)],['Approvals',String(approvals.length)],['Payslips',String(payslips)],['Payment batches',String(payments.length)],['Journals',String(journals.length)],['Liabilities',String(liabilities.length)],['Remittances',String(remittances.length)]];
  return <main><p className="text-sm font-semibold uppercase tracking-widest text-indigo-700">Payroll run</p><h1 className="mt-2 break-all text-3xl font-bold">{run.id}</h1><div className="mt-8 grid gap-4 md:grid-cols-3">{cards.map(([label,value])=><article className="rounded-2xl border bg-white p-5" key={label}><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-xl font-bold">{value}</p></article>)}</div><section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="font-bold">Authoritative lifecycle</h2><p className="mt-2 text-sm text-slate-600">Created {run.createdAt.toISOString()} · Frozen {run.frozenAt?.toISOString()??'pending'} · Finalized {run.finalizedAt?.toISOString()??'pending'}</p></section></main>;
}
