import { z } from 'zod';
import { countryPhoneOptions, normalizePhoneForCountry } from './phone';
import { experienceLevelOptions, resolveRoleAppliedFor, roleAppliedForOptions } from './recruitment-options';
export const stageStatuses = ['Locked','Available','In Progress','Submitted','Under Review','Approved','Correction Requested','Rejected','Completed'] as const;
export const applicationStatuses = ['Application Submitted','Screening','Candidate Information Required','Interview Scheduled','Assessment Required','Offer Pending','Offer Sent','Offer Accepted','Agreement Pending','Onboarding Pending','Final Review','Enrollment Completed','Hired','Rejected'] as const;
export type StageStatus = typeof stageStatuses[number];
export function isStageStatus(value: unknown): value is StageStatus { return typeof value === 'string' && (stageStatuses as readonly string[]).includes(value); }
export function toStageStatus(value: unknown, fallback: StageStatus = 'Locked'): StageStatus { return isStageStatus(value) ? value : fallback; }
export const stages = [
  { order: 1, key: 'initial-application', title: 'Initial Application', applicantAction: 'Submit your first-stage application and signed privacy consent.' },
  { order: 2, key: 'candidate-information', title: 'Candidate Information / Identity Verification', applicantAction: 'Provide HR and identity details after Stage 1 approval.' },
  { order: 3, key: 'screening-assessment', title: 'Screening / Interview / Assessment', applicantAction: 'Review admin instructions, confirm availability, and upload assessment if requested.' },
  { order: 4, key: 'offer', title: 'Offer Stage', applicantAction: 'Review, accept, or decline the offer when released.' },
  { order: 5, key: 'employment-agreement', title: 'Employment Agreement + Role Schedule', applicantAction: 'Review terms, role schedule, and e-sign agreement.' },
  { order: 6, key: 'onboarding', title: 'Onboarding Form', applicantAction: 'Submit payroll, next-of-kin, access, and start-date details.' },
  { order: 7, key: 'policy-acknowledgements', title: 'Policy, Privacy, and Access Acknowledgements', applicantAction: 'Acknowledge privacy, policy, confidentiality, communications, and system-access rules.' },
  { order: 8, key: 'final-hr-approval', title: 'Final HR Approval', applicantAction: 'HR confirms completion and employee-file readiness.' },
] as const;
export const workModes = ['Office','Remote','Hybrid','Flexible'] as const;
export const idTypes = ['National Identification Number / NIN','International Passport','Driver’s Licence','Voter’s Card','Other Government-issued ID'] as const;
export const initialApplicationSchema = z.object({ firstName: z.string().trim().min(1, 'Enter your first name.'), middleInitial: z.string().trim().max(20, 'Middle initial must be 20 characters or fewer.').optional().or(z.literal('')), lastName: z.string().trim().min(1, 'Enter your last name.'), email: z.string().email('Enter a valid email address.'), phoneCountryIso: z.enum(countryPhoneOptions.map((country) => country.iso) as [string, ...string[]], { errorMap: () => ({ message: 'Select a valid country.' }) }), phoneNational: z.string().min(4, 'Enter a phone number.'), location: z.string().min(2, 'Enter your current location.'), role: z.enum(roleAppliedForOptions, { errorMap: () => ({ message: 'Select the role you are applying for.' }) }), otherRole: z.string().trim().max(100, 'Other role must be 100 characters or fewer.').optional().or(z.literal('')), workMode: z.enum(workModes, { errorMap: () => ({ message: 'Select a work mode preference.' }) }), experienceLevel: z.enum(experienceLevelOptions, { errorMap: () => ({ message: 'Select your experience level.' }) }), skills: z.string().min(2, 'Enter at least one relevant skill.'), portfolioUrl: z.string().url('Enter a valid URL, or leave this blank.').optional().or(z.literal('')), message: z.string().min(20, 'Enter a short message of at least 20 characters.').max(1500, 'Keep your message under 1,500 characters.'), privacyConsent: z.literal('on', { errorMap: () => ({ message: 'Consent is required to process your application.' }) }), signatureName: z.string().min(2, 'Type your legal name as your electronic signature.'), signatureConsent: z.literal('on', { errorMap: () => ({ message: 'Confirm your electronic signature.' }) }) }).superRefine((data, ctx) => { const phone = normalizePhoneForCountry(data.phoneCountryIso, data.phoneNational); if (!phone.valid) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['phoneNational'], message: phone.error }); if (data.role === 'Other' && !data.otherRole?.trim()) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ['otherRole'], message: 'Specify the role when Other is selected.' }); });
export function toStage1SubmissionPayload(data: z.infer<typeof initialApplicationSchema>) { const phone = normalizePhoneForCountry(data.phoneCountryIso, data.phoneNational); if (!phone.valid) throw new Error(phone.error); return { ...data, roleAppliedFor: resolveRoleAppliedFor(data.role, data.otherRole), phoneCountryIso: phone.iso, phoneCountryName: phone.countryName, phoneDialCode: phone.dialCode, phoneNational: phone.nationalNumber, phoneE164: phone.e164, fullName: [data.firstName, data.middleInitial, data.lastName].filter(Boolean).join(' ') }; }
export function generateApplicationId(sequence: number, date = new Date()) { return `ZA-APP-${date.getUTCFullYear()}-${String(sequence).padStart(5, '0')}`; }
export function maskSensitive(value: string) { const clean = value.replace(/\s+/g, ''); return clean.length <= 4 ? '****' : `${'*'.repeat(Math.max(4, clean.length - 4))}${clean.slice(-4)}`; }
export const stage1DownloadAllowedStatuses: StageStatus[] = ['Approved','Completed'];
export type Stage1DownloadEligibilityInput = { stagePresent: boolean; submissionPresent: boolean; submissionSubmitted: boolean; signaturePresent: boolean; signatureConfirmed: boolean; signedAtPresent: boolean; stageStatus: StageStatus };
export function isStage1DownloadEligible(input: Stage1DownloadEligibilityInput) { return input.stagePresent && input.submissionPresent && input.submissionSubmitted && input.signaturePresent && input.signatureConfirmed && input.signedAtPresent && stage1DownloadAllowedStatuses.includes(input.stageStatus); }
export function canDownloadDocument(status: StageStatus, signed: boolean, submittedAt?: string | null, signedAt?: string | null) { return isStage1DownloadEligible({ stagePresent: true, submissionPresent: true, submissionSubmitted: Boolean(submittedAt), signaturePresent: signed, signatureConfirmed: signed, signedAtPresent: Boolean(signedAt), stageStatus: status }); }
export function sanitizeDownloadFilenamePart(value: string) { return value.replace(/[^a-zA-Z0-9._-]+/g, '-').replace(/-+/g, '-').replace(/^[-.]+|[-.]+$/g, '').slice(0, 80) || 'application'; }
export const documentStatuses = ['Locked','Not Started','In Progress','Submitted','Signed','Under Review','Correction Requested','Approved','Download Available'] as const;
export function isAccessCodeUsable(input: { expiresAt: Date; usedAt?: Date | null }, now = new Date()) { return !input.usedAt && input.expiresAt.getTime() > now.getTime(); }
export function getStage1ApprovalEffects() { return { stage1Status: 'Approved', stage2Status: 'Available', applicationStatus: 'Candidate Information Required', currentStageOrder: 2 } as const; }
export function adminActionAuditName(action: 'approve' | 'reject' | 'correction') { if (action === 'approve') return 'Admin approved Stage 1'; if (action === 'reject') return 'Admin rejected Stage 1'; return 'Admin requested correction'; }
