"use client";
import { useState } from "react";
import { Building2, ClipboardList, Edit3, FileText, Network, Settings, Users } from "lucide-react";
import { HrModal } from "@/components/HrModal";
type Department = { id:string; name:string; code:string; description:string|null; status:string; head:string; employees:number; teams:number; positions:number; createdAt:string };
export function DepartmentManageModal({ department, controls }: { department:Department; controls:React.ReactNode }) {
 const [open,setOpen]=useState(false),[tab,setTab]=useState("Overview"); const tabs=[["Overview",Building2],["Structure",Network],["Team Members",Users],["Assignments",ClipboardList],["Documents",FileText],["Settings",Settings],["Activity Log",ClipboardList]] as const;
 return <><button className="hr-row-trigger" onClick={()=>setOpen(true)}>Manage</button><HrModal open={open} title="Manage Department" onClose={()=>setOpen(false)}><div className="hr-entity-modal-layout"><aside>{tabs.map(([name,Icon])=><button className={tab===name?"active":""} key={name} onClick={()=>setTab(name)}><Icon/><span>{name}</span>{name==="Team Members"&&<b>{department.employees}</b>}{name==="Assignments"&&<b>{department.positions}</b>}</button>)}</aside><section className="hr-entity-modal-main">{tab==="Overview"?<><header className="hr-entity-summary"><span><Building2/></span><div><h3>{department.name} <em>{department.status}</em></h3><p>Department code: {department.code}</p><small>Created on {new Date(department.createdAt).toLocaleDateString()}</small></div><button className="btn btn-secondary" onClick={()=>setTab("Settings")}><Edit3/> Edit department</button></header><Info title="Department information" rows={[["Department name",department.name],["Department code",department.code],["Parent department","—"],["Head of department",department.head],["Employees",String(department.employees)],["Status",department.status],["Description",department.description||"No description supplied."]]}/><h4 className="hr-quick-title">Quick actions</h4><div className="hr-modal-actions"><button onClick={()=>setTab("Team Members")}><Users/><span><strong>View team</strong><small>See all team members</small></span></button><button onClick={()=>setTab("Assignments")}><ClipboardList/><span><strong>View assignments</strong><small>{department.positions} active positions</small></span></button><a href="/hr/admin/reports"><Network/><span><strong>Department reports</strong><small>View department analytics</small></span></a><button onClick={()=>setTab("Settings")}><Edit3/><span><strong>Edit department</strong><small>Update department details</small></span></button></div></>:tab==="Settings"?controls:<div className="hr-modal-empty"><h3>{tab}</h3><p>This view uses the department’s existing governed data and workflows.</p></div>}</section></div><footer className="hr-modal-footer"><button className="btn btn-secondary" onClick={()=>setOpen(false)}>Close</button></footer></HrModal></>;
}
function Info({title,rows}:{title:string;rows:string[][]}){return <section className="hr-info-card"><h4>{title}</h4><dl>{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>}
