import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { archiveDepartmentAction, archiveTeamAction, createDepartmentAction, createTeamAction } from "./actions";

export default async function DepartmentsPage() {
  const auth = await requirePermission("department.manage");
  const departments = await prisma.hrDepartment.findMany({ where: { organizationId: auth.user.organizationId }, include: { teams: { orderBy: { name: "asc" } }, _count: { select: { teams: true, positions: true, employeeAssignments: true } } }, orderBy: [{ status: "asc" }, { name: "asc" }] });
  return <><h1 className="text-3xl font-bold">Departments</h1><p className="mt-2 text-slate-600">Manage organization structure without deleting historical assignments.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create department</h2><form action={createDepartmentAction} className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" name="code" placeholder="Code" required /><input className="input" name="name" placeholder="Department name" required /><input className="input" name="description" placeholder="Description" /><button className="btn btn-primary">Create</button></form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create team</h2><form action={createTeamAction} className="mt-4 grid gap-3 md:grid-cols-4"><select className="input" name="departmentId" required><option value="">Department</option>{departments.filter(({ status }) => status === "ACTIVE").map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><input className="input" name="code" placeholder="Team code" required /><input className="input" name="name" placeholder="Team name" required /><button className="btn btn-primary">Create team</button></form></section>
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Code</th><th className="p-4">Department</th><th className="p-4">Teams</th><th className="p-4">Positions</th><th className="p-4">Assignments</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{departments.map((department) => <tr className="border-b last:border-0 align-top" key={department.id}><td className="p-4 font-mono">{department.code}</td><td className="p-4"><p className="font-semibold">{department.name}</p><p className="text-slate-500">{department.description}</p></td><td className="p-4"><ul className="space-y-2">{department.teams.map((team) => <li className="flex items-center gap-2" key={team.id}><span>{team.name} ({team.status})</span>{team.status === "ACTIVE" ? <form action={archiveTeamAction} className="flex gap-1"><input type="hidden" name="id" value={team.id} /><input className="input max-w-32" name="reason" placeholder="Reason" required /><button className="text-red-700">Archive</button></form> : null}</li>)}</ul></td><td className="p-4">{department._count.positions}</td><td className="p-4">{department._count.employeeAssignments}</td><td className="p-4">{department.status}</td><td className="p-4">{department.status === "ACTIVE" ? <form action={archiveDepartmentAction} className="flex gap-2"><input type="hidden" name="id" value={department.id} /><input className="input min-w-40" name="reason" placeholder="Archive reason" required /><button className="font-semibold text-red-700">Archive</button></form> : "History retained"}</td></tr>)}</tbody></table>{!departments.length ? <p className="p-6 text-slate-500">No departments yet.</p> : null}</div></>;
}
