import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { archiveDepartmentAction, archiveTeamAction, createDepartmentAction, createTeamAction, updateDepartmentAction } from "./actions";

export default async function DepartmentsPage() {
  const auth = await requirePermission("department.manage");
  const [departments, employees] = await Promise.all([
    prisma.hrDepartment.findMany({ where: { organizationId: auth.user.organizationId }, include: { headEmployee: true, teams: { orderBy: { name: "asc" } }, _count: { select: { teams: true, positions: true, employeeAssignments: true } } }, orderBy: [{ status: "asc" }, { name: "asc" }] }),
    prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId, employmentStatus: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }] }),
  ]);
  return <><h1 className="text-3xl font-bold">Departments</h1><p className="mt-2 text-slate-600">Manage organization structure without deleting historical assignments.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create department</h2><form action={createDepartmentAction} className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" name="code" placeholder="Code" required /><input className="input" name="name" placeholder="Department name" required /><input className="input" name="description" placeholder="Description" /><button className="btn btn-primary">Create</button></form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create team</h2><form action={createTeamAction} className="mt-4 grid gap-3 md:grid-cols-4"><select className="input" name="departmentId" required><option value="">Department</option>{departments.filter(({ status }) => status === "ACTIVE").map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><input className="input" name="code" placeholder="Team code" required /><input className="input" name="name" placeholder="Team name" required /><button className="btn btn-primary">Create team</button></form></section>
    <div className="mt-6 space-y-4">{departments.map((department) => <article className="rounded-2xl bg-white p-5" key={department.id}><div className="flex flex-wrap justify-between gap-4"><div><p className="font-mono text-sm">{department.code}</p><h2 className="text-xl font-bold">{department.name}</h2><p className="text-sm text-slate-500">{department.description}</p><p className="mt-2 text-sm"><strong>Head:</strong> {department.headEmployee ? `${department.headEmployee.legalFirstName} ${department.headEmployee.lastName}` : "Not assigned"} · <strong>Positions:</strong> {department._count.positions} · <strong>Assignment records:</strong> {department._count.employeeAssignments}</p></div><span>{department.status}</span></div><div className="mt-4"><h3 className="text-sm font-bold">Teams</h3><ul className="mt-2 space-y-2">{department.teams.map((team) => <li className="flex flex-wrap items-center gap-2 text-sm" key={team.id}><span>{team.name} ({team.status})</span>{team.status === "ACTIVE" ? <form action={archiveTeamAction} className="flex gap-1"><input type="hidden" name="id" value={team.id} /><input className="input max-w-32" name="reason" placeholder="Reason" required /><button className="text-red-700">Archive</button></form> : null}</li>)}</ul></div>{department.status === "ACTIVE" ? <div className="mt-5 grid gap-4 lg:grid-cols-2"><form action={updateDepartmentAction} className="grid gap-2"><input type="hidden" name="id" value={department.id} /><input className="input" name="name" defaultValue={department.name} required /><input className="input" name="description" defaultValue={department.description ?? ""} placeholder="Description" /><select className="input" name="headEmployeeId" defaultValue={department.headEmployeeId ?? ""}><option value="">No department head</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.legalFirstName} {employee.lastName}</option>)}</select><input className="input" name="reason" placeholder="Reason for update" required /><button className="btn btn-secondary">Update department</button></form><form action={archiveDepartmentAction} className="grid content-start gap-2"><input type="hidden" name="id" value={department.id} /><input className="input" name="reason" placeholder="Archive reason" required /><button className="btn btn-secondary text-red-700">Archive department</button></form></div> : <p className="mt-4 text-sm text-slate-500">History retained.</p>}</article>)}{!departments.length ? <p className="rounded-2xl bg-white p-6 text-slate-500">No departments yet.</p> : null}</div></>;
}
