import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { addHolidayOccurrenceAction, assignHolidayCalendarAction, assignWorkScheduleAction, createHolidayCalendarAction, createPolicyApplicabilityAction, createWorkScheduleAction } from "./actions";

const defaultPattern = JSON.stringify([{ weekday: 1, start: "09:00", end: "17:00" }, { weekday: 2, start: "09:00", end: "17:00" }, { weekday: 3, start: "09:00", end: "17:00" }, { weekday: 4, start: "09:00", end: "17:00" }, { weekday: 5, start: "09:00", end: "17:00" }]);

export default async function Unit5LeaveConfigurationPage() {
  const auth = await requirePermission("leave.policy.manage");
  const organizationId = auth.user.organizationId;
  const [schedules, calendars, policies, employees] = await Promise.all([
    prisma.hrWorkSchedule.findMany({ where: { organizationId }, include: { versions: { orderBy: { version: "desc" } } }, orderBy: { name: "asc" } }),
    prisma.hrHolidayCalendar.findMany({ where: { organizationId }, include: { versions: { include: { occurrences: true }, orderBy: { version: "desc" } } }, orderBy: { name: "asc" } }),
    prisma.hrLeavePolicy.findMany({ where: { organizationId, status: "ACTIVE" }, include: { leaveType: true, applicability: true }, orderBy: [{ leaveType: { name: "asc" } }, { version: "desc" }] }),
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }], take: 250 }),
  ]);
  return <main><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Unit 5 leave configuration</h1><p className="mt-2 text-slate-600">Effective-dated policy applicability, work schedules and holiday calendars. Published versions remain historical.</p></div><Link className="btn btn-secondary" href="/hr/admin/leave">Leave administration</Link></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Publish work schedule version</h2><form action={createWorkScheduleAction} className="mt-4 grid gap-3"><input className="input" name="code" placeholder="Schedule code (reuse to version)" required/><input className="input" name="name" placeholder="Schedule name" required/><input className="input" name="timezone" defaultValue="UTC" required/><input className="input" name="effectiveFrom" type="date" required/><input className="input" name="effectiveTo" type="date" aria-label="Effective end (required before a later version can be published)"/><textarea className="input min-h-32 font-mono text-xs" name="weeklyPattern" defaultValue={defaultPattern} required/><button className="btn btn-primary">Publish immutable version</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Assign schedule</h2><form action={assignWorkScheduleAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee)=><option key={employee.id} value={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="workScheduleVersionId" required><option value="">Published version</option>{schedules.flatMap((schedule)=>schedule.versions.map((version)=><option key={version.id} value={version.id}>{schedule.name} v{version.version}</option>))}</select><input className="input" name="effectiveFrom" type="date" required/><input className="input" name="reason" placeholder="Assignment reason" required/><button className="btn btn-primary">Assign schedule</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Publish holiday calendar version</h2><form action={createHolidayCalendarAction} className="mt-4 grid gap-3"><input className="input" name="code" placeholder="Calendar code (reuse to version)" required/><input className="input" name="name" placeholder="Calendar name" required/><input className="input" name="timezone" defaultValue="UTC" required/><input className="input" name="effectiveFrom" type="date" required/><input className="input" name="effectiveTo" type="date"/><button className="btn btn-primary">Publish immutable version</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Add holiday/shutdown</h2><form action={addHolidayOccurrenceAction} className="mt-4 grid gap-3"><select className="input" name="holidayCalendarVersionId" required><option value="">Calendar version</option>{calendars.flatMap((calendar)=>calendar.versions.map((version)=><option key={version.id} value={version.id}>{calendar.name} v{version.version}</option>))}</select><input className="input" name="code" placeholder="Occurrence code" required/><input className="input" name="name" placeholder="Name" required/><input className="input" name="localDate" type="date" required/><input className="input" name="durationMinutes" type="number" min="1" max="1440" placeholder="Minutes; blank for full day"/><label className="flex gap-2 text-sm"><input name="companyShutdown" type="checkbox"/>Company shutdown</label><button className="btn btn-primary">Add occurrence</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Assign holiday calendar</h2><form action={assignHolidayCalendarAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee)=><option key={employee.id} value={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="holidayCalendarVersionId" required><option value="">Published calendar version</option>{calendars.flatMap((calendar)=>calendar.versions.map((version)=><option key={version.id} value={version.id}>{calendar.name} v{version.version}</option>))}</select><input className="input" name="effectiveFrom" type="date" required/><input className="input" name="effectiveTo" type="date"/><input className="input" name="reason" placeholder="Assignment reason" required/><button className="btn btn-primary">Assign calendar</button></form></section>
    </div>
    <section className="mt-5 rounded-2xl bg-white p-5"><h2 className="font-bold">Policy applicability</h2><form action={createPolicyApplicabilityAction} className="mt-4 grid gap-3 md:grid-cols-3"><select className="input" name="leavePolicyId" required><option value="">Policy version</option>{policies.map((policy)=><option key={policy.id} value={policy.id}>{policy.leaveType.name} — {policy.name} v{policy.version}</option>)}</select><input className="input" name="countryCode" placeholder="Country code"/><input className="input" name="legalEntityId" placeholder="Legal entity ID"/><input className="input" name="locationId" placeholder="Location ID"/><select className="input" name="employmentType"><option value="">Any employment type</option><option>FULL_TIME</option><option>PART_TIME</option><option>CONTRACTOR</option><option>INTERN</option><option>TEMPORARY</option></select><input className="input" name="gradeId" placeholder="Grade ID"/><input className="input" name="minimumTenureDays" type="number" min="0" placeholder="Minimum tenure days"/><input className="input" name="priority" type="number" defaultValue="0" required/><button className="btn btn-primary">Add applicability rule</button></form></section>
  </main>;
}
