"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { approveContractVersion, createContractVersion, createProbationCase, decideProbationCase, rehireEmployee, reviewSeparationCase, signContractVersion, submitProbationReview } from "@/lib/hr/workforce/lifecycle-commands";
const refresh = () => { revalidatePath("/hr/admin/employment-lifecycle"); revalidatePath("/hr/admin/employees"); };
const context = (auth: Awaited<ReturnType<typeof requirePermission>>) => ({ organizationId: auth.user.organizationId, actorUserId: auth.user.id, actorRole: auth.roles[0] });
const workRelationshipId = z.union([z.string().cuid(), z.string().regex(/^legacy_relationship_[a-f0-9]{32}$/)]);

export async function createProbationAction(formData: FormData) { const auth = await requirePermission("workforce_event.create"); const input = z.object({ employeeId: z.string().cuid(), startedAt: z.coerce.date(), scheduledEndAt: z.coerce.date(), objectives: z.string().trim().min(3).max(2000) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => createProbationCase(tx, context(auth), { ...input, objectives: { summary: input.objectives } }), { isolationLevel: "Serializable" }); refresh(); }
export async function submitProbationReviewAction(formData: FormData) { const auth = await requirePermission("workforce_event.review"); const input = z.object({ probationCaseId: z.string().cuid(), type: z.enum(["CHECKPOINT", "FINAL"]), checkpointAt: z.coerce.date(), employeeComment: z.string().trim().max(2000).optional(), managerComment: z.string().trim().min(3).max(2000), recommendation: z.enum(["CONTINUE", "CONFIRM", "EXTEND", "END_EMPLOYMENT"]) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => submitProbationReview(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
export async function decideProbationAction(formData: FormData) { const auth = await requirePermission("workforce_event.review"); const input = z.object({ probationCaseId: z.string().cuid(), expectedVersion: z.coerce.number().int().positive(), outcome: z.enum(["CONFIRM", "EXTEND", "END_EMPLOYMENT"]), reason: z.string().trim().min(3).max(1000), extensionEndAt: z.coerce.date().optional().or(z.literal("")).transform((v) => v === "" ? undefined : v) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => decideProbationCase(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
export async function createContractAction(formData: FormData) { const auth = await requirePermission("workforce_event.create"); const input = z.object({ employeeId: z.string().cuid(), workRelationshipId, contractId: z.string().cuid().optional().or(z.literal("")).transform((v) => v || undefined), effectiveFrom: z.coerce.date(), effectiveTo: z.coerce.date().optional().or(z.literal("")).transform((v) => v === "" ? undefined : v), documentVersionId: z.string().cuid(), terms: z.string().trim().min(3).max(5000) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => createContractVersion(tx, context(auth), { ...input, termsSnapshot: { summary: input.terms } }), { isolationLevel: "Serializable" }); refresh(); }
export async function approveContractAction(formData: FormData) { const auth = await requirePermission("workforce_event.review"); const input = z.object({ contractId: z.string().cuid(), expectedVersion: z.coerce.number().int().positive() }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => approveContractVersion(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
export async function signContractAction(formData: FormData) { const auth = await requirePermission("workforce_event.review"); const input = z.object({ contractId: z.string().cuid(), expectedVersion: z.coerce.number().int().positive() }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => signContractVersion(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
export async function reviewSeparationAction(formData: FormData) { const auth = await requirePermission("workforce_event.review"); const input = z.object({ separationId: z.string().cuid(), expectedVersion: z.coerce.number().int().positive(), decision: z.enum(["APPROVED", "REJECTED"]), reason: z.string().trim().min(3).max(1000) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => reviewSeparationCase(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
export async function rehireAction(formData: FormData) { const auth = await requirePermission("workforce_event.create"); const input = z.object({ employeeId: z.string().cuid(), priorRelationshipId: z.string().trim().min(1).max(191), positionId: z.string().cuid(), employmentType: z.enum(["FULL_TIME", "PART_TIME", "CONTRACT", "INTERN", "TEMPORARY"]), fte: z.coerce.number().positive().max(1), startedAt: z.coerce.date(), reason: z.string().trim().min(3).max(1000) }).parse(Object.fromEntries(formData)); await prisma.$transaction((tx) => rehireEmployee(tx, context(auth), input), { isolationLevel: "Serializable" }); refresh(); }
