import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { approveContractAction, createContractAction, createProbationAction, decideProbationAction, rehireAction, reviewSeparationAction, signContractAction, submitProbationReviewAction } from "./actions";

export default async function EmploymentLifecyclePage() {
  const auth = await requirePermission("workforce_event.create");
  const organizationId = auth.user.organizationId;
  const [employees, probationCases, contracts, separations, formerEmployees, documentVersions, positions] = await Promise.all([
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { notIn: ["TERMINATED", "ARCHIVED"] } }, include: { workRelationships: { where: { status: { in: ["ACTIVE", "NOTICE_PERIOD", "SUSPENDED"] } }, take: 1 } }, orderBy: { legalFirstName: "asc" } }),
    prisma.hrProbationCase.findMany({ where: { organizationId }, include: { employee: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrEmploymentContract.findMany({ where: { organizationId }, include: { employee: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrSeparationCase.findMany({ where: { organizationId }, include: { employee: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { in: ["TERMINATED", "ARCHIVED"] } }, include: { workRelationships: { where: { status: "ENDED" }, orderBy: { endedAt: "desc" } } } }),
    prisma.hrEmployeeDocumentVersion.findMany({ where: { organizationId, scanStatus: "CLEAN", releasedAt: { not: null } }, include: { document: { include: { employee: true } } }, orderBy: { uploadedAt: "desc" }, take: 100 }),
    prisma.hrPosition.findMany({ where: { organizationId, status: "ACTIVE", lifecycleStatus: { in: ["OPEN", "PARTIALLY_FILLED"] } }, include: { department: true }, orderBy: { title: "asc" } }),
  ]);
  return <><h1 className="text-3xl font-bold">Employment lifecycle</h1><p className="mt-2 text-slate-600">Probation, exact-version contracts, separation review, and identity-preserving rehire.</p>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Start probation</h2><form action={createProbationAction} className="mt-3 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((e) => <option value={e.id} key={e.id}>{e.legalFirstName} {e.lastName}</option>)}</select><input className="input" name="startedAt" type="date" required/><input className="input" name="scheduledEndAt" type="date" required/><textarea className="input" name="objectives" placeholder="Probation objectives" required/><button className="btn btn-primary">Create probation</button></form></section>
    <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Create contract version</h2><form action={createContractAction} className="mt-3 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((e) => <option value={e.id} key={e.id}>{e.legalFirstName} {e.lastName}</option>)}</select><select className="input" name="workRelationshipId" required><option value="">Work relationship</option>{employees.flatMap((e) => e.workRelationships.map((r) => <option value={r.id} key={r.id}>{e.employeeNumber} — {r.relationshipRef}</option>))}</select><select className="input" name="contractId"><option value="">New contract</option>{contracts.map((c) => <option value={c.id} key={c.id}>{c.contractRef} v{c.currentVersion}</option>)}</select><select className="input" name="documentVersionId" required><option value="">Exact clean document version</option>{documentVersions.map((v) => <option value={v.id} key={v.id}>{v.document.employee.employeeNumber} — {v.document.title} v{v.version}</option>)}</select><input className="input" name="effectiveFrom" type="date" required/><input className="input" name="effectiveTo" type="date"/><textarea className="input" name="terms" placeholder="Terms snapshot" required/><button className="btn btn-primary">Create exact version</button></form></section></div>
    <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">Probation register</h2>{probationCases.map((p) => <article className="rounded-xl bg-white p-4" key={p.id}><strong>{p.employee.legalFirstName} {p.employee.lastName}</strong> · {p.status} · ends {p.scheduledEndAt.toLocaleDateString()} · v{p.version}<form action={submitProbationReviewAction} className="mt-3 grid gap-2 md:grid-cols-5"><input type="hidden" name="probationCaseId" value={p.id}/><select className="input" name="type"><option>CHECKPOINT</option><option>FINAL</option></select><input className="input" name="checkpointAt" type="date" required/><select className="input" name="recommendation"><option>CONTINUE</option><option>CONFIRM</option><option>EXTEND</option><option>END_EMPLOYMENT</option></select><input className="input" name="managerComment" placeholder="Review comment" required/><button className="btn btn-secondary">Submit review</button></form>{p.status === "UNDER_REVIEW" ? <form action={decideProbationAction} className="mt-2 flex gap-2"><input type="hidden" name="probationCaseId" value={p.id}/><input type="hidden" name="expectedVersion" value={p.version}/><select className="input" name="outcome"><option>CONFIRM</option><option>EXTEND</option><option>END_EMPLOYMENT</option></select><input className="input" name="extensionEndAt" type="date"/><input className="input" name="reason" placeholder="Decision reason" required/><button className="btn btn-primary">Decide</button></form> : null}</article>)}</section>
    <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">Contract register</h2>{contracts.map((c) => <article className="rounded-xl bg-white p-4" key={c.id}><strong>{c.contractRef}</strong> · {c.employee.legalFirstName} {c.employee.lastName} · {c.status} · v{c.currentVersion}{c.status === "PENDING_APPROVAL" ? <form action={approveContractAction} className="mt-2"><input type="hidden" name="contractId" value={c.id}/><input type="hidden" name="expectedVersion" value={c.currentVersion}/><button className="btn btn-primary">Approve exact version</button></form> : null}{c.status === "APPROVED" ? <form action={signContractAction} className="mt-2"><input type="hidden" name="contractId" value={c.id}/><input type="hidden" name="expectedVersion" value={c.currentVersion}/><button className="btn btn-secondary">Record signature</button></form> : null}</article>)}</section>
    <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">Separation review</h2>{separations.map((s) => <article className="rounded-xl bg-white p-4" key={s.id}><strong>{s.employee.legalFirstName} {s.employee.lastName}</strong> · {s.type} · {s.status} · final day {s.finalWorkingDate.toLocaleDateString()}{["SUBMITTED","UNDER_REVIEW"].includes(s.status) ? <form action={reviewSeparationAction} className="mt-2 flex gap-2"><input type="hidden" name="separationId" value={s.id}/><input type="hidden" name="expectedVersion" value={s.version}/><select className="input" name="decision"><option>APPROVED</option><option>REJECTED</option></select><input className="input" name="reason" placeholder="Independent decision reason" required/><button className="btn btn-primary">Decide</button></form> : null}</article>)}</section>
    <section className="mt-6 space-y-3"><h2 className="text-xl font-bold">Rehire</h2>{formerEmployees.map((e) => e.workRelationships[0] ? <form action={rehireAction} className="rounded-xl bg-white p-4" key={e.id}><strong>{e.legalFirstName} {e.lastName}</strong><input type="hidden" name="employeeId" value={e.id}/><input type="hidden" name="priorRelationshipId" value={e.workRelationships[0].id}/><div className="mt-2 grid gap-2 md:grid-cols-6"><select className="input" name="positionId" required><option value="">Approved position</option>{positions.map((position) => <option value={position.id} key={position.id}>{position.title} · {position.department.name}</option>)}</select><select className="input" name="employmentType" defaultValue="FULL_TIME"><option>FULL_TIME</option><option>PART_TIME</option><option>CONTRACT</option><option>INTERN</option><option>TEMPORARY</option></select><input className="input" name="fte" type="number" min="0.01" max="1" step="0.01" defaultValue="1" required/><input className="input" name="startedAt" type="date" required/><input className="input" name="reason" placeholder="Rehire reason" required/><button className="btn btn-primary">Create relationship and assignment</button></div></form> : null)}</section></>;
}
