import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

export default async function AuditorPerformancePage() {
  const auth = await requirePermission("performance.audit.read");
  const [reviews, calibration, decisions, promotions, audits] = await Promise.all([
    prisma.hrPerformanceReview.findMany({ where: { organizationId: auth.user.organizationId, status: "FINALIZED" }, select: { id: true, employeeId: true, cycleId: true, status: true, version: true, finalizedRatingItemId: true, finalizedAt: true, correlationId: true }, orderBy: { finalizedAt: "desc" }, take: 100 }),
    prisma.hrCalibrationSession.findMany({ where: { organizationId: auth.user.organizationId }, select: { id: true, cycleId: true, status: true, version: true, finalizedAt: true, correlationId: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.hrCalibrationDecision.findMany({ where: { organizationId: auth.user.organizationId }, select: { id: true, sessionId: true, reviewId: true, reviewVersion: true, managerRatingItemId: true, calibratedRatingItemId: true, version: true, finalizedAt: true, correlationId: true }, take: 100 }),
    prisma.hrPromotionCase.findMany({ where: { organizationId: auth.user.organizationId }, select: { id: true, employeeId: true, status: true, version: true, workforceEventId: true, workforceEventVersion: true, correlationId: true, updatedAt: true }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrAuditEvent.findMany({ where: { organizationId: auth.user.organizationId, action: { startsWith: "hr.performance." } }, select: { id: true, entityType: true, entityId: true, action: true, correlationId: true, createdAt: true }, orderBy: { createdAt: "desc" }, take: 200 }),
  ]);
  return <><h1 className="text-3xl font-bold">Performance audit evidence</h1><p className="mt-2 text-slate-600">Read-only, tenant-scoped metadata. Sensitive narratives and calibration deliberation are intentionally redacted.</p><div className="mt-6 grid gap-4 sm:grid-cols-4">{[["Final reviews", reviews.length], ["Calibration sessions", calibration.length], ["Calibration decisions", decisions.length], ["Promotion cases", promotions.length]].map(([label, count]) => <article className="rounded-2xl bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{count}</p></article>)}</div><section className="mt-6 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Correlated immutable events</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Time</th><th>Entity</th><th>Action</th><th>Correlation</th></tr></thead><tbody>{audits.map((item) => <tr className="border-b last:border-0" key={item.id}><td className="py-3">{item.createdAt.toISOString()}</td><td>{item.entityType} · {item.entityId ?? "—"}</td><td>{item.action}</td><td className="font-mono text-xs">{item.correlationId}</td></tr>)}</tbody></table></section></>;
}
