import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { assignAssetAction, createAssetAction, reportAssignedAssetLostAction, returnAssetAction, sendAssetReturnRemindersAction, updateAssetStatusAction } from "./actions";

const conditions = ["NEW", "GOOD", "FAIR", "DAMAGED", "UNUSABLE"];

export default async function AssetsAdminPage() {
  const auth = await requireAnyPermission(["asset.manage", "asset.assign", "asset.return"]);
  const organizationId = auth.user.organizationId;
  const [assets, employees, assignments] = await Promise.all([
    prisma.hrAsset.findMany({ where: { organizationId }, orderBy: [{ status: "asc" }, { assetTag: "asc" }], take: 500 }),
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: { employeeNumber: "asc" } }),
    prisma.hrAssetAssignment.findMany({ where: { organizationId }, include: { asset: true, employee: true }, orderBy: { assignedAt: "desc" }, take: 500 }),
  ]);
  return <>
    <h1 className="text-3xl font-bold">Asset management</h1><p className="mt-2 text-slate-600">Serialized inventory, employee custody, receipt acknowledgement, return condition, and permanent assignment history.</p>
    <form action={sendAssetReturnRemindersAction} className="mt-6 flex flex-wrap items-end gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-4"><label className="text-sm font-semibold">Reminder date<input className="input mt-1" name="asOf" type="date" required /></label><button className="btn btn-secondary">Queue seven-day return reminders</button></form>
    <div className="mt-5 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Register asset</h2><form action={createAssetAction} className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" name="assetTag" placeholder="Asset ID/tag" required /><input className="input" name="type" placeholder="Type, e.g. Laptop" required /><input className="input" name="name" placeholder="Asset name" required /><input className="input" name="manufacturer" placeholder="Manufacturer" /><input className="input" name="model" placeholder="Model" /><input className="input" name="serialNumber" placeholder="Serial number" /><input className="input" name="purchaseDate" type="date" /><input className="input" name="purchaseValue" inputMode="decimal" placeholder="Purchase value" /><input className="input" name="currency" defaultValue="NGN" maxLength={3} required /><select className="input" name="condition">{conditions.map((condition) => <option key={condition}>{condition}</option>)}</select><textarea className="input md:col-span-2" name="notes" placeholder="Notes" /><button className="btn btn-primary md:col-span-2">Register asset</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Assign available asset</h2><form action={assignAssetAction} className="mt-4 grid gap-3"><select className="input" name="assetId" required><option value="">Available asset</option>{assets.filter(({ status }) => status === "AVAILABLE").map((asset) => <option value={asset.id} key={asset.id}>{asset.assetTag} — {asset.name} ({asset.condition})</option>)}</select><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Assigned date<input className="input mt-1" name="assignedAt" type="date" required /></label><label className="text-sm font-semibold">Expected return<input className="input mt-1" name="expectedReturnAt" type="date" /></label></div><select className="input" name="issueCondition">{conditions.map((condition) => <option key={condition}>{condition}</option>)}</select><textarea className="input" name="issueNotes" placeholder="Issue notes" /><button className="btn btn-primary">Assign asset</button></form></section>
    </div>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Inventory</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Asset</th><th>Details</th><th>Condition</th><th>Status</th><th>Status control</th></tr></thead><tbody>{assets.map((asset) => <tr className="border-b last:border-0 align-top" key={asset.id}><td className="py-3">{asset.assetTag} — {asset.name}<br /><span className="text-xs text-slate-500">{asset.type}</span></td><td>{asset.manufacturer} {asset.model}<br /><span className="text-xs text-slate-500">{asset.serialNumber || "No serial"}{asset.purchaseValue ? ` · ${asset.currency} ${asset.purchaseValue.toFixed(2)}` : ""}</span></td><td>{asset.condition}</td><td>{asset.status}</td><td>{asset.status !== "ASSIGNED" ? <form action={updateAssetStatusAction} className="grid gap-2"><input type="hidden" name="assetId" value={asset.id} /><div className="flex gap-2"><select className="input" name="status" defaultValue={asset.status}>{["AVAILABLE", "UNDER_REPAIR", "LOST", "RETIRED", "DISPOSED"].map((status) => <option key={status}>{status}</option>)}</select><select className="input" name="condition" defaultValue={asset.condition}>{conditions.map((condition) => <option key={condition}>{condition}</option>)}</select></div><input className="input" name="reason" placeholder="Change reason" required /><button className="text-left font-semibold text-teal-700">Update status</button></form> : "Return or report assignment first"}</td></tr>)}</tbody></table></section>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Assignment history</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Asset</th><th>Employee</th><th>Custody</th><th>Condition</th><th>Status</th><th>Action</th></tr></thead><tbody>{assignments.map((assignment) => <tr className="border-b last:border-0 align-top" key={assignment.id}><td className="py-3">{assignment.asset.assetTag} — {assignment.asset.name}</td><td>{assignment.employee.employeeNumber} — {assignment.employee.legalFirstName} {assignment.employee.lastName}</td><td>{assignment.assignedAt.toLocaleDateString()} {assignment.expectedReturnAt ? `· due ${assignment.expectedReturnAt.toLocaleDateString()}` : ""}<br /><span className="text-xs text-slate-500">{assignment.acknowledgedAt ? `Acknowledged ${assignment.acknowledgedAt.toLocaleDateString()}` : "Awaiting acknowledgement"}</span></td><td>Issued {assignment.issueCondition}{assignment.returnCondition ? ` · returned ${assignment.returnCondition}` : ""}</td><td>{assignment.status}</td><td>{assignment.status === "ACTIVE" ? <div className="grid gap-3"><form action={returnAssetAction} className="grid gap-2"><input type="hidden" name="assignmentId" value={assignment.id} /><input className="input" name="returnedAt" type="date" required /><select className="input" name="returnCondition">{conditions.map((condition) => <option key={condition}>{condition}</option>)}</select><input className="input" name="returnNotes" placeholder="Return notes" required /><button className="text-left font-semibold text-teal-700">Record return</button></form><form action={reportAssignedAssetLostAction} className="flex gap-2"><input type="hidden" name="assignmentId" value={assignment.id} /><input className="input" name="reason" placeholder="Loss report" required /><button className="font-semibold text-red-700">Report lost</button></form></div> : assignment.returnedAt?.toLocaleDateString() ?? "—"}</td></tr>)}</tbody></table></section>
  </>;
}
