import Link from "next/link";
import { ArrowLeft, Check, LogIn, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { HrPasswordResetShell, ResetHeading } from "@/components/HrPasswordResetShell";
import { completeResetAction, requestResetAction } from "./actions";

export default async function ResetPage({ searchParams }: { searchParams: Promise<{ requested?: string; complete?: string; stage?: string; error?: string }> }) {
  const params = await searchParams;
  if (params.complete) return <HrPasswordResetShell variant="complete"><ResetHeading icon={Check} title="You’re all set!">Your password has been reset successfully. You can now sign in using your new password.</ResetHeading><div className="hr-reset-success"><Mail /><span>A confirmation has been queued for your work email.</span></div><Link className="hr-reset-primary" href="/hr/login"><LogIn />Sign in to your account</Link></HrPasswordResetShell>;
  if (params.stage === "new") return <HrPasswordResetShell variant="new"><ResetHeading icon={LockKeyhole} title="Reset your password">Enter and confirm your new password.</ResetHeading>{params.error && <p className="hr-reset-error" role="alert">The reset link is invalid, expired, or the password does not meet policy.</p>}<form action={completeResetAction} className="hr-reset-form"><label>New password<span><LockKeyhole /><input name="password" type="password" minLength={12} autoComplete="new-password" required /></span></label><p className="hr-reset-policy">Use at least 12 characters with uppercase, lowercase, a number, and a symbol.</p><button className="hr-reset-primary"><LockKeyhole />Reset password</button></form><div className="hr-reset-divider">or</div><Link className="hr-reset-secondary" href="/hr/login"><ArrowLeft />Back to sign in</Link></HrPasswordResetShell>;
  if (params.requested) return <HrPasswordResetShell variant="sent"><ResetHeading icon={Mail} title="Check your work email">If an active account exists, a secure one-time reset link has been sent.</ResetHeading><div className="hr-reset-success"><ShieldCheck /><span>The secure link expires automatically and can only be used once.</span></div><Link className="hr-reset-secondary" href="/hr/password-reset"><ArrowLeft />Back to email</Link></HrPasswordResetShell>;
  return <HrPasswordResetShell variant="request"><ResetHeading icon={LockKeyhole} title="Password reset">Enter your work email and we’ll send you a secure one-time link to continue.</ResetHeading>{params.error && <p className="hr-reset-error" role="alert">The reset link is invalid or expired.</p>}<form action={requestResetAction} className="hr-reset-form"><label>Work email<span><Mail /><input name="email" type="email" placeholder="you@company.com" autoComplete="email" required /></span></label><button className="hr-reset-primary"><ShieldCheck />Send secure reset link</button></form><div className="hr-reset-divider">or</div><Link className="hr-reset-secondary" href="/hr/login"><ArrowLeft />Back to sign in</Link></HrPasswordResetShell>;
}
