import Link from "next/link";
import { ArrowLeft, Check, LogIn, LockKeyhole, Mail, RefreshCw, ShieldCheck } from "lucide-react";
import { HrPasswordResetShell, ResetHeading } from "@/components/HrPasswordResetShell";
import { HrResetRedirect } from "@/components/HrResetRedirect";
import { completeResetAction, requestResetAction, resendResetCodeAction, restartResetAction, verifyResetCodeAction } from "./actions";
const verificationErrors: Record<string, string> = { invalid: "That verification code is invalid.", expired: "That verification code has expired. Request a new code.", attempts: "Too many verification attempts. Request a new code.", cooldown: "Please wait 60 seconds before requesting another code." };
export default async function ResetPage({ searchParams }: { searchParams: Promise<{ complete?: string; stage?: string; error?: string; resent?: string }> }) {
  const params = await searchParams;
  if (params.complete) return <HrPasswordResetShell variant="complete"><ResetHeading icon={Check} title="You’re all set!">Your password has been reset successfully. You can now sign in using your new password.</ResetHeading><div className="hr-reset-success"><Mail /><span>A confirmation has been queued for your work email.</span></div><HrResetRedirect /><Link className="hr-reset-primary" href="/hr/login"><LogIn />Sign in to your account</Link></HrPasswordResetShell>;
  if (params.stage === "new") return <HrPasswordResetShell variant="new"><ResetHeading icon={LockKeyhole} title="Reset your password">Enter and confirm your new password.</ResetHeading>{params.error && <p className="hr-reset-error" role="alert">{params.error === "mismatch" ? "Passwords do not match." : params.error === "short" ? "Password must be at least 8 characters." : "Your password reset session expired. Start again."}</p>}<form action={completeResetAction} className="hr-reset-form"><label>New password<span><LockKeyhole /><input name="password" type="password" minLength={8} maxLength={128} autoComplete="new-password" required /></span></label><label>Confirm new password<span><LockKeyhole /><input name="confirmation" type="password" minLength={8} maxLength={128} autoComplete="new-password" required /></span></label><p className="hr-reset-policy">Use at least 8 characters.</p><button className="hr-reset-primary"><LockKeyhole />Reset password</button></form></HrPasswordResetShell>;
  if (params.stage === "verify") return <HrPasswordResetShell variant="sent"><ResetHeading icon={Mail} title="Check your work email">If an active HR account exists for that address, we sent a 6-digit verification code.</ResetHeading>{params.error && <p className="hr-reset-error" role="alert">{verificationErrors[params.error] ?? verificationErrors.invalid}</p>}{params.resent && <p className="hr-reset-success" role="status">A new code has been requested.</p>}<form action={verifyResetCodeAction} className="hr-reset-form"><label>Verification code<span><ShieldCheck /><input aria-describedby="reset-code-help" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} placeholder="123456" required autoFocus /></span></label><p id="reset-code-help" className="hr-reset-policy">The code expires in 10 minutes and can only be used once.</p><button className="hr-reset-primary"><ShieldCheck />Verify code</button></form><form action={resendResetCodeAction}><button className="hr-reset-secondary"><RefreshCw />Resend code</button></form><form action={restartResetAction}><button className="hr-reset-secondary"><ArrowLeft />Use a different email</button></form></HrPasswordResetShell>;
  return <HrPasswordResetShell variant="request"><ResetHeading icon={LockKeyhole} title="Password reset">Enter your work email and we’ll send you a 6-digit verification code.</ResetHeading>{params.error === "session" && <p className="hr-reset-error" role="alert">Your password reset session expired. Start again.</p>}<form action={requestResetAction} className="hr-reset-form"><label>Work email<span><Mail /><input name="email" type="email" placeholder="you@company.com" autoComplete="email" required /></span></label><button className="hr-reset-primary"><ShieldCheck />Send verification code</button></form><div className="hr-reset-divider">or</div><Link className="hr-reset-secondary" href="/hr/login"><ArrowLeft />Back to sign in</Link></HrPasswordResetShell>;
}
