import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { cancelLifecycleAction, completeLifecycleTaskAction, createStandardLifecycleTemplateAction, sendLifecycleRemindersAction, skipLifecycleTaskAction, startLifecycleAction } from "./actions";

export default async function LifecycleAdminPage() {
  const auth = await requireAnyPermission(["workflow.create", "workflow.assign", "workflow.review", "workflow.override"]);
  const [templates, employees, instances] = await Promise.all([
    prisma.hrLifecycleTemplate.findMany({ where: { organizationId: auth.user.organizationId, active: true }, orderBy: [{ type: "asc" }, { version: "desc" }] }),
    prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId, archivedAt: null }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }] }),
    prisma.hrLifecycleInstance.findMany({ where: { organizationId: auth.user.organizationId }, include: { employee: true, template: true, tasks: { include: { assignedUser: true }, orderBy: [{ dueAt: "asc" }, { createdAt: "asc" }] } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  return <main>
    <h1 className="text-3xl font-bold">Onboarding & offboarding</h1>
    <p className="mt-2 text-slate-600">Versioned checklists, dependency-aware tasks, accountable ownership, reminders and permanent completion history.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-3">
      {auth.permissions.has("workflow.create") && <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Publish standard template</h2><p className="mt-2 text-sm text-slate-600">Creates a new immutable template version.</p><form action={createStandardLifecycleTemplateAction} className="mt-4 grid gap-3"><select className="input" name="type"><option>ONBOARDING</option><option>OFFBOARDING</option></select><button className="btn btn-secondary">Publish version</button></form></section>}
      {auth.permissions.has("workflow.assign") && <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Start employee lifecycle</h2><form action={startLifecycleAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="templateId" required><option value="">Template</option>{templates.map((template) => <option value={template.id} key={template.id}>{template.type} · {template.name} v{template.version}</option>)}</select><label className="text-sm font-semibold">Effective date<input className="input mt-1" name="effectiveDate" type="date" required /></label><select className="input" name="knowledgeTransferToId"><option value="">Knowledge-transfer employee (offboarding)</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><button className="btn btn-primary">Start checklist</button></form></section>}
      {auth.permissions.has("workflow.assign") && <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Due-task reminders</h2><p className="mt-2 text-sm text-slate-600">Queues reference-only reminders for overdue tasks and tasks due within three days.</p><form action={sendLifecycleRemindersAction} className="mt-4 flex gap-3"><input className="input" name="asOf" type="date" required /><button className="btn btn-secondary">Queue reminders</button></form></section>}
    </div>
    <section className="mt-6 space-y-5">{instances.length === 0 ? <div className="rounded-2xl bg-white p-6 text-slate-600">No onboarding or offboarding workflows yet.</div> : instances.map((instance) => <article className="rounded-2xl bg-white p-5" key={instance.id}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-bold">{instance.employee.employeeNumber} — {instance.employee.legalFirstName} {instance.employee.lastName}</h2><p className="text-sm text-slate-600">{instance.type} · {instance.template.name} v{instance.template.version} · effective {instance.effectiveDate.toLocaleDateString()}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{instance.status}</span>{instance.status === "ACTIVE" && auth.permissions.has("workflow.override") && <form action={cancelLifecycleAction} className="flex gap-2"><input type="hidden" name="instanceId" value={instance.id} /><input className="input max-w-44" name="reason" placeholder="Cancellation reason" required /><button className="font-semibold text-red-700">Cancel</button></form>}</div></div>
      <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Task</th><th>Owner</th><th>Due</th><th>Status</th><th>Completion</th></tr></thead><tbody>{instance.tasks.map((task) => <tr className="border-b last:border-0 align-top" key={task.id}><td className="py-3">{task.title}<br /><span className="text-xs text-slate-500">{task.required ? "Required" : "Optional"}{task.predecessorKeys.length ? ` · after ${task.predecessorKeys.join(", ")}` : ""}</span></td><td>{task.assignedUser?.email ?? task.ownerType}</td><td>{task.dueAt.toLocaleDateString()}</td><td>{task.status}</td><td>{["PENDING", "IN_PROGRESS"].includes(task.status) && auth.permissions.has("workflow.override") ? <form action={completeLifecycleTaskAction} className="grid min-w-56 gap-2"><input type="hidden" name="taskId" value={task.id} /><input className="input" name="completionNotes" placeholder="Completion notes" required /><input className="input" name="evidenceReference" placeholder="Evidence reference (no secrets)" /><button className="text-left font-semibold text-teal-700">Complete</button></form> : task.status === "BLOCKED" ? "Waiting for prerequisites" : task.completionNotes ?? task.skipReason ?? "—"}{!task.required && ["BLOCKED", "PENDING", "IN_PROGRESS"].includes(task.status) && auth.permissions.has("workflow.override") && <form action={skipLifecycleTaskAction} className="mt-2 flex gap-2"><input type="hidden" name="taskId" value={task.id} /><input className="input" name="reason" placeholder="Skip reason" required /><button className="font-semibold text-amber-700">Skip</button></form>}</td></tr>)}</tbody></table></div>
    </article>)}</section>
  </main>;
}
