import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

export const dynamic = "force-dynamic";
export default async function PayrollComplianceExceptionsPage() {
  const auth = await requirePermission("payroll.exception.read");
  const exceptions = await prisma.hrPayrollComplianceException.findMany({ where: { organizationId: auth.user.organizationId }, orderBy: { openedAt: "desc" }, take: 100, select: { id: true, employeeId: true, payrollRunId: true, rtaCode: true, blockerCode: true, affectedInput: true, openedAt: true, assignedOwnerId: true, status: true } });
  return <main><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-amber-700">Governed payroll review</p><h1 className="mt-2 text-3xl font-bold">Nigeria compliance holds</h1><p className="mt-2 max-w-3xl text-slate-600">Unresolved employees stay linked to their original period. Resolution requires authority, an approved rule and deterministic recalculation.</p></div><Link className="rounded-xl border px-4 py-2 font-semibold" href="/hr/admin/payroll/unit9">Payroll runs</Link></div><section className="mt-8 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Employee</th><th className="p-4">Run</th><th className="p-4">RTA</th><th className="p-4">Blocker</th><th className="p-4">Input</th><th className="p-4">Opened</th><th className="p-4">Owner</th><th className="p-4">Status</th></tr></thead><tbody>{exceptions.map((item)=><tr className="border-t" key={item.id}><td className="p-4 font-medium">{item.employeeId}</td><td className="p-4">{item.payrollRunId}</td><td className="p-4">{item.rtaCode}</td><td className="p-4 font-mono text-xs">{item.blockerCode}</td><td className="p-4">{item.affectedInput ?? "—"}</td><td className="p-4">{item.openedAt.toISOString()}</td><td className="p-4">{item.assignedOwnerId ?? "Unassigned"}</td><td className="p-4"><span className="rounded-full bg-amber-100 px-2 py-1 font-semibold text-amber-900">{item.status}</span></td></tr>)}</tbody></table>{exceptions.length===0&&<p className="p-6 text-slate-600">No compliance holds exist for this tenant.</p>}</section><p className="mt-4 text-sm text-slate-500">Sensitive bank, tax identifier, pension identifier and reviewer-note fields are intentionally omitted.</p></main>;
}
