import { describe, expect, it } from 'vitest';
import { adminActionAuditName, canDownloadDocument, generateApplicationId, getStage1ApprovalEffects, initialApplicationSchema, isAccessCodeUsable, isStageStatus, maskSensitive, toStageStatus } from '../src/lib/hiring';
import { renderSubmittedDocumentText } from '../src/lib/pdf';

describe('hiring workflow helpers',()=>{
  it('generates formatted application ids',()=>{expect(generateApplicationId(41,new Date('2026-06-21T00:00:00Z'))).toBe('ZA-APP-2026-00041')});
  it('validates Stage 1 payloads',()=>{const result=initialApplicationSchema.safeParse({fullName:'Ada Lovelace',email:'ada@example.com',phone:'123456789',location:'Lagos',role:'Data Analyst',workMode:'Remote',experienceLevel:'Mid',skills:'SQL, Python',portfolioUrl:'https://github.com/ada',message:'I am interested in this role because I can contribute immediately.',privacyConsent:'on',signatureName:'Ada Lovelace',signatureConsent:'on'});expect(result.success).toBe(true)});
  it('narrows database status strings to valid stage statuses',()=>{expect(isStageStatus('Submitted')).toBe(true);expect(isStageStatus('Unexpected')).toBe(false);expect(toStageStatus('Approved')).toBe('Approved');expect(toStageStatus('Unexpected')).toBe('Locked');expect(toStageStatus(null,'Available')).toBe('Available')});
  it('blocks and allows downloads according to signature/submission state',()=>{expect(canDownloadDocument('Under Review',true,'2026-06-21')).toBe(true);expect(canDownloadDocument('Available',true,'2026-06-21')).toBe(false);expect(canDownloadDocument('Under Review',false,'2026-06-21')).toBe(false);expect(canDownloadDocument('Under Review',true,null)).toBe(false)});
  it('masks sensitive values in generated document text',()=>{const doc=renderSubmittedDocumentText({title:'Candidate Information',applicantName:'Ada',applicationId:'ZA-APP-2026-00041',fields:[{label:'ID number',value:'12345678901',sensitive:true}],signatureName:'Ada',submittedAt:'2026-06-21',version:1,status:'Submitted'});expect(doc).toContain('*******8901');expect(doc).not.toContain('12345678901');expect(maskSensitive('abcdef')).toBe('****cdef')});
  it('expires and verifies access code usability',()=>{const now=new Date('2026-06-22T12:00:00Z');expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T12:01:00Z')},now)).toBe(true);expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T11:59:00Z')},now)).toBe(false);expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T12:01:00Z'),usedAt:now},now)).toBe(false)});
  it('describes Stage 1 approval unlocking Stage 2',()=>{expect(getStage1ApprovalEffects()).toEqual({stage1Status:'Approved',stage2Status:'Available',applicationStatus:'Candidate Information Required',currentStageOrder:2})});
  it('maps admin actions to audit log actions',()=>{expect(adminActionAuditName('approve')).toBe('Admin approved Stage 1');expect(adminActionAuditName('reject')).toBe('Admin rejected Stage 1');expect(adminActionAuditName('correction')).toBe('Admin requested correction')});
});
