import { describe, expect, it } from 'vitest';
import { adminActionAuditName, canDownloadDocument, isStage1DownloadEligible, sanitizeDownloadFilenamePart, generateApplicationId, getStage1ApprovalEffects, initialApplicationSchema, isAccessCodeUsable, isStageStatus, maskSensitive, toStage1SubmissionPayload, toStageStatus } from '../src/lib/hiring';
import { renderSubmittedDocumentText } from '../src/lib/pdf';
import { buildFullLegalName, normalizePhoneForCountry } from '../src/lib/phone';
import { experienceLevelOptions, roleAppliedForOptions } from '../src/lib/recruitment-options';
import { DEFAULT_UPLOAD_MAX_BYTES, MAX_CV_BYTES, validateCvFile } from '../src/lib/storage';
import { existsSync, readFileSync } from 'node:fs';

const payload = { firstName:'Ada', middleInitial:'B', lastName:'Lovelace', email:'ada@example.com', phoneCountryIso:'NG', phoneNational:'08012345678', location:'Lagos', role:'Data Analyst', workMode:'Remote', experienceLevel:'Mid-Level', skills:'SQL, Python', portfolioUrl:'https://github.com/ada', message:'I am interested in this role because I can contribute immediately.', privacyConsent:'on', signatureName:'Ada B Lovelace', signatureConsent:'on' };
const file = (name:string, type:string, size=12) => new File([new Uint8Array(size)], name, { type });
const utf16PdfHex = (value:string) => `<FEFF${[...value].map((char)=>char.charCodeAt(0).toString(16).padStart(4,'0')).join('').toUpperCase()}>`;
const utf16PdfHexFragment = (value:string) => utf16PdfHex(value).slice(5,-1);

describe('hiring workflow helpers',()=>{
  it('generates formatted application ids',()=>{expect(generateApplicationId(41,new Date('2026-06-21T00:00:00Z'))).toBe('ZA-APP-2026-00041')});
  it('validates Stage 1 payloads and computes submitted name/phone/role',()=>{const result=initialApplicationSchema.safeParse(payload);expect(result.success).toBe(true);if(result.success){const data=toStage1SubmissionPayload(result.data);expect(data.fullName).toBe('Ada B Lovelace');expect(data.phoneE164).toBe('+2348012345678');expect(data.roleAppliedFor).toBe('Data Analyst')}});
  it('generates full legal names from split fields',()=>{expect(buildFullLegalName('Ada','B','Lovelace')).toBe('Ada B Lovelace');expect(buildFullLegalName('Ada','','Lovelace')).toBe('Ada Lovelace')});
  it('exposes required role and experience dropdown values',()=>{expect(roleAppliedForOptions).toContain('Junior Frontend Developer');expect(roleAppliedForOptions).toContain('Other');expect(experienceLevelOptions).toContain('No professional experience yet');expect(experienceLevelOptions).toContain('Manager')});
  it('accepts valid Nigerian, US, and UK phone numbers and normalizes E.164 values',()=>{expect(normalizePhoneForCountry('NG','0801 234 5678')).toMatchObject({valid:true,e164:'+2348012345678',countryName:'Nigeria',dialCode:'+234',nationalNumber:'8012345678'});expect(normalizePhoneForCountry('US','(415) 555-2671')).toMatchObject({valid:true,e164:'+14155552671'});expect(normalizePhoneForCountry('GB','07911 123456')).toMatchObject({valid:true,e164:'+447911123456'});expect(normalizePhoneForCountry('NG','+234 801-234-5678')).toMatchObject({valid:true,e164:'+2348012345678'});expect(normalizePhoneForCountry('GB','+44 20 7946 0958')).toMatchObject({valid:true,e164:'+442079460958'})});
  it('rejects truly invalid or unsafe phone values without overly strict formatting checks',()=>{expect(normalizePhoneForCountry('NG','1111111111')).toMatchObject({valid:false});expect(normalizePhoneForCountry('US','123')).toMatchObject({valid:false});expect(normalizePhoneForCountry('ZZ','08012345678')).toMatchObject({valid:false,error:'Select a valid country.'});expect(initialApplicationSchema.safeParse({...payload,phoneNational:'123'}).success).toBe(false)});
  it('accepts PDF/DOC/DOCX/JPG/JPEG/PNG/WEBP uploads and rejects unsupported formats',()=>{expect(validateCvFile(file('cv.pdf','application/pdf'))).toBeNull();expect(validateCvFile(file('cv.doc','application/msword'))).toBeNull();expect(validateCvFile(file('cv.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document'))).toBeNull();expect(validateCvFile(file('cv.jpg','image/jpeg'))).toBeNull();expect(validateCvFile(file('cv.jpeg','image/pjpeg'))).toBeNull();expect(validateCvFile(file('cv.png','image/png'))).toBeNull();expect(validateCvFile(file('cv.webp','image/webp'))).toBeNull();expect(validateCvFile(file('cv.pdf',''))).toBeNull();expect(validateCvFile(file('cv.docx','application/octet-stream'))).toBeNull();expect(validateCvFile(file('cv.svg','image/svg+xml'))).toContain('PDF, DOC, DOCX, JPG, JPEG, PNG, or WEBP');expect(validateCvFile(file('cv.exe','application/octet-stream'))).toContain('PDF, DOC, DOCX, JPG, JPEG, PNG, or WEBP')});
  it('returns a file-specific error when the Stage 1 upload is missing',()=>{expect(validateCvFile(null)).toContain('Upload your CV')});
  it('enforces the 20MB Stage 1 upload limit by default',()=>{expect(DEFAULT_UPLOAD_MAX_BYTES).toBe(20971520);expect(MAX_CV_BYTES).toBe(20971520);expect(validateCvFile(file('cv.pdf','application/pdf',DEFAULT_UPLOAD_MAX_BYTES))).toBeNull();expect(validateCvFile(file('cv.pdf','application/pdf',DEFAULT_UPLOAD_MAX_BYTES-1))).toBeNull();expect(validateCvFile(file('cv.pdf','application/pdf',DEFAULT_UPLOAD_MAX_BYTES+1))).toContain('20MB or smaller')});

  it('uses the exact Stage 1 FormData keys expected by the server schema',()=>{const page=readFileSync('src/app/apply/Stage1ApplicationForm.tsx','utf8');['firstName','middleInitial','lastName','email','phoneCountryIso','phoneNational','location','role','otherRole','workMode','experienceLevel','skills','portfolioUrl','message','cv','privacyConsent','signatureName','signatureConsent'].forEach((name)=>expect(page).toContain(`name="${name}"`))});
  it('returns field-specific schema failures for missing required name and signature confirmation',()=>{const missingName=initialApplicationSchema.safeParse({...payload,firstName:''});expect(missingName.success).toBe(false);if(!missingName.success)expect(missingName.error.issues.some((issue)=>issue.path[0]==='firstName'&&issue.message.includes('first name'))).toBe(true);const missingSignature=initialApplicationSchema.safeParse({...payload,signatureConsent:undefined});expect(missingSignature.success).toBe(false);if(!missingSignature.success)expect(missingSignature.error.issues.some((issue)=>issue.path[0]==='signatureConsent')).toBe(true)});
  it('narrows database status strings to valid stage statuses',()=>{expect(isStageStatus('Submitted')).toBe(true);expect(isStageStatus('Unexpected')).toBe(false);expect(toStageStatus('Approved')).toBe('Approved');expect(toStageStatus('Unexpected')).toBe('Locked');expect(toStageStatus(null,'Available')).toBe('Available')});
  it('blocks and allows downloads according to full Stage 1 eligibility state',()=>{expect(canDownloadDocument('Approved',true,'2026-06-21','2026-06-21')).toBe(true);expect(canDownloadDocument('Completed',true,'2026-06-21','2026-06-21')).toBe(true);expect(canDownloadDocument('Under Review',true,'2026-06-21','2026-06-21')).toBe(false);expect(canDownloadDocument('Available',true,'2026-06-21','2026-06-21')).toBe(false);expect(canDownloadDocument('Approved',false,'2026-06-21','2026-06-21')).toBe(false);expect(canDownloadDocument('Approved',true,null,'2026-06-21')).toBe(false);expect(canDownloadDocument('Approved',true,'2026-06-21',null)).toBe(false);expect(isStage1DownloadEligible({stagePresent:true,submissionPresent:true,submissionSubmitted:true,signaturePresent:true,signatureConfirmed:true,signedAtPresent:true,stageStatus:'Approved'})).toBe(true);expect(isStage1DownloadEligible({stagePresent:true,submissionPresent:true,submissionSubmitted:true,signaturePresent:true,signatureConfirmed:true,signedAtPresent:false,stageStatus:'Approved'})).toBe(false)});
  it('sanitizes Stage 1 PDF download filenames',()=>{expect(sanitizeDownloadFilenamePart('ZA/APP 2026:00041')).toBe('ZA-APP-2026-00041');expect(`${sanitizeDownloadFilenamePart('ZA/APP 2026:00041')}-stage-1-official.pdf`).toBe('ZA-APP-2026-00041-stage-1-official.pdf')});
  it('renders official Zentric document structure and masks sensitive values',()=>{const doc=renderSubmittedDocumentText({title:'Candidate Information',applicantName:'Ada',applicationId:'ZA-APP-2026-00041',fields:[{label:'ID number',value:'12345678901',sensitive:true}],signatureName:'Ada',submittedAt:'2026-06-21',version:1,status:'Submitted'});expect(doc).toContain('Zentric Analytics Ltd');expect(doc).toContain('PRIVATE & CONFIDENTIAL');expect(doc).toContain('Employment Application');expect(doc).toContain('Candidate Data Privacy Acknowledgement');expect(doc).toContain('For Zentric Use Only');expect(doc).toContain('*******8901');expect(doc).not.toContain('12345678901');expect(maskSensitive('abcdef')).toBe('****cdef')});
  it('expires and verifies access code usability',()=>{const now=new Date('2026-06-22T12:00:00Z');expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T12:01:00Z')},now)).toBe(true);expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T11:59:00Z')},now)).toBe(false);expect(isAccessCodeUsable({expiresAt:new Date('2026-06-22T12:01:00Z'),usedAt:now},now)).toBe(false)});
  it('describes Stage 1 approval unlocking Stage 2',()=>{expect(getStage1ApprovalEffects()).toEqual({stage1Status:'Approved',stage2Status:'Available',applicationStatus:'Candidate Information Required',currentStageOrder:2})});
  it('maps admin actions to audit log actions',()=>{expect(adminActionAuditName('approve')).toBe('Admin approved Stage 1');expect(adminActionAuditName('reject')).toBe('Admin rejected Stage 1');expect(adminActionAuditName('correction')).toBe('Admin requested correction')});
});

import { createAdminSessionToken, hashAdminPassword, verifyAdminPassword, verifyAdminSessionToken } from '../src/lib/admin-auth';
import { renderSubmittedDocumentPdf, STAGE_1_TEMPLATE_PATH } from '../src/lib/pdf';
import { hashRateLimitKey } from '../src/lib/rate-limit';
import { selectedStorageProvider } from '../src/lib/storage';

describe('production hardening helpers',()=>{
  it('hashes and verifies admin passwords without plaintext storage',()=>{const hash=hashAdminPassword('correct horse battery staple','abc123abc123abc1');expect(hash).toMatch(/^pbkdf2_sha256\$/);expect(verifyAdminPassword('correct horse battery staple',hash)).toBe(true);expect(verifyAdminPassword('wrong',hash)).toBe(false)});
  it('signs short-lived admin sessions',()=>{process.env.ADMIN_SESSION_SECRET='x'.repeat(40);const token=createAdminSessionToken('admin@example.com',1000);expect(verifyAdminSessionToken(token,2000)?.email).toBe('admin@example.com');expect(verifyAdminSessionToken(token.replace(/.$/,'x'),2000)).toBeNull();expect(verifyAdminSessionToken(token,1000+5*60*60*1000)).toBeNull()});
  it('generates the Stage 1 PDF from the official template and overlays applicant values',async()=>{expect(existsSync(STAGE_1_TEMPLATE_PATH)).toBe(true);const pdf=await renderSubmittedDocumentPdf({title:'Candidate Information',applicantName:'Ada B Lovelace',applicationId:'ZA-APP-2026-00041',fields:[{label:'First name',value:'Ada'},{label:'Middle initial',value:'B'},{label:'Last name',value:'Lovelace'},{label:'Email',value:'ada@example.com'},{label:'Phone country name',value:'Nigeria'},{label:'Phone E164',value:'+2348012345678'},{label:'Phone display',value:'Nigeria +2348012345678'},{label:'Location',value:'Lagos, Nigeria'},{label:'Role applied for',value:'Data Analyst'},{label:'Work mode',value:'Remote'},{label:'Experience level',value:'Mid-Level'},{label:'Skills',value:'SQL, Python'},{label:'Portfolio URL',value:'https://github.com/ada'},{label:'Message',value:'I can contribute immediately.'},{label:'Privacy consent',value:'true'}],documents:[{label:'Stage 1 CV',value:'ada-cv.pdf (application/pdf, 1000 bytes)'}],signatureName:'Ada B Lovelace',submittedAt:'2026-06-21T10:00:00.000Z',signedAt:'2026-06-21T10:01:00.000Z',version:1,status:'Under Review'});const raw=pdf.toString('latin1');expect(raw.startsWith('%PDF-')).toBe(true);expect(raw).toContain('/Count 4');expect(raw).toContain('/FlateDecode');expect(raw).toContain(utf16PdfHexFragment('ZA-APP-2026-00041'));expect(raw).toContain(utf16PdfHexFragment('Ada B Lovelace'));expect(raw).not.toContain('session-token');expect(raw).not.toContain('123456');expect(raw).not.toContain('private/storage/key');expect(raw).not.toContain('secret-key')});
  it('selects local-private storage fallback and hashes rate-limit keys',()=>{delete process.env.PRIVATE_OBJECT_STORAGE_PROVIDER;expect(selectedStorageProvider()).toBe('local-private');const hashed=hashRateLimitKey('ip@example');expect(hashed).toHaveLength(64);expect(hashed).not.toContain('ip@example')});
});

describe('admin auth robustness',()=>{
  it('verifies correct passwords and rejects wrong passwords',()=>{const hash=hashAdminPassword('correct horse battery staple','abc123abc123abc1');expect(verifyAdminPassword('correct horse battery staple',hash)).toBe(true);expect(verifyAdminPassword('wrong',hash)).toBe(false)});
  it('normalizes ADMIN_EMAIL spaces and uppercase for matching diagnostics',async()=>{const mod=await import('../src/lib/admin-auth');process.env.ADMIN_EMAIL='  ADMIN@EXAMPLE.COM  ';process.env.ADMIN_PASSWORD_HASH=hashAdminPassword('pw','abc123abc123abc1');process.env.ADMIN_SESSION_SECRET='x'.repeat(40);const diagnostics=mod.buildAdminLoginDiagnostics(' admin@example.com ',true);expect(diagnostics.submittedEmailMatchesConfiguredEmail).toBe(true);expect(mod.getConfiguredAdminEmail()).toBe('admin@example.com')});
  it('verifies ADMIN_PASSWORD_HASH with surrounding spaces',()=>{const hash=`  ${hashAdminPassword('pw','abc123abc123abc1')}  `;expect(verifyAdminPassword('pw',hash)).toBe(true)});
  it('verifies ADMIN_PASSWORD_HASH with surrounding quotes',()=>{const hash=`"${hashAdminPassword('pw','abc123abc123abc1')}"`;expect(verifyAdminPassword('pw',hash)).toBe(true);expect(verifyAdminPassword('pw',`'${hashAdminPassword('pw','abc123abc123abc1')}'`)).toBe(true)});
  it('rejects ADMIN_PASSWORD_HASH values that include the variable name with safe diagnostics',async()=>{const mod=await import('../src/lib/admin-auth');process.env.ADMIN_EMAIL='admin@example.com';process.env.ADMIN_PASSWORD_HASH=`ADMIN_PASSWORD_HASH=${hashAdminPassword('pw','abc123abc123abc1')}`;process.env.ADMIN_SESSION_SECRET='x'.repeat(40);const diagnostics=mod.buildAdminLoginDiagnostics('admin@example.com',mod.verifyAdminPassword('pw'));expect(diagnostics.passwordHashConfigured).toBe(true);expect(diagnostics.passwordHashFormatValid).toBe(false);expect(diagnostics.passwordVerified).toBe(false)});
  it('fails safely for malformed hashes',async()=>{const mod=await import('../src/lib/admin-auth');for(const value of ['', 'pbkdf2_sha256', 'sha1$310000$salt$abcd', 'pbkdf2_sha256$0$salt$abcd', 'pbkdf2_sha256$abc$salt$abcd', 'pbkdf2_sha256$310000$$abcd', 'pbkdf2_sha256$310000$salt$not-hex']){expect(mod.parseAdminPasswordHash(value)).toBeNull();expect(mod.verifyAdminPassword('pw',value)).toBe(false)}});
  it('detects ADMIN_SESSION_SECRET shorter than 32 characters',async()=>{const mod=await import('../src/lib/admin-auth');expect(mod.isAdminSessionSecretLengthValid('x'.repeat(31))).toBe(false);expect(mod.isAdminSessionSecretLengthValid('x'.repeat(32))).toBe(true)});
  it('diagnostics never include secrets',async()=>{const mod=await import('../src/lib/admin-auth');process.env.ADMIN_EMAIL='admin@example.com';process.env.ADMIN_PASSWORD_HASH=hashAdminPassword('super-secret-password','abc123abc123abc1');process.env.ADMIN_SESSION_SECRET='secret-session-value-that-is-long-enough';const diagnostics=mod.buildAdminLoginDiagnostics('admin@example.com',false);const text=JSON.stringify(diagnostics);expect(text).not.toContain('admin@example.com');expect(text).not.toContain('super-secret-password');expect(text).not.toContain('pbkdf2_sha256');expect(text).not.toContain('abc123abc123abc1');expect(text).not.toContain('secret-session-value')});
});


describe('Stage 1 download and admin safety source checks',()=>{
  it('portal uses the same eligibility helper as the document route and shows safe messages',()=>{const portal=readFileSync('src/app/track/portal/page.tsx','utf8');const button=readFileSync('src/app/track/portal/Stage1DownloadButton.tsx','utf8');expect(portal).toContain('isStage1DownloadEligible');expect(portal).toContain('Approved and ready to download.');expect(portal).toContain('Available after this form is signed and approved.');expect(button).toContain('Download PDF');expect(button).toContain('Preparing PDF...');expect(button).toContain('Download failed. Please try again.');expect(button).toContain('Session expired. Request a new passcode.');});
  it('document route emits safe diagnostics, requires a session, no-store PDF headers, and delayed audit logging',()=>{const route=readFileSync('src/app/api/candidate/documents/stage-1/route.ts','utf8');expect(route).toContain('if (!session)');expect(route).toContain("return new NextResponse('Unauthorized', { status: 401");expect(route).toContain('verifiedSessionTokenHash: sha256(session)');expect(route).toContain('sessionExpiresAt: { gt: new Date() }');expect(route.indexOf('if (!session)')).toBeLessThan(route.indexOf('prisma.applicationAccessCode.findFirst'));expect(route.indexOf('if (!session)')).toBeLessThan(route.indexOf('const pdf = await renderSubmittedDocumentPdf'));expect(route).toContain('candidateDocumentDownloadDiagnostics');expect(route).toContain('Content-Type');expect(route).toContain('application/pdf');expect(route).toContain('Content-Disposition');expect(route).toContain('attachment; filename=');expect(route).toContain('-stage-1-official.pdf');expect(route).toContain('Cache-Control');expect(route).toContain('no-store');expect(route.indexOf('const pdf = await renderSubmittedDocumentPdf')).toBeLessThan(route.indexOf('auditLog.create'));expect(route).not.toContain('actorRef: app.applicant.email');expect(route).not.toContain('storageKey');expect(route).not.toContain('verifiedSessionTokenHash: session');});
  it('admin action catches failures, redirects with safe state, and revalidates list plus detail pages',()=>{const actions=readFileSync('src/app/admin/applications/actions.ts','utf8');expect(actions).toContain('try {');expect(actions).toContain('catch (error)');expect(actions).toContain('adminStageActionDiagnostics');expect(actions).toContain('warning=email_failed');expect(actions).toContain("revalidatePath('/admin/applications')");expect(actions).toContain('revalidatePath(`/admin/applications/${applicationId}`)');expect(actions).not.toContain('console.error');expect(actions).not.toContain('stack');});
});
