import { describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { calculateFrozenPayroll2026_8, deriveFrozenNg2026_8Binding, type Candidate2026_8Manifest } from "../src/lib/hr/payroll/unit9-engine-2026-8";
import { NG_2026_8_STATUS, NG_2026_8_VERSION } from "../src/lib/hr/payroll/nigeria-2026-8";
import { assertOfficialPayrollCandidateCertified, PAYROLL_CANDIDATE_MANIFEST_INVALID, PAYROLL_CANDIDATE_NOT_CERTIFIED, PAYROLL_CANDIDATE_VERSION_MISMATCH } from "../src/lib/hr/payroll/unit9-candidate-certification";
import { finalizeUnit9Run } from "../src/lib/hr/payroll/unit9-service";
import { acknowledgeUnit9RemittanceSimulation, createCorrectedUnit9Payslip, createUnit9PaymentBatch, createUnit9RemittanceAmendmentSimulation, createUnit9RemittanceBatch, generateUnit9FinancialOutputs, generateUnit9Payslips, publishUnit9Payslip, transitionUnit9PaymentBatch } from "../src/lib/hr/payroll/unit9-financial-service";

const manifest = (): Candidate2026_8Manifest => ({ employeeId: "employee-1", workRelationshipId: "relationship-1", assignmentId: "assignment-1", payrollPeriodId: "period-1", currency: "NGN", jurisdictionVersion: NG_2026_8_VERSION, engineVersion: "unit9-ng-2026.8", incomeEvidence: { employeeId: "employee-1", workRelationshipId: "relationship-1", assignmentId: "assignment-1", payrollPeriodId: "period-1", rta: "LAGOS", candidateVersion: NG_2026_8_VERSION, actualFrozenSalary: "70000", currentBonus: "0", otherTaxableEmploymentIncome: "VERIFIED_NONE", materiallyVariableMonthlyWage: "NO", ambiguousMultiEmployer: "NO", unusualPartialYearArrangement: "NO", evidenceCompletenessCertified: true, evidenceReferences: ["salary-record-1", "ledger-hash-1"], inputCertificationId: "cert-1", inputCertificationVersion: "v1" }, authoritativeSources: { salary: { recordId: "salary-record-1", versionHash: "salary-v1-hash", monthlyAmount: "70000", currency: "NGN", payFrequency: "MONTHLY", effectiveFrom: "2026-01-01T00:00:00.000Z" }, annualization: { ruleId: "annualization-1", ruleVersion: 1, frequency: "MONTHLY", periodsInTaxYear: 12, method: "GOVERNED_PERIODIC_SALARY_X_PERIODS_IN_TAX_YEAR", taxYear: 2026, certificationStatus: "CERTIFIED" }, ytd: { sourceLedgerHash: "ledger-hash-1", cutoff: "2026-08-01T00:00:00.000Z", priorBonusYtd: "0", payeDeducted: "0", payeRepaid: "0", entryIds: [] }, priorEmployer: { state: "NONE", income: "0", paye: "0", payeRepaid: "0" }, deductions: { amount: "0", sourceType: "TAX_RELIEF_CLAIM_VERSIONS", sourceRecordIds: [], sourceVersions: [], evidenceReferences: [], aggregateHash: "empty-relief-set" } }, auditExpectedAnnualSalary: "840000", auditPriorBonusYtd: "0", auditPayeDeductedYtd: "0", auditPayeRepaidYtd: "0", earnings: [{ code: "SALARY", sourceType: "UNIT8", sourceId: "salary-record-1", fixedAmount: "70000", taxableBaseCode: "EMPLOYMENT", ruleVersionReference: "salary-v1" }], paye: { priorYtdTaxableIncome: "0", priorYtdPaye: "0", priorPayeRepaid: "0", expectedAnnualEmploymentIncome: "840000", eligibleAnnualDeductions: "0", periodsElapsed: 8, periodsInTaxYear: 12, currentNonPeriodicPayments: "0", priorBonusPaidTaxYearToDate: "0", priorEmployerIncome: "0", priorEmployerPaye: "0", rules: { version: "not-authority", annualizationPeriods: 12, roundingScale: 2, bands: [] } } });

function certificationDb(input: { candidateVersion?: string; certification?: string; status?: string; certifiedAt?: Date | null; snapshotVersion?: string }) {
  return { hrPayrollAuthoritativeRun: { findFirst: vi.fn().mockResolvedValue({ id: "run-1", jurisdictionVersionId: "jurisdiction-1", createdAt: new Date("2026-08-01T00:00:00Z") }) }, hrPayrollJurisdictionVersion: { findFirst: vi.fn().mockResolvedValue({ id: "jurisdiction-1", ruleManifest: { ...(input.candidateVersion === undefined ? {} : { candidateVersion: input.candidateVersion }), ...(input.certification === undefined ? {} : { certification: input.certification }) }, ruleHash: "rule-hash", status: input.status ?? "TESTING", certifiedAt: input.certifiedAt ?? null, effectiveFrom: new Date("2026-01-01T00:00:00Z"), effectiveTo: null }) }, hrPayrollInputSnapshot: { findMany: vi.fn().mockResolvedValue([{ sourceManifest: { jurisdictionVersion: input.snapshotVersion ?? input.candidateVersion } }]) } };
}

const actor = { organizationId: "org-1", userId: "checker-1", role: "PAYROLL_FINALIZER" };
const transactionClient = (tx: Record<string, unknown>) => ({ $transaction: (callback: (value: unknown) => unknown) => callback(tx) });
function financialBoundaryTx(certifications: Record<string, "CERTIFIED" | "NOT_CERTIFIED"> = { "run-1": "NOT_CERTIFIED" }) {
  const runFor = (id: string) => ({ id, organizationId: "org-1", status: "FINALIZED", jurisdictionVersionId: `jurisdiction-${id}`, createdAt: new Date("2026-08-01T00:00:00Z"), correlationId: `correlation-${id}` });
  const runs = Object.fromEntries(Object.keys(certifications).map((id) => [id, runFor(id)]));
  const mutations = { payslipUpsert: vi.fn(), payslipUpdate: vi.fn(), payslipCreate: vi.fn(), paymentBatchCreate: vi.fn(), paymentInstructionCreate: vi.fn(), paymentBatchUpdateMany: vi.fn(), journalCreate: vi.fn(), journalLinesCreateMany: vi.fn(), liabilityCreate: vi.fn(), remittanceCreate: vi.fn(), remittanceLinesCreateMany: vi.fn(), amendmentCreate: vi.fn(), auditCreate: vi.fn() };
  const tx = {
    hrPayrollAuthoritativeRun: { findFirst: vi.fn(async ({ where }: { where: { id: string } }) => runs[where.id] ?? null) },
    hrPayrollJurisdictionVersion: { findFirst: vi.fn(async ({ where }: { where: { id: string } }) => { const runId = where.id.replace("jurisdiction-", ""); return { id: where.id, ruleManifest: { candidateVersion: NG_2026_8_VERSION, certification: certifications[runId] }, ruleHash: `rule-${runId}`, status: certifications[runId] === "CERTIFIED" ? "CERTIFIED" : "TESTING", certifiedAt: certifications[runId] === "CERTIFIED" ? new Date("2026-07-31T00:00:00Z") : null, effectiveFrom: new Date("2026-01-01T00:00:00Z"), effectiveTo: null }; }) },
    hrPayrollInputSnapshot: { findMany: vi.fn(async ({ where }: { where: { payrollRunId: string } }) => [{ sourceManifest: { jurisdictionVersion: NG_2026_8_VERSION }, payrollRunId: where.payrollRunId }]) },
    hrPayrollAuthoritativeResult: { findFirst: vi.fn().mockResolvedValue({ id: "result-1", employeeId: "employee-1", payrollRunId: "run-1", finalizedAt: new Date(), outputHash: "output" }), findMany: vi.fn().mockResolvedValue([]) },
    hrPayrollPayslipVersion: { findFirst: vi.fn(async ({ where }: { where: { status?: string } }) => ({ id: "payslip-1", employeeId: "employee-1", payrollResultId: "result-1", status: where.status ?? "GENERATED", version: 1, correlationId: "payslip-correlation" })), upsert: mutations.payslipUpsert, update: mutations.payslipUpdate, create: mutations.payslipCreate },
    hrPayrollPaymentBatch: { findFirst: vi.fn().mockResolvedValue({ id: "payment-batch-1", payrollRunId: "run-1", status: "VALIDATED", version: 1, createdById: "maker-1", instructionCount: 0, totalAmount: { toFixed: () => "0.0000" }, correlationId: "payment-correlation" }), create: mutations.paymentBatchCreate, updateMany: mutations.paymentBatchUpdateMany },
    hrPayrollPaymentInstruction: { create: mutations.paymentInstructionCreate, updateMany: vi.fn() },
    hrPayrollJournalBatch: { findFirst: vi.fn().mockResolvedValue(null), create: mutations.journalCreate },
    hrPayrollJournalLine: { createMany: mutations.journalLinesCreateMany },
    hrPayrollStatutoryLiability: { findMany: vi.fn().mockResolvedValue([{ id: "liability-1", payrollRunId: "run-1", amount: { plus: () => ({}) } }, { id: "liability-2", payrollRunId: "run-2", amount: { plus: () => ({}) } }]), create: mutations.liabilityCreate },
    hrPayrollRemittanceBatch: { findFirst: vi.fn(async ({ where }: { where: { status?: string } }) => ({ id: "remittance-1", status: where.status ?? "DRAFT", externalReference: null, correlationId: "remittance-correlation" })), create: mutations.remittanceCreate, updateMany: vi.fn() },
    hrPayrollRemittanceLine: { findMany: vi.fn().mockResolvedValue([{ liabilityId: "liability-1" }, { liabilityId: "liability-2" }]), createMany: mutations.remittanceLinesCreateMany },
    hrPayrollStatutoryAmendment: { findUnique: vi.fn(), findFirst: vi.fn(), create: mutations.amendmentCreate },
    hrAuditEvent: { create: mutations.auditCreate },
  };
  return { tx, client: transactionClient(tx) as never, mutations };
}

describe("NG-CANDIDATE-2026.8 certification boundary", () => {
  it("inherits 2026.7 arithmetic while identifying 2026.8 as NOT_CERTIFIED", () => { const raw = manifest(); const binding = deriveFrozenNg2026_8Binding(raw); const approved = { ...raw, expectedEmploymentIncomeBindingHash: binding.employmentIncomeBindingHash, expectedMinimumWageDecisionHash: binding.decision.decisionHash }; const result = calculateFrozenPayroll2026_8(approved, "snapshot"); expect([NG_2026_8_STATUS, binding.annualization.derivedExpectedAnnualSalary, binding.decision.classification, result.paye.currentPaye.toFixed(2), result.paye.candidateVersion]).toEqual(["NOT_CERTIFIED", "840000.00", "MINIMUM_WAGE_EXEMPT", "0.00", NG_2026_8_VERSION]); });
  it("preserves annual Salary mismatch rejection", () => { const value = manifest(); value.auditExpectedAnnualSalary = "1200000"; value.paye.expectedAnnualEmploymentIncome = "1200000"; expect(() => deriveFrozenNg2026_8Binding(value)).toThrow("ANNUAL_SALARY_BINDING_MISMATCH"); });
  it("rejects a technically certified jurisdiction whose candidate remains NOT_CERTIFIED", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "NOT_CERTIFIED", status: "CERTIFIED", certifiedAt: new Date() }) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); });
  it.each([{ candidateVersion: undefined, certification: "NOT_CERTIFIED" }, { candidateVersion: NG_2026_8_VERSION, certification: undefined }, { candidateVersion: NG_2026_8_VERSION, certification: "UNKNOWN" }])("fails closed for malformed candidate authority %#", async (value) => { await expect(assertOfficialPayrollCandidateCertified(certificationDb(value) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_MANIFEST_INVALID); });
  it("rejects jurisdiction/snapshot candidate mismatch", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "CERTIFIED", status: "CERTIFIED", certifiedAt: new Date(), snapshotVersion: "NG-CANDIDATE-2026.7" }) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_VERSION_MISMATCH); });
  it("accepts only a coherent future certified fixture", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "CERTIFIED", status: "CERTIFIED", certifiedAt: new Date("2026-07-31T00:00:00Z") }) as never, "org-1", "run-1")).resolves.toMatchObject({ candidateVersion: NG_2026_8_VERSION, certificationStatus: "CERTIFIED", ruleHash: "rule-hash" }); });
  it("rejects finalization before official-state mutation", async () => { const db = certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "NOT_CERTIFIED" }) as Record<string, unknown>; (db.hrPayrollAuthoritativeRun as { findFirst: ReturnType<typeof vi.fn> }).findFirst.mockResolvedValue({ id: "run-1", status: "APPROVED", jurisdictionVersionId: "jurisdiction-1", createdAt: new Date("2026-08-01T00:00:00Z") }); const tx = { ...db, hrPayrollAuthoritativeResult: { updateMany: vi.fn() }, hrPayrollYtdLedgerEntry: { upsert: vi.fn() }, hrAuditEvent: { create: vi.fn() } }; const client = { $transaction: (callback: (value: unknown) => unknown) => callback(tx) }; await expect(finalizeUnit9Run(client as never, { organizationId: "org-1", userId: "user-1", role: "PAYROLL_FINALIZER" }, "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); expect(tx.hrPayrollAuthoritativeResult.updateMany).not.toHaveBeenCalled(); expect(tx.hrPayrollYtdLedgerEntry.upsert).not.toHaveBeenCalled(); expect(tx.hrAuditEvent.create).not.toHaveBeenCalled(); });
  it("uses the shared guard at all official downstream boundaries and preserves reject/return neutralization", () => { const source = fs.readFileSync(path.join(process.cwd(), "src/lib/hr/payroll/unit9-financial-service.ts"), "utf8"); for (const name of ["generateUnit9Payslips", "publishUnit9Payslip", "createCorrectedUnit9Payslip", "createUnit9PaymentBatch", "transitionUnit9PaymentBatch", "generateUnit9FinancialOutputs", "createUnit9RemittanceBatch"]) expect(source.slice(source.indexOf(`export async function ${name}`))).toContain("assertOfficialPayrollCandidateCertified"); for (const name of ["acknowledgeUnit9RemittanceSimulation", "createUnit9RemittanceAmendmentSimulation"]) expect(source.slice(source.indexOf(`export async function ${name}`))).toContain("assertRemittanceCandidateCertified"); expect(source).toContain("!['REJECTED', 'RETURNED'].includes(input.to)"); });
  it("returns an existing certified payment batch without querying remittance lineage or creating instructions", async () => { const { tx, client, mutations } = financialBoundaryTx({ "run-1": "CERTIFIED" }); const result = await createUnit9PaymentBatch(client, actor, "run-1"); expect(result).toMatchObject({ idempotent: true, batch: { id: "payment-batch-1" } }); expect(tx.hrPayrollRemittanceLine.findMany).not.toHaveBeenCalled(); expect(tx.hrPayrollStatutoryLiability.findMany).not.toHaveBeenCalled(); expect(mutations.paymentBatchCreate).not.toHaveBeenCalled(); expect(mutations.paymentInstructionCreate).not.toHaveBeenCalled(); });
  it("guards existing remittance batches across every source run", async () => { const certified = financialBoundaryTx({ "run-1": "CERTIFIED", "run-2": "CERTIFIED" }); await expect(createUnit9RemittanceBatch(certified.client, actor, { jurisdictionVersionId: "jurisdiction-run-1", periodKey: "2026-08", category: "PAYE" })).resolves.toMatchObject({ idempotent: true, batch: { id: "remittance-1" } }); const blocked = financialBoundaryTx({ "run-1": "CERTIFIED", "run-2": "NOT_CERTIFIED" }); await expect(createUnit9RemittanceBatch(blocked.client, actor, { jurisdictionVersionId: "jurisdiction-run-1", periodKey: "2026-08", category: "PAYE" })).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); expect(blocked.mutations.remittanceCreate).not.toHaveBeenCalled(); });
  it.each([
    ["payslip generation", (client: never) => generateUnit9Payslips(client, actor, "run-1")],
    ["payslip publication", (client: never) => publishUnit9Payslip(client, actor, "payslip-1")],
    ["corrected payslip", (client: never) => createCorrectedUnit9Payslip(client, actor, { correctedResultId: "result-1", supersedesPayslipId: "payslip-1" })],
    ["payment batch", (client: never) => createUnit9PaymentBatch(client, actor, "run-1")],
    ["outgoing payment transition", (client: never) => transitionUnit9PaymentBatch(client, actor, "payment-batch-1", { to: "APPROVED", reason: "test" })],
    ["financial outputs", (client: never) => generateUnit9FinancialOutputs(client, actor, "run-1", { periodKey: "2026-08" })],
    ["remittance creation", (client: never) => createUnit9RemittanceBatch(client, actor, { jurisdictionVersionId: "jurisdiction-run-1", periodKey: "2026-08", category: "PAYE" })],
    ["remittance acknowledgement", (client: never) => acknowledgeUnit9RemittanceSimulation(client, actor, "remittance-1", "test")],
    ["remittance amendment", (client: never) => createUnit9RemittanceAmendmentSimulation(client, actor, "remittance-1", { idempotencyKey: "amendment-1", reason: "test", deltaManifest: {} })],
  ])("blocks NOT_CERTIFIED %s before official mutation", async (_name, invoke) => { const { client, mutations } = financialBoundaryTx({ "run-1": "NOT_CERTIFIED", "run-2": "NOT_CERTIFIED" }); await expect(invoke(client)).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); for (const mutation of Object.values(mutations)) expect(mutation).not.toHaveBeenCalled(); });
});
