import { describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { calculateFrozenPayroll2026_8, deriveFrozenNg2026_8Binding, type Candidate2026_8Manifest } from "../src/lib/hr/payroll/unit9-engine-2026-8";
import { NG_2026_8_STATUS, NG_2026_8_VERSION } from "../src/lib/hr/payroll/nigeria-2026-8";
import { assertOfficialPayrollCandidateCertified, PAYROLL_CANDIDATE_MANIFEST_INVALID, PAYROLL_CANDIDATE_NOT_CERTIFIED, PAYROLL_CANDIDATE_VERSION_MISMATCH } from "../src/lib/hr/payroll/unit9-candidate-certification";
import { finalizeUnit9Run } from "../src/lib/hr/payroll/unit9-service";

const manifest = (): Candidate2026_8Manifest => ({ employeeId: "employee-1", workRelationshipId: "relationship-1", assignmentId: "assignment-1", payrollPeriodId: "period-1", currency: "NGN", jurisdictionVersion: NG_2026_8_VERSION, engineVersion: "unit9-ng-2026.8", incomeEvidence: { employeeId: "employee-1", workRelationshipId: "relationship-1", assignmentId: "assignment-1", payrollPeriodId: "period-1", rta: "LAGOS", candidateVersion: NG_2026_8_VERSION, actualFrozenSalary: "70000", currentBonus: "0", otherTaxableEmploymentIncome: "VERIFIED_NONE", materiallyVariableMonthlyWage: "NO", ambiguousMultiEmployer: "NO", unusualPartialYearArrangement: "NO", evidenceCompletenessCertified: true, evidenceReferences: ["salary-record-1", "ledger-hash-1"], inputCertificationId: "cert-1", inputCertificationVersion: "v1" }, authoritativeSources: { salary: { recordId: "salary-record-1", versionHash: "salary-v1-hash", monthlyAmount: "70000", currency: "NGN", payFrequency: "MONTHLY", effectiveFrom: "2026-01-01T00:00:00.000Z" }, annualization: { ruleId: "annualization-1", ruleVersion: 1, frequency: "MONTHLY", periodsInTaxYear: 12, method: "GOVERNED_PERIODIC_SALARY_X_PERIODS_IN_TAX_YEAR", taxYear: 2026, certificationStatus: "CERTIFIED" }, ytd: { sourceLedgerHash: "ledger-hash-1", cutoff: "2026-08-01T00:00:00.000Z", priorBonusYtd: "0", payeDeducted: "0", payeRepaid: "0", entryIds: [] }, priorEmployer: { state: "NONE", income: "0", paye: "0", payeRepaid: "0" }, deductions: { amount: "0", sourceType: "TAX_RELIEF_CLAIM_VERSIONS", sourceRecordIds: [], sourceVersions: [], evidenceReferences: [], aggregateHash: "empty-relief-set" } }, auditExpectedAnnualSalary: "840000", auditPriorBonusYtd: "0", auditPayeDeductedYtd: "0", auditPayeRepaidYtd: "0", earnings: [{ code: "SALARY", sourceType: "UNIT8", sourceId: "salary-record-1", fixedAmount: "70000", taxableBaseCode: "EMPLOYMENT", ruleVersionReference: "salary-v1" }], paye: { priorYtdTaxableIncome: "0", priorYtdPaye: "0", priorPayeRepaid: "0", expectedAnnualEmploymentIncome: "840000", eligibleAnnualDeductions: "0", periodsElapsed: 8, periodsInTaxYear: 12, currentNonPeriodicPayments: "0", priorBonusPaidTaxYearToDate: "0", priorEmployerIncome: "0", priorEmployerPaye: "0", rules: { version: "not-authority", annualizationPeriods: 12, roundingScale: 2, bands: [] } } });

function certificationDb(input: { candidateVersion?: string; certification?: string; status?: string; certifiedAt?: Date | null; snapshotVersion?: string }) {
  return { hrPayrollAuthoritativeRun: { findFirst: vi.fn().mockResolvedValue({ id: "run-1", jurisdictionVersionId: "jurisdiction-1", createdAt: new Date("2026-08-01T00:00:00Z") }) }, hrPayrollJurisdictionVersion: { findFirst: vi.fn().mockResolvedValue({ id: "jurisdiction-1", ruleManifest: { ...(input.candidateVersion === undefined ? {} : { candidateVersion: input.candidateVersion }), ...(input.certification === undefined ? {} : { certification: input.certification }) }, ruleHash: "rule-hash", status: input.status ?? "TESTING", certifiedAt: input.certifiedAt ?? null, effectiveFrom: new Date("2026-01-01T00:00:00Z"), effectiveTo: null }) }, hrPayrollInputSnapshot: { findMany: vi.fn().mockResolvedValue([{ sourceManifest: { jurisdictionVersion: input.snapshotVersion ?? input.candidateVersion } }]) } };
}

describe("NG-CANDIDATE-2026.8 certification boundary", () => {
  it("inherits 2026.7 arithmetic while identifying 2026.8 as NOT_CERTIFIED", () => { const raw = manifest(); const binding = deriveFrozenNg2026_8Binding(raw); const approved = { ...raw, expectedEmploymentIncomeBindingHash: binding.employmentIncomeBindingHash, expectedMinimumWageDecisionHash: binding.decision.decisionHash }; const result = calculateFrozenPayroll2026_8(approved, "snapshot"); expect([NG_2026_8_STATUS, binding.annualization.derivedExpectedAnnualSalary, binding.decision.classification, result.paye.currentPaye.toFixed(2), result.paye.candidateVersion]).toEqual(["NOT_CERTIFIED", "840000.00", "MINIMUM_WAGE_EXEMPT", "0.00", NG_2026_8_VERSION]); });
  it("preserves annual Salary mismatch rejection", () => { const value = manifest(); value.auditExpectedAnnualSalary = "1200000"; value.paye.expectedAnnualEmploymentIncome = "1200000"; expect(() => deriveFrozenNg2026_8Binding(value)).toThrow("ANNUAL_SALARY_BINDING_MISMATCH"); });
  it("rejects a technically certified jurisdiction whose candidate remains NOT_CERTIFIED", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "NOT_CERTIFIED", status: "CERTIFIED", certifiedAt: new Date() }) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); });
  it.each([{ candidateVersion: undefined, certification: "NOT_CERTIFIED" }, { candidateVersion: NG_2026_8_VERSION, certification: undefined }, { candidateVersion: NG_2026_8_VERSION, certification: "UNKNOWN" }])("fails closed for malformed candidate authority %#", async (value) => { await expect(assertOfficialPayrollCandidateCertified(certificationDb(value) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_MANIFEST_INVALID); });
  it("rejects jurisdiction/snapshot candidate mismatch", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "CERTIFIED", status: "CERTIFIED", certifiedAt: new Date(), snapshotVersion: "NG-CANDIDATE-2026.7" }) as never, "org-1", "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_VERSION_MISMATCH); });
  it("accepts only a coherent future certified fixture", async () => { await expect(assertOfficialPayrollCandidateCertified(certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "CERTIFIED", status: "CERTIFIED", certifiedAt: new Date("2026-07-31T00:00:00Z") }) as never, "org-1", "run-1")).resolves.toMatchObject({ candidateVersion: NG_2026_8_VERSION, certificationStatus: "CERTIFIED", ruleHash: "rule-hash" }); });
  it("rejects finalization before official-state mutation", async () => { const db = certificationDb({ candidateVersion: NG_2026_8_VERSION, certification: "NOT_CERTIFIED" }) as Record<string, unknown>; (db.hrPayrollAuthoritativeRun as { findFirst: ReturnType<typeof vi.fn> }).findFirst.mockResolvedValue({ id: "run-1", status: "APPROVED", jurisdictionVersionId: "jurisdiction-1", createdAt: new Date("2026-08-01T00:00:00Z") }); const tx = { ...db, hrPayrollAuthoritativeResult: { updateMany: vi.fn() }, hrPayrollYtdLedgerEntry: { upsert: vi.fn() }, hrAuditEvent: { create: vi.fn() } }; const client = { $transaction: (callback: (value: unknown) => unknown) => callback(tx) }; await expect(finalizeUnit9Run(client as never, { organizationId: "org-1", userId: "user-1", role: "PAYROLL_FINALIZER" }, "run-1")).rejects.toThrow(PAYROLL_CANDIDATE_NOT_CERTIFIED); expect(tx.hrPayrollAuthoritativeResult.updateMany).not.toHaveBeenCalled(); expect(tx.hrPayrollYtdLedgerEntry.upsert).not.toHaveBeenCalled(); expect(tx.hrAuditEvent.create).not.toHaveBeenCalled(); });
  it("uses the shared guard at all official downstream boundaries and preserves reject/return neutralization", () => { const source = fs.readFileSync(path.join(process.cwd(), "src/lib/hr/payroll/unit9-financial-service.ts"), "utf8"); for (const name of ["generateUnit9Payslips", "publishUnit9Payslip", "createCorrectedUnit9Payslip", "createUnit9PaymentBatch", "transitionUnit9PaymentBatch", "generateUnit9FinancialOutputs", "createUnit9RemittanceBatch"]) expect(source.slice(source.indexOf(`export async function ${name}`))).toContain("assertOfficialPayrollCandidateCertified"); for (const name of ["acknowledgeUnit9RemittanceSimulation", "createUnit9RemittanceAmendmentSimulation"]) expect(source.slice(source.indexOf(`export async function ${name}`))).toContain("assertRemittanceCandidateCertified"); expect(source).toContain("!['REJECTED', 'RETURNED'].includes(input.to)"); });
});
