import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { captureTimeEventAction, createTimesheetAction, requestTimeCorrectionAction, submitTimesheetAction } from "./actions";

export default async function EmployeeTimePage() {
  const auth = await requirePermission("time.read_self");
  if (!auth.user.employee) throw new Error("An employee profile is required.");
  const [sessions, days, timesheets] = await Promise.all([
    prisma.hrClockSession.findMany({ where: { organizationId: auth.user.organizationId, employeeId: auth.user.employee.id }, orderBy: { startedAt: "desc" }, take: 30 }),
    prisma.hrAttendanceDay.findMany({ where: { organizationId: auth.user.organizationId, employeeId: auth.user.employee.id }, include: { interpretations: { orderBy: { version: "desc" }, take: 1 } }, orderBy: { businessDate: "desc" }, take: 30 }),
    prisma.hrTimesheet.findMany({ where: { organizationId: auth.user.organizationId, employeeId: auth.user.employee.id }, orderBy: { periodStart: "desc" }, take: 20 }),
  ]);
  const open = sessions.find(({ status }) => status === "CLOCKED_IN" || status === "ON_BREAK");
  return <><h1 className="text-3xl font-bold">My time</h1><p className="mt-2 text-slate-600">Governed clock events, attendance outcomes, and weekly timesheets.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Clock</h2><p className="mt-2 text-sm">Current state: <strong>{open?.status ?? "NOT_STARTED"}</strong></p><form action={captureTimeEventAction} className="mt-4 flex flex-wrap gap-2">{!open ? <button className="btn btn-primary" name="eventType" value="CLOCK_IN">Clock in</button> : open.status === "CLOCKED_IN" ? <><button className="btn btn-secondary" name="eventType" value="BREAK_START">Start break</button><button className="btn btn-primary" name="eventType" value="CLOCK_OUT">Clock out</button></> : <button className="btn btn-primary" name="eventType" value="BREAK_END">End break</button>}</form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Attendance history</h2><div className="mt-3 space-y-3">{days.map((day) => <article className="rounded-xl border p-3" key={day.id}><p className="text-sm">{day.businessDate.toLocaleDateString()} · {day.currentOutcome} · v{day.currentVersion}</p>{!["PRESENT", "APPROVED_LEAVE", "HOLIDAY", "NON_WORKING_DAY"].includes(day.currentOutcome) ? <form action={requestTimeCorrectionAction} className="mt-3 grid gap-2 md:grid-cols-4"><input type="hidden" name="attendanceDayId" value={day.id}/><input className="input" type="datetime-local" name="requestedClockIn"/><input className="input" type="datetime-local" name="requestedClockOut"/><input className="input" name="reason" placeholder="Correction reason" required/><button className="btn btn-secondary">Request correction</button></form> : null}</article>)}{!days.length ? <p className="text-sm text-slate-500">No interpreted attendance yet.</p> : null}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Timesheets</h2><form action={createTimesheetAction} className="mt-3 grid gap-3 md:grid-cols-5"><input className="input" type="date" name="periodStart" required/><input className="input" type="date" name="periodEnd" required/><input className="input" type="number" min="0" max="10080" name="totalMinutes" placeholder="Total minutes" required/><input className="input" name="comment" placeholder="Work summary"/><button className="btn btn-primary">Create draft</button></form><div className="mt-5 space-y-3">{timesheets.map((sheet) => <form action={submitTimesheetAction} className="flex flex-wrap items-center gap-3 rounded-xl border p-3" key={sheet.id}><input type="hidden" name="timesheetId" value={sheet.id}/><input type="hidden" name="expectedVersion" value={sheet.version}/><p className="mr-auto text-sm">{sheet.periodStart.toLocaleDateString()}–{sheet.periodEnd.toLocaleDateString()} · {sheet.status} · v{sheet.version}</p>{["DRAFT", "RETURNED"].includes(sheet.status) ? <button className="btn btn-secondary">Submit</button> : null}</form>)}</div></section>
  </>;
}
