import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { archiveEmployeeDocumentAction, recordDocumentScanAction, sendDocumentExpiryRemindersAction, updateEmployeeDocumentMetadataAction, uploadEmployeeDocumentAction, uploadEmployeeDocumentVersionAction } from "./actions";

const categories = ["EMPLOYMENT_AGREEMENT", "OFFER_LETTER", "IDENTITY_DOCUMENT", "TAX_DOCUMENT", "BANK_DOCUMENT", "QUALIFICATION_CERTIFICATE", "POLICY_ACKNOWLEDGEMENT", "LEAVE_SUPPORT", "PERFORMANCE", "DISCIPLINARY", "EXIT_DOCUMENT", "OTHER"];

export default async function DocumentsAdminPage() {
  const auth = await requireAnyPermission(["document.read_employee", "document.read_sensitive", "document.update"]);
  const organizationId = auth.user.organizationId;
  const [employees, documents, accessLogs] = await Promise.all([
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { not: "ARCHIVED" } }, orderBy: { employeeNumber: "asc" } }),
    prisma.hrEmployeeDocument.findMany({ where: { organizationId }, include: { employee: true, versions: { orderBy: { version: "desc" } } }, orderBy: { createdAt: "desc" }, take: 250 }),
    prisma.hrDocumentAccessLog.findMany({ where: { organizationId }, include: { actor: true, documentVersion: { include: { document: { include: { employee: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const visible = documents.filter((document) => !document.restricted || auth.permissions.has("document.read_sensitive"));
  const visibleAccessLogs = accessLogs.filter((log) => !log.documentVersion.document.restricted || auth.permissions.has("document.read_sensitive"));
  return <>
    <h1 className="text-3xl font-bold">Employee documents</h1><p className="mt-2 text-slate-600">Private, versioned, checksum-verified records with malware quarantine, expiration, retention, and access history.</p>
    <details className="mt-6 rounded-2xl bg-white p-5"><summary className="cursor-pointer font-bold">Retention and metadata controls</summary><div className="mt-4 grid gap-4 lg:grid-cols-2">{visible.filter(({ archivedAt }) => !archivedAt).map((document) => <form action={updateEmployeeDocumentMetadataAction} className="grid gap-2 rounded-xl border border-slate-200 p-4" key={document.id}><input type="hidden" name="id" value={document.id} /><p className="text-sm font-semibold">{document.employee.employeeNumber} · {document.title}</p><input className="input" name="title" defaultValue={document.title} required /><input className="input" name="expiresAt" type="date" defaultValue={document.expiresAt?.toISOString().slice(0, 10)} /><select className="input" name="retentionStatus" defaultValue={document.retentionStatus}>{["ACTIVE", "HOLD", "EXPIRED", "PENDING_DELETION"].map((status) => <option key={status}>{status}</option>)}</select><label className="flex gap-2 text-sm"><input name="restricted" type="checkbox" defaultChecked={document.restricted} />Restricted</label><input className="input" name="reason" placeholder="Required change reason" required /><button className="text-left font-semibold text-teal-700">Update metadata</button></form>)}</div></details>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Upload document</h2><form action={uploadEmployeeDocumentAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="category">{categories.map((category) => <option key={category}>{category}</option>)}</select><input className="input" name="title" placeholder="Document title" required /><input className="input" name="expiresAt" type="date" /><label className="flex gap-2 text-sm"><input name="restricted" type="checkbox" />Restricted HR document</label><label className="text-sm font-semibold">PDF, JPEG, or PNG<input className="input mt-1" name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" required /></label><button className="btn btn-primary">Upload to quarantine</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Expiration reminders</h2><p className="mt-2 text-sm text-slate-600">Queues reference-only reminders for active documents expiring in the next 30 days. Safe to retry for the same date.</p><form action={sendDocumentExpiryRemindersAction} className="mt-4 flex gap-3"><input className="input" name="asOf" type="date" required /><button className="btn btn-secondary">Queue reminders</button></form></section>
    </div>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Document register</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Document</th><th>Expiration</th><th>Versions</th><th>Latest scan</th><th>Actions</th></tr></thead><tbody>{visible.map((document) => { const latest = document.versions[0]; return <tr className="border-b last:border-0 align-top" key={document.id}><td className="py-3">{document.employee.employeeNumber} — {document.employee.legalFirstName} {document.employee.lastName}</td><td>{document.title}<br /><span className="text-xs text-slate-500">{document.category} · {document.restricted ? "Restricted" : "Standard"} · {document.archivedAt ? "Archived" : document.retentionStatus}</span></td><td>{document.expiresAt?.toLocaleDateString() ?? "—"}</td><td><div className="space-y-1">{document.versions.map((version) => <div key={version.id}>{version.scanStatus === "CLEAN" ? <Link className="font-semibold text-teal-700" href={`/api/hr/documents/versions/${version.id}`}>v{version.version} · {version.displayFileName}</Link> : `v${version.version} · ${version.displayFileName}`}</div>)}</div>{!document.archivedAt && <form action={uploadEmployeeDocumentVersionAction} className="mt-2 flex gap-2"><input type="hidden" name="documentId" value={document.id} /><input className="input max-w-52" name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required /><button className="font-semibold text-teal-700">New version</button></form>}</td><td>{latest?.scanStatus ?? "—"}{latest?.scanStatus === "PENDING" && auth.permissions.has("document.update") && <form action={recordDocumentScanAction} className="mt-2 grid gap-2"><input type="hidden" name="versionId" value={latest.id} /><select className="input" name="status"><option>CLEAN</option><option>QUARANTINED</option><option>FAILED</option></select><input className="input" name="provider" placeholder="Scanner/provider" required /><input className="input" name="reference" placeholder="Scan reference" /><input className="input" name="reason" placeholder="Result reason" required /><button className="text-left font-semibold text-teal-700">Record scan result</button></form>}</td><td>{!document.archivedAt && auth.permissions.has("document.archive") ? <form action={archiveEmployeeDocumentAction} className="grid gap-2"><input type="hidden" name="id" value={document.id} /><input className="input max-w-48" name="reason" placeholder="Archive reason" required /><button className="text-left font-semibold text-red-700">Archive metadata</button></form> : "—"}</td></tr>; })}</tbody></table></section>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Recent access log</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Time</th><th>Actor</th><th>Employee</th><th>Document</th><th>Action</th></tr></thead><tbody>{visibleAccessLogs.map((log) => <tr className="border-b last:border-0" key={log.id}><td className="py-3">{log.createdAt.toLocaleString()}</td><td>{log.actor.email}</td><td>{log.documentVersion.document.employee.employeeNumber}</td><td>{log.documentVersion.document.title} v{log.documentVersion.version}</td><td>{log.action}</td></tr>)}</tbody></table></section>
  </>;
}
