import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { completeLifecycleTaskAction } from "@/app/hr/admin/lifecycle/actions";

export default async function EmployeeLifecycleTasksPage() {
  const auth = await requirePermission("workflow.task.complete");
  const tasks = await prisma.hrLifecycleTask.findMany({ where: { organizationId: auth.user.organizationId, assignedUserId: auth.user.id, instance: { status: "ACTIVE" } }, include: { instance: { include: { template: true } } }, orderBy: [{ status: "asc" }, { dueAt: "asc" }] });
  return <main><h1 className="text-3xl font-bold">My lifecycle tasks</h1><p className="mt-2 text-slate-600">Your assigned onboarding and offboarding responsibilities.</p><div className="mt-6 grid gap-4">{tasks.length === 0 ? <div className="rounded-2xl bg-white p-6 text-slate-600">No active tasks are assigned to you.</div> : tasks.map((task) => <article className="rounded-2xl bg-white p-5" key={task.id}><div className="flex justify-between gap-4"><div><h2 className="font-bold">{task.title}</h2><p className="text-sm text-slate-600">{task.instance.type} · due {task.dueAt.toLocaleDateString()}</p></div><span className="text-xs font-semibold">{task.status}</span></div>{task.instructions && <p className="mt-3 text-sm">{task.instructions}</p>}{["PENDING", "IN_PROGRESS"].includes(task.status) && <form action={completeLifecycleTaskAction} className="mt-4 grid gap-3"><input type="hidden" name="taskId" value={task.id} /><textarea className="input" name="completionNotes" placeholder="What was completed?" required /><input className="input" name="evidenceReference" placeholder="Evidence/reference (optional; do not enter secrets)" /><button className="btn btn-primary">Mark complete</button></form>}{task.status === "BLOCKED" && <p className="mt-3 text-sm text-amber-700">Waiting for prerequisite tasks: {task.predecessorKeys.join(", ")}</p>}{task.completionNotes && <p className="mt-3 text-sm">Completed: {task.completionNotes}</p>}</article>)}</div></main>;
}
