import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { archiveLeavePolicyAction, archiveLeaveTypeAction, endEmployeeLeavePolicyAction } from "./actions";

export default async function LeavePoliciesPage() {
  const auth = await requirePermission("leave.policy.manage");
  const [types, policies, assignments] = await Promise.all([
    prisma.hrLeaveType.findMany({ where: { organizationId: auth.user.organizationId }, orderBy: { name: "asc" } }),
    prisma.hrLeavePolicy.findMany({ where: { organizationId: auth.user.organizationId }, include: { leaveType: true }, orderBy: [{ leaveType: { name: "asc" } }, { version: "desc" }] }),
    prisma.hrEmployeeLeavePolicy.findMany({ where: { employee: { organizationId: auth.user.organizationId } }, include: { employee: true, leavePolicy: { include: { leaveType: true } } }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
  ]);
  return <><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Leave policy history</h1><p className="mt-2 text-slate-600">Retirement is guarded so active employee coverage cannot be silently removed.</p></div><Link className="btn btn-secondary" href="/hr/admin/leave">Back to leave</Link></div><div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Leave types</h2><ul className="mt-4 space-y-4">{types.map((type) => <li className="border-b pb-4 last:border-0" key={type.id}><p className="font-semibold">{type.name} · {type.code} · {type.status}</p><p className="text-sm text-slate-600">{type.unit} · {type.paid ? "Paid" : "Unpaid"} · {type.requiresAttachment ? "Evidence required" : "No mandatory evidence"}</p>{type.status === "ACTIVE" ? <form action={archiveLeaveTypeAction} className="mt-2 flex gap-2"><input type="hidden" name="id" value={type.id} /><input className="input" name="reason" placeholder="Archive reason" required /><button className="font-semibold text-red-700">Archive</button></form> : null}</li>)}</ul></section><section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Policy versions</h2><ul className="mt-4 space-y-4">{policies.map((policy) => <li className="border-b pb-4 last:border-0" key={policy.id}><p className="font-semibold">{policy.leaveType.name} · {policy.name} v{policy.version} · {policy.status}</p><p className="text-sm text-slate-600">{policy.entitlement.toString()} units · {policy.accrualFrequency} · effective {policy.effectiveFrom.toLocaleDateString()} – {policy.effectiveTo?.toLocaleDateString() ?? "Current"}</p>{policy.status === "ACTIVE" ? <form action={archiveLeavePolicyAction} className="mt-2 flex gap-2"><input type="hidden" name="id" value={policy.id} /><input className="input" name="reason" placeholder="Archive reason" required /><button className="font-semibold text-red-700">Archive</button></form> : null}</li>)}</ul></section></div><section className="mt-5 rounded-2xl bg-white p-5"><h2 className="font-bold">Employee assignment history</h2><div className="mt-4 space-y-3">{assignments.map((assignment) => <div className="grid gap-2 border-b pb-3 md:grid-cols-[1fr_1fr_1fr_auto]" key={assignment.id}><span>{assignment.employee.legalFirstName} {assignment.employee.lastName}</span><span>{assignment.leavePolicy.leaveType.name} v{assignment.leavePolicy.version}</span><span>{assignment.effectiveFrom.toLocaleDateString()} – {assignment.effectiveTo?.toLocaleDateString() ?? "Current"} · {assignment.status}</span>{assignment.status === "ACTIVE" ? <form action={endEmployeeLeavePolicyAction} className="flex gap-2"><input type="hidden" name="id" value={assignment.id} /><input className="input" name="effectiveTo" type="date" required /><input className="input" name="reason" placeholder="End reason" required /><button className="font-semibold text-red-700">End</button></form> : null}</div>)}</div></section></>;
}
