import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { archivePositionAction, createPositionAction, updatePositionAction } from "./actions";

export default async function PositionsPage() {
  const auth = await requirePermission("position.manage");
  const [positions, departments, teams] = await Promise.all([
    prisma.hrPosition.findMany({ where: { organizationId: auth.user.organizationId }, include: { department: true, team: true, _count: { select: { employeeAssignments: true } } }, orderBy: [{ status: "asc" }, { title: "asc" }] }),
    prisma.hrDepartment.findMany({ where: { organizationId: auth.user.organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.hrTeam.findMany({ where: { organizationId: auth.user.organizationId, status: "ACTIVE" }, include: { department: true }, orderBy: { name: "asc" } }),
  ]);
  return <><h1 className="text-3xl font-bold">Positions</h1><p className="mt-2 text-slate-600">Define approved positions and salary bands. Salary bands do not expose employee pay.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create position</h2><form action={createPositionAction} className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" name="code" placeholder="Code" required /><input className="input" name="title" placeholder="Title" required /><select className="input" name="departmentId" required><option value="">Department</option>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><select className="input" name="teamId"><option value="">No team</option>{teams.map((team) => <option value={team.id} key={team.id}>{team.department.name} — {team.name}</option>)}</select><input className="input" name="currency" defaultValue="NGN" maxLength={3} required /><input className="input" name="salaryBandMinimum" type="number" min="0" step="0.01" placeholder="Band minimum" /><input className="input" name="salaryBandMaximum" type="number" min="0" step="0.01" placeholder="Band maximum" /><input className="input" name="description" placeholder="Description" /><button className="btn btn-primary">Create</button></form></section>
    <div className="mt-6 space-y-4">{positions.map((position) => <article className="rounded-2xl bg-white p-5" key={position.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-mono text-sm">{position.code}</p><h2 className="text-xl font-bold">{position.title}</h2><p className="text-sm text-slate-600">{position.department.name}{position.team ? ` · ${position.team.name}` : ""} · {position._count.employeeAssignments} assignment records</p><p className="mt-2 text-sm"><strong>Salary band:</strong> {position.salaryBandMinimum !== null || position.salaryBandMaximum !== null ? `${position.currency} ${position.salaryBandMinimum?.toString() ?? "—"} – ${position.salaryBandMaximum?.toString() ?? "—"}` : "Not set"}</p></div><span>{position.status}</span></div>{position.status === "ACTIVE" ? <div className="mt-5 grid gap-4 lg:grid-cols-2"><form action={updatePositionAction} className="grid gap-2"><input type="hidden" name="id" value={position.id} /><input type="hidden" name="code" value={position.code} /><input className="input" name="title" defaultValue={position.title} required /><select className="input" name="departmentId" defaultValue={position.departmentId}>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><select className="input" name="teamId" defaultValue={position.teamId ?? ""}><option value="">No team</option>{teams.map((team) => <option value={team.id} key={team.id}>{team.department.name} — {team.name}</option>)}</select><input className="input" name="description" defaultValue={position.description ?? ""} placeholder="Description" /><input className="input" name="currency" defaultValue={position.currency} maxLength={3} required /><input className="input" name="salaryBandMinimum" type="number" min="0" step="0.01" defaultValue={position.salaryBandMinimum?.toString() ?? ""} /><input className="input" name="salaryBandMaximum" type="number" min="0" step="0.01" defaultValue={position.salaryBandMaximum?.toString() ?? ""} /><input className="input" name="reason" placeholder="Reason for update" required /><button className="btn btn-secondary">Update position</button></form><form action={archivePositionAction} className="grid content-start gap-2"><input type="hidden" name="id" value={position.id} /><input className="input" name="reason" placeholder="Archive reason" required /><button className="btn btn-secondary text-red-700">Archive position</button></form></div> : <p className="mt-4 text-sm text-slate-500">History retained.</p>}</article>)}{!positions.length ? <p className="rounded-2xl bg-white p-6 text-slate-500">No positions yet.</p> : null}</div></>;
}
