import { BriefcaseBusiness, CircleCheck, Clock3, DoorOpen } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { createPositionAction, openPositionAction, submitPositionAction } from "./actions";
import { PositionDecisionForm } from "./PositionDecisionForm";

export default async function PositionsPage() {
  const auth = await requirePermission("position.manage");
  const organizationId = auth.user.organizationId;
  const [positions, departments, teams] = await Promise.all([
    prisma.hrPosition.findMany({ where: { organizationId }, include: { department: true, team: true, _count: { select: { employeeAssignments: true } } }, orderBy: [{ lifecycleStatus: "asc" }, { title: "asc" }] }),
    prisma.hrDepartment.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.hrTeam.findMany({ where: { organizationId, status: "ACTIVE" }, include: { department: true }, orderBy: { name: "asc" } }),
  ]);
  const count = (status: string) => positions.filter((position) => position.lifecycleStatus === status).length;
  const stats = [{ label: "Total positions", value: positions.length, icon: BriefcaseBusiness }, { label: "Open", value: count("OPEN"), icon: DoorOpen }, { label: "Approved", value: count("APPROVED"), icon: CircleCheck }, { label: "Pending approval", value: count("PENDING_APPROVAL"), icon: Clock3 }];
  return <main><div className="hr-page-heading"><div><h1 className="hr-page-title">Positions</h1><p className="hr-page-subtitle">Approval-controlled organizational seats with governed capacity.</p></div><a className="btn btn-primary" href="#create-position">Create draft position</a></div>
    <div className="hr-grid-4">{stats.map(({ label, value, icon: Icon }) => <article className="hr-card hr-stat" key={label}><span className="hr-icon"><Icon /></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</div>
    <section className="hr-card hr-form-panel hr-wide-form" id="create-position"><div className="hr-panel-heading"><span className="hr-icon"><BriefcaseBusiness /></span><div><h2>Create draft position</h2><p>Define a governed seat before submitting it for approval.</p></div></div><form action={createPositionAction} className="hr-position-form">
      <label>Code<input className="input" name="code" placeholder="Position code" required /></label><label>Title<input className="input" name="title" placeholder="Position title" required /></label><label>Department<select className="input" name="departmentId" required><option value="">Select department</option>{departments.map(item => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Team<select className="input" name="teamId"><option value="">No team</option>{teams.map(item => <option value={item.id} key={item.id}>{item.department.name} — {item.name}</option>)}</select></label><label>Currency<input className="input" name="currency" defaultValue="NGN" maxLength={3} required /></label><label>Band minimum<input className="input" name="salaryBandMinimum" type="number" min="0" step="0.01" placeholder="0.00" /></label><label>Band maximum<input className="input" name="salaryBandMaximum" type="number" min="0" step="0.01" placeholder="0.00" /></label><label>Description<input className="input" name="description" placeholder="Position description" /></label><button className="btn btn-primary">Create draft</button>
    </form></section>
    <section className="hr-card hr-register"><div className="hr-register-heading"><div><h2>Positions register</h2><p>Capacity, assignment history, lifecycle state, and approval actions.</p></div><span>{positions.length} records</span></div><div className="hr-table-wrap"><table><thead><tr><th>Code</th><th>Title</th><th>Department</th><th>Team</th><th>Band</th><th>Capacity</th><th>Assignments</th><th>Status</th><th>Actions</th></tr></thead><tbody>{positions.map(position => <tr key={position.id}><td><code>{position.code}</code></td><td><strong>{position.title}</strong></td><td>{position.department.name}</td><td>{position.team?.name ?? "—"}</td><td>{position.salaryBandMinimum || position.salaryBandMaximum ? `${position.currency} ${position.salaryBandMinimum?.toString() ?? "—"} – ${position.salaryBandMaximum?.toString() ?? "—"}` : "Not set"}</td><td>{position.headcountLimit} / {position.fullTimeEquivalent.toString()} FTE</td><td>{position._count.employeeAssignments}</td><td><span className="hr-status success">{position.lifecycleStatus.replaceAll("_", " ")}</span></td><td><details className="hr-row-details"><summary>Review</summary><div className="hr-row-popover hr-position-actions"><h3>{position.title}</h3><p>{position.description || "No description supplied."}</p>{position.lifecycleStatus === "DRAFT" && <DecisionForm action={submitPositionAction} id={position.id} label="Submit for approval" />}{position.lifecycleStatus === "PENDING_APPROVAL" && <><PositionDecisionForm decision="approve" id={position.id} /><PositionDecisionForm decision="reject" id={position.id} /></>}{position.lifecycleStatus === "APPROVED" && <DecisionForm action={openPositionAction} id={position.id} label="Open position" />}{!["DRAFT", "PENDING_APPROVAL", "APPROVED"].includes(position.lifecycleStatus) && <p className="hr-history-note">No lifecycle action is currently available.</p>}</div></details></td></tr>)}</tbody></table></div>{!positions.length && <p className="hr-empty">No positions yet.</p>}</section>
  </main>;
}

function DecisionForm({ action, id, label }: { action: (formData: FormData) => Promise<void>; id: string; label: string }) { return <form action={action} className="hr-inline-action"><input type="hidden" name="id" value={id}/><input className="input" name="reason" placeholder={`${label} reason`} required/><button className="btn btn-primary">{label}</button></form>; }
