import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { availableLeaveBalance } from "@/lib/hr/leave/engine";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { adjustLeaveBalanceAction, assignLeavePolicyAction, createLeavePolicyAction, createLeaveTypeAction, createPublicHolidayAction, runLeaveAccrualAction, runLeaveCarryOverAction, submitReturnToWorkAction } from "./actions";
import { cancelApprovedLeaveAction, reviewLeaveRequestAction } from "@/app/hr/supervisor/leave/actions";

export default async function LeaveAdminPage() {
  const auth = await requireAnyPermission(["leave.read_all", "leave.policy.manage", "leave.override"]);
  const organizationId = auth.user.organizationId;
  const [types, policies, employees, assignments, balances, holidays, requests, longAbsences] = await Promise.all([
    prisma.hrLeaveType.findMany({ where: { organizationId }, orderBy: { name: "asc" } }),
    prisma.hrLeavePolicy.findMany({ where: { organizationId }, include: { leaveType: true }, orderBy: [{ leaveType: { name: "asc" } }, { version: "desc" }] }),
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }] }),
    prisma.hrEmployeeLeavePolicy.findMany({ where: { employee: { organizationId } }, include: { employee: true, leavePolicy: { include: { leaveType: true } } }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
    prisma.hrLeaveBalance.findMany({ where: { organizationId }, include: { employee: true, leaveType: true }, orderBy: [{ periodYear: "desc" }, { employee: { lastName: "asc" } }], take: 250 }),
    prisma.hrPublicHoliday.findMany({ where: { organizationId }, orderBy: { date: "desc" }, take: 100 }),
    prisma.hrLeaveRequest.findMany({ where: { organizationId }, include: { employee: true, leaveType: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.hrLeaveLongAbsence.findMany({ where: { organizationId }, include: { employee: true, startWorkforceEvent: true, returnWorkforceEvent: true }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  return <><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">Leave administration</h1><p className="mt-2 text-slate-600">Versioned policies, immutable balance ledger, approvals, calendar, and employee history.</p></div><div className="flex flex-wrap gap-2"><Link className="btn btn-secondary" href="/hr/admin/leave/configuration">Unit 5 configuration</Link><Link className="btn btn-secondary" href="/hr/admin/leave/policies">Policy history</Link><Link className="btn btn-secondary" href="/hr/admin/leave/calendar">Open leave calendar</Link></div></div>
    <Link className="btn btn-secondary mt-4 inline-flex" href="/hr/admin/leave/reports">Open operations reports</Link>
    <form action={runLeaveAccrualAction} className="mt-5 flex flex-wrap items-end gap-3 rounded-2xl border border-teal-200 bg-teal-50 p-4"><label className="text-sm font-semibold">Accrual effective date<input className="input mt-1" name="effectiveAt" type="date" required /></label><button className="btn btn-secondary">Run scheduled accrual</button><p className="text-sm text-slate-600">Safe to retry: each monthly or quarterly period is idempotent.</p></form>
    <form action={runLeaveCarryOverAction} className="mt-3 flex flex-wrap items-end gap-3 rounded-2xl border border-blue-200 bg-blue-50 p-4"><label className="text-sm font-semibold">Year close/expiry date<input className="input mt-1" name="effectiveAt" type="date" required /></label><button className="btn btn-secondary">Run carry-over and expiry</button><p className="text-sm text-slate-600">Carries eligible balances and expires carry-over idempotently under policy.</p></form>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Create leave type</h2><form action={createLeaveTypeAction} className="mt-4 grid gap-3"><input className="input" name="code" placeholder="Code" required /><input className="input" name="name" placeholder="Name" required /><textarea className="input" name="description" placeholder="Description" /><select className="input" name="unit"><option>DAYS</option><option>HOURS</option></select><label className="flex gap-2 text-sm"><input name="paid" type="checkbox" defaultChecked />Paid leave</label><label className="flex gap-2 text-sm"><input name="requiresAttachment" type="checkbox" />Attachment required</label><button className="btn btn-primary">Create type</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Create policy version</h2><form action={createLeavePolicyAction} className="mt-4 grid gap-3 md:grid-cols-2"><select className="input" name="leaveTypeId" required><option value="">Leave type</option>{types.filter(({ status }) => status === "ACTIVE").map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select><input className="input" name="name" placeholder="Policy name" required /><select className="input" name="entitlementModel"><option>ENTITLEMENT</option><option>EVENT_LIMITED</option><option>UNLIMITED</option><option>UNPAID</option><option>STATUTORY</option><option>LONG_TERM</option></select><input className="input" name="timezone" defaultValue="UTC" required/><input className="input" name="entitlement" type="number" min="0" step="0.25" placeholder="Annual entitlement" required /><select className="input" name="accrualFrequency"><option>ANNUALLY</option><option>MONTHLY</option><option>QUARTERLY</option><option>NONE</option></select><input className="input" name="accrualAmount" type="number" min="0" step="0.25" placeholder="Amount per accrual" /><input className="input" name="maximumBalance" type="number" min="0" step="0.25" placeholder="Maximum balance" /><input className="input" name="carryOverLimit" type="number" min="0" step="0.25" placeholder="Carry-over limit" /><input className="input" name="carryOverExpiryMonth" type="number" min="1" max="12" placeholder="Carry-over expiry month" /><input className="input" name="minimumRequest" type="number" min="0.25" step="0.25" placeholder="Minimum request"/><input className="input" name="minimumNoticeDays" type="number" min="0" defaultValue="0" required /><input className="input" name="maximumConsecutive" type="number" min="0.25" step="0.25" placeholder="Maximum consecutive" /><input className="input" name="probationMonths" type="number" min="0" defaultValue="0" required /><input className="input" name="evidenceClass" placeholder="Restricted evidence class"/><input className="input" name="evidenceRetentionDays" type="number" min="1" placeholder="Evidence retention days"/><input className="input" name="workflowDefinitionKey" placeholder="Approval workflow key"/><input className="input" name="effectiveFrom" type="date" required /><label className="flex gap-2 text-sm"><input name="allowNegativeBalance" type="checkbox" />Allow negative balance</label><label className="flex gap-2 text-sm"><input name="requiresApproval" type="checkbox" defaultChecked />Approval required</label><button className="btn btn-primary md:col-span-2">Create version</button></form></section>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Assign employee policy</h2><form action={assignLeavePolicyAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="leavePolicyId" required><option value="">Active policy</option>{policies.filter(({ status }) => status === "ACTIVE").map((policy) => <option value={policy.id} key={policy.id}>{policy.leaveType.name} — {policy.name} v{policy.version}</option>)}</select><input className="input" name="effectiveFrom" type="date" required /><input className="input" name="reason" placeholder="Assignment reason" required /><button className="btn btn-primary">Assign policy</button></form><ul className="mt-5 space-y-2 text-sm">{assignments.map((assignment) => <li key={assignment.id}>{assignment.employee.legalFirstName} {assignment.employee.lastName} · {assignment.leavePolicy.leaveType.name} v{assignment.leavePolicy.version} · {assignment.status}</li>)}</ul></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Public holiday</h2><form action={createPublicHolidayAction} className="mt-4 grid gap-3"><input className="input" name="name" placeholder="Holiday name" required /><input className="input" name="date" type="date" required /><input className="input" name="country" placeholder="Country" /><input className="input" name="region" placeholder="Region (optional)" /><button className="btn btn-primary">Add holiday</button></form><ul className="mt-5 space-y-2 text-sm">{holidays.map((holiday) => <li key={holiday.id}>{holiday.date.toLocaleDateString()} · {holiday.name}{holiday.region ? ` · ${holiday.region}` : ""}</li>)}</ul></section>
    </div>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Balances</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Type</th><th>Year</th><th>Available</th><th>Reserved</th><th>Used</th><th>Adjustment</th></tr></thead><tbody>{balances.map((balance) => <tr className="border-b last:border-0" key={balance.id}><td className="py-3">{balance.employee.legalFirstName} {balance.employee.lastName}</td><td>{balance.leaveType.name}</td><td>{balance.periodYear}</td><td>{availableLeaveBalance({ opening: Number(balance.opening), accrued: Number(balance.accrued), carriedOver: Number(balance.carriedOver), adjusted: Number(balance.adjusted), reserved: Number(balance.reserved), used: Number(balance.used), expired: Number(balance.expired) })}</td><td>{balance.reserved.toString()}</td><td>{balance.used.toString()}</td><td><form action={adjustLeaveBalanceAction} className="flex gap-2"><input type="hidden" name="balanceId" value={balance.id} /><input className="input max-w-28" name="amount" type="number" step="0.25" required /><input className="input max-w-48" name="reason" placeholder="Reason" required /><button className="font-semibold text-teal-700">Apply</button></form></td></tr>)}</tbody></table></section>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Recent requests</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Leave</th><th>Dates</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{requests.map((request) => <tr className="border-b last:border-0 align-top" key={request.id}><td className="py-3">{request.employee.legalFirstName} {request.employee.lastName}</td><td>{request.leaveType.name}</td><td>{request.startDate.toLocaleDateString()} – {request.endDate.toLocaleDateString()}</td><td>{request.amount.toString()}</td><td>{request.status}</td><td>{request.status === "PENDING" ? <form action={reviewLeaveRequestAction} className="grid gap-2"><input type="hidden" name="requestId" value={request.id} /><input className="input" name="notes" placeholder="Decision notes" /><div className="flex gap-2"><button className="font-semibold text-teal-700" name="decision" value="APPROVED">Approve</button><button className="font-semibold text-red-700" name="decision" value="REJECTED">Reject</button></div></form> : request.status === "APPROVED" ? <form action={cancelApprovedLeaveAction} className="grid gap-2"><input type="hidden" name="requestId" value={request.id} /><input className="input" name="reason" placeholder="Cancellation reason" required /><button className="text-left font-semibold text-red-700">Cancel and restore balance</button></form> : "—"}</td></tr>)}</tbody></table></section>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Long-term absence integration</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Leave event</th><th>Expected return</th><th>Return event</th><th>Action</th></tr></thead><tbody>{longAbsences.map((absence)=><tr className="border-b last:border-0 align-top" key={absence.id}><td className="py-3">{absence.employee.legalFirstName} {absence.employee.lastName}</td><td>{absence.startWorkforceEvent?.status ?? "not created"}</td><td>{absence.expectedReturnAt?.toLocaleDateString() ?? "—"}</td><td>{absence.returnWorkforceEvent?.status ?? "not submitted"}</td><td>{absence.startWorkforceEvent?.status === "APPLIED" && !absence.returnWorkforceEventId ? <form action={submitReturnToWorkAction} className="grid gap-2"><input type="hidden" name="longAbsenceId" value={absence.id}/><input className="input" name="returnAt" type="date" defaultValue={absence.expectedReturnAt?.toISOString().slice(0,10)} required/><input className="input" name="reason" placeholder="Return-to-work reason" required/><button className="font-semibold text-teal-700">Submit governed return event</button></form> : "—"}</td></tr>)}</tbody></table></section>
  </>;
}
