import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { createEmployeeGoalAction, recordEmployeeGoalProgressAction } from "./actions";

export default async function EmployeePerformancePage() {
  const auth = await requirePermission("performance.goal.read_self");
  if (!auth.user.employee) throw new Error("An employee profile is required.");
  const employeeId = auth.user.employee.id;
  const [goals, feedback, checkIns, reviews, interests, plans, readiness] = await Promise.all([
    prisma.hrPerformanceGoal.findMany({ where: { organizationId: auth.user.organizationId, employeeId }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrPerformanceFeedback.findMany({ where: { organizationId: auth.user.organizationId, employeeId, visibility: { in: ["EMPLOYEE_VISIBLE", "MANAGER_EMPLOYEE"] }, status: "SUBMITTED" }, orderBy: { submittedAt: "desc" }, take: 50 }),
    prisma.hrPerformanceCheckIn.findMany({ where: { organizationId: auth.user.organizationId, employeeId, visibility: { in: ["EMPLOYEE_VISIBLE", "MANAGER_EMPLOYEE"] } }, orderBy: { occurredAt: "desc" }, take: 50 }),
    prisma.hrPerformanceReview.findMany({ where: { organizationId: auth.user.organizationId, employeeId }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.hrCareerInterest.findMany({ where: { organizationId: auth.user.organizationId, employeeId }, orderBy: { effectiveFrom: "desc" }, take: 20 }),
    prisma.hrDevelopmentPlan.findMany({ where: { organizationId: auth.user.organizationId, employeeId }, orderBy: { updatedAt: "desc" }, take: 20 }),
    prisma.hrPromotionReadinessAssessment.findMany({ where: { organizationId: auth.user.organizationId, employeeId, finalizedAt: { not: null } }, orderBy: { createdAt: "desc" }, take: 20 }),
  ]);
  return <><h1 className="text-3xl font-bold">My performance &amp; career</h1><p className="mt-2 text-slate-600">Goals, shared feedback, check-ins, reviews, development, and target-specific readiness.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create a goal</h2><form action={createEmployeeGoalAction} className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" name="title" placeholder="Goal title" required/><select className="input" name="goalType"><option value="OPERATIONAL">Operational</option><option value="DEVELOPMENTAL">Developmental</option><option value="GROWTH">Growth</option></select><textarea className="input md:col-span-2" name="outcomeDescription" placeholder="Outcome to achieve" required/><input className="input" name="measure" placeholder="How success will be measured" required/><input className="input" name="dueAt" type="date" required/><button className="btn btn-primary md:col-span-2">Propose goal</button></form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Goals</h2><div className="mt-4 space-y-3">{goals.map((goal) => <article className="rounded-xl border p-4" key={goal.id}><div className="flex justify-between gap-3"><strong>{goal.goalType}</strong><span>{goal.status} · v{goal.currentVersion}</span></div>{goal.status === "ACTIVE" && <form action={recordEmployeeGoalProgressAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="goalId" value={goal.id}/><input type="hidden" name="expectedVersion" value={goal.currentVersion}/><input className="input max-w-28" name="progress" type="number" min="0" max="100" required/><input className="input flex-1" name="note" placeholder="Progress note"/><button className="btn btn-primary">Record progress</button></form>}</article>)}</div></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Visible feedback &amp; check-ins</h2><p className="mt-3 text-sm text-slate-600">{feedback.length} feedback item(s) · {checkIns.length} check-in(s). HR-confidential and calibration-only narratives are not exposed here.</p></article><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Reviews &amp; development</h2><p className="mt-3 text-sm text-slate-600">{reviews.length} review(s) · {plans.length} development plan(s) · {interests.length} career-interest version(s).</p></article><article className="rounded-2xl bg-white p-5 lg:col-span-2"><h2 className="font-bold">Promotion readiness</h2><div className="mt-3 space-y-2">{readiness.length ? readiness.map((item) => <p className="rounded-xl border p-3 text-sm" key={item.id}><strong>{item.state.replaceAll("_", " ")}</strong> — {item.employeeFacingRationale}</p>) : <p className="text-sm text-slate-600">No finalized target-specific readiness assessment.</p>}</div></article></section>
  </>;
}
