import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { createEmployeeGoalAction, recordEmployeeGoalProgressAction, submitSelfReviewAction } from "./actions";

export default async function EmployeePerformancePage() {
  const auth = await requirePermission("performance.goal.read_self");
  if (!auth.user.employee) throw new Error("An employee profile is required.");
  const organizationId = auth.user.organizationId;
  const employeeId = auth.user.employee.id;
  const [goals, feedback, checkIns, reviews, interests, plans, readiness] = await Promise.all([
    prisma.hrPerformanceGoal.findMany({ where: { organizationId, employeeId }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.hrPerformanceFeedback.findMany({ where: { organizationId, employeeId, visibility: { in: ["EMPLOYEE_VISIBLE", "MANAGER_EMPLOYEE"] }, status: "SUBMITTED" }, orderBy: { submittedAt: "desc" }, take: 50 }),
    prisma.hrPerformanceCheckIn.findMany({ where: { organizationId, employeeId, visibility: { in: ["EMPLOYEE_VISIBLE", "MANAGER_EMPLOYEE"] } }, orderBy: { occurredAt: "desc" }, take: 50 }),
    prisma.hrPerformanceReview.findMany({ where: { organizationId, employeeId }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.hrCareerInterest.findMany({ where: { organizationId, employeeId }, orderBy: { effectiveFrom: "desc" }, take: 20 }),
    prisma.hrDevelopmentPlan.findMany({ where: { organizationId, employeeId }, orderBy: { updatedAt: "desc" }, take: 20 }),
    prisma.hrPromotionReadinessAssessment.findMany({ where: { organizationId, employeeId, finalizedAt: { not: null } }, orderBy: { createdAt: "desc" }, take: 20 }),
  ]);
  const planVersions = await prisma.hrDevelopmentPlanVersion.findMany({ where: { organizationId, planId: { in: plans.map(({ id }) => id) } }, orderBy: [{ planId: "asc" }, { version: "desc" }] });
  const currentPlanVersions = planVersions.filter((version) => plans.some((plan) => plan.id === version.planId && plan.currentVersion === version.version));
  const [developmentActions, targetProfiles, targetExpectations] = await Promise.all([
    prisma.hrDevelopmentAction.findMany({ where: { organizationId, planVersionId: { in: currentPlanVersions.map(({ id }) => id) } }, orderBy: [{ planVersionId: "asc" }, { sequence: "asc" }] }),
    prisma.hrJobProfileVersion.findMany({ where: { organizationId, id: { in: readiness.map(({ targetJobProfileVersionId }) => targetJobProfileVersionId) } }, select: { id: true, title: true, version: true } }),
    prisma.hrCompetencyExpectation.findMany({ where: { organizationId, id: { in: currentPlanVersions.flatMap(({ expectationVersionIds }) => expectationVersionIds) } }, select: { id: true, expectation: true } }),
  ]);
  return <><h1 className="text-3xl font-bold">My performance &amp; career</h1><p className="mt-2 text-slate-600">Goals, shared feedback, check-ins, reviews, development, and target-specific readiness.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create a goal</h2><form action={createEmployeeGoalAction} className="mt-4 grid gap-3 md:grid-cols-2"><input className="input" name="title" placeholder="Goal title" required/><select className="input" name="goalType"><option value="OPERATIONAL">Operational</option><option value="DEVELOPMENTAL">Developmental</option><option value="GROWTH">Growth</option></select><textarea className="input md:col-span-2" name="outcomeDescription" placeholder="Outcome to achieve" required/><input className="input" name="measure" placeholder="How success will be measured" required/><input className="input" name="dueAt" type="date" required/><button className="btn btn-primary md:col-span-2">Propose goal</button></form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Goals</h2><div className="mt-4 space-y-3">{goals.map((goal) => <article className="rounded-xl border p-4" key={goal.id}><div className="flex justify-between gap-3"><strong>{goal.goalType}</strong><span>{goal.status} · v{goal.currentVersion}</span></div>{goal.status === "ACTIVE" && <form action={recordEmployeeGoalProgressAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="goalId" value={goal.id}/><input type="hidden" name="expectedVersion" value={goal.currentVersion}/><input className="input max-w-28" name="progress" type="number" min="0" max="100" required/><input className="input flex-1" name="note" placeholder="Progress note"/><button className="btn btn-primary">Record progress</button></form>}</article>)}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Self-review queue</h2><div className="mt-4 space-y-4">{reviews.filter((review) => review.status === "SELF_REVIEW").map((review) => <form action={submitSelfReviewAction} className="grid gap-3 rounded-xl border p-4 md:grid-cols-2" key={review.id}><input type="hidden" name="reviewId" value={review.id}/><input type="hidden" name="expectedVersion" value={review.version}/><textarea className="input" name="achievements" placeholder="Achievements" required/><textarea className="input" name="goalReflection" placeholder="Goal reflection" required/><textarea className="input" name="challenges" placeholder="Challenges" required/><textarea className="input" name="development" placeholder="Development" required/><textarea className="input md:col-span-2" name="careerInterest" placeholder="Career interest"/><button className="btn btn-primary md:col-span-2">Submit immutable self-review</button></form>)}</div></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Visible feedback &amp; check-ins</h2><p className="mt-3 text-sm text-slate-600">{feedback.length} feedback item(s) · {checkIns.length} check-in(s). HR-confidential and calibration-only narratives are not exposed here.</p></article><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Reviews &amp; career interests</h2><p className="mt-3 text-sm text-slate-600">{reviews.length} review(s) · {interests.length} career-interest version(s).</p></article></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">My development plans</h2><div className="mt-4 space-y-4">{plans.length ? plans.map((plan) => { const version = currentPlanVersions.find((item) => item.planId === plan.id); const actions = developmentActions.filter((item) => item.planVersionId === version?.id); const expectations = targetExpectations.filter((item) => version?.expectationVersionIds.includes(item.id)); return <article className="rounded-xl border p-4" key={plan.id}><p><strong>{plan.status}</strong> · version {plan.currentVersion}</p>{version && <><p className="mt-2 text-sm">{version.summary}</p><h3 className="mt-3 text-sm font-semibold">Exact target expectations</h3><ul className="mt-1 list-disc pl-5 text-sm">{expectations.map((item) => <li key={item.id}>{item.expectation}</li>)}</ul><h3 className="mt-3 text-sm font-semibold">Agreed actions</h3>{actions.map((item) => <p className="mt-2 rounded-lg bg-slate-50 p-3 text-sm" key={item.id}><strong>{item.actionType.replaceAll("_", " ")}</strong> · {item.targetCapability}<br/>Gap: {item.gap}<br/>Target date: {item.targetDate.toISOString().slice(0, 10)} · {item.status}</p>)}</>}</article>; }) : <p className="text-sm text-slate-600">No governed development plan.</p>}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Promotion readiness</h2><div className="mt-3 space-y-3">{readiness.length ? readiness.map((item) => { const target = targetProfiles.find((profile) => profile.id === item.targetJobProfileVersionId); return <article className="rounded-xl border p-4 text-sm" key={item.id}><p><strong>{target?.title ?? "Versioned target role"}</strong> · target version {target?.version ?? 1}</p><p className="mt-2 font-semibold">{item.state.replaceAll("_", " ")}</p><p className="mt-1">{item.employeeFacingRationale}</p><p className="mt-2 text-xs text-slate-500">Assessment version {item.version} · finalized {item.finalizedAt?.toISOString()}</p></article>; }) : <p className="text-sm text-slate-600">No finalized target-specific readiness assessment.</p>}</div><p className="mt-4 text-xs text-slate-500">Restricted calibration discussion, internal assessor rationale, and private approval deliberation are intentionally excluded.</p></section>
  </>;
}
