CREATE TABLE "HrPayrollBikEvidenceVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "jurisdictionVersionId" TEXT NOT NULL, "code" TEXT NOT NULL, "version" INTEGER NOT NULL, "valuationMethod" TEXT NOT NULL, "valuationInputs" JSONB NOT NULL, "taxableTreatment" TEXT NOT NULL, "taxableValue" DECIMAL(20,4) NOT NULL, "sourceRuleId" TEXT NOT NULL, "evidenceReference" TEXT, "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "HrPayrollBikEvidenceVersion_org_employee_code_version_key" ON "HrPayrollBikEvidenceVersion"("organizationId","employeeId","code","version");
CREATE UNIQUE INDEX "HrPayrollBikEvidenceVersion_org_correlation_key" ON "HrPayrollBikEvidenceVersion"("organizationId","correlationId");
CREATE INDEX "HrPayrollBikEvidenceVersion_effective_idx" ON "HrPayrollBikEvidenceVersion"("organizationId","employeeId","effectiveFrom","effectiveTo");

CREATE TABLE "HrPayrollTaxReliefClaimVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "jurisdictionVersionId" TEXT NOT NULL, "taxYear" INTEGER NOT NULL, "claimType" TEXT NOT NULL, "version" INTEGER NOT NULL, "claimedAmount" DECIMAL(20,4) NOT NULL, "eligibleAmount" DECIMAL(20,4) NOT NULL, "ytdUtilized" DECIMAL(20,4) NOT NULL DEFAULT 0, "electionRecorded" BOOLEAN NOT NULL, "evidenceReference" TEXT NOT NULL, "remittanceStatus" TEXT NOT NULL, "sourceRuleId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "effectiveFrom" TIMESTAMP(3) NOT NULL, "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HrPayrollTaxReliefClaimVersion_amounts_check" CHECK ("claimedAmount" >= 0 AND "eligibleAmount" >= 0 AND "ytdUtilized" >= 0));
CREATE UNIQUE INDEX "HrPayrollTaxReliefClaimVersion_logical_key" ON "HrPayrollTaxReliefClaimVersion"("organizationId","employeeId","taxYear","claimType","version");
CREATE UNIQUE INDEX "HrPayrollTaxReliefClaimVersion_correlation_key" ON "HrPayrollTaxReliefClaimVersion"("organizationId","correlationId");
CREATE INDEX "HrPayrollTaxReliefClaimVersion_status_idx" ON "HrPayrollTaxReliefClaimVersion"("organizationId","employeeId","taxYear","status");

CREATE TABLE "HrPayrollPriorEmployerYtdVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "taxYear" INTEGER NOT NULL, "version" INTEGER NOT NULL, "priorEmployerReference" TEXT, "gross" DECIMAL(20,4), "eligibleDeductions" DECIMAL(20,4), "taxableIncome" DECIMAL(20,4), "payeDeducted" DECIMAL(20,4), "payeRepaid" DECIMAL(20,4), "handling" TEXT NOT NULL, "evidenceReference" TEXT NOT NULL, "rtaApprovalReference" TEXT, "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HrPayrollPriorEmployerYtdVersion_handling_check" CHECK (("handling"='EVIDENCED' AND "priorEmployerReference" IS NOT NULL AND "gross" IS NOT NULL AND "eligibleDeductions" IS NOT NULL AND "taxableIncome" IS NOT NULL AND "payeDeducted" IS NOT NULL AND "payeRepaid" IS NOT NULL) OR ("handling"='RTA_APPROVED_NO_PRIOR_VALUES' AND "rtaApprovalReference" IS NOT NULL)));
CREATE UNIQUE INDEX "HrPayrollPriorEmployerYtdVersion_logical_key" ON "HrPayrollPriorEmployerYtdVersion"("organizationId","employeeId","taxYear","version");
CREATE UNIQUE INDEX "HrPayrollPriorEmployerYtdVersion_correlation_key" ON "HrPayrollPriorEmployerYtdVersion"("organizationId","correlationId");

CREATE TABLE "HrPayrollEmployeeRtaProfileVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "taxYear" INTEGER NOT NULL, "version" INTEGER NOT NULL, "residenceStateOrFct" TEXT NOT NULL, "rtaCode" TEXT NOT NULL, "taxIdentifierEncrypted" TEXT NOT NULL, "adapterVersion" TEXT NOT NULL, "priorYtdRequirement" TEXT NOT NULL, "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "HrPayrollEmployeeRtaProfileVersion_logical_key" ON "HrPayrollEmployeeRtaProfileVersion"("organizationId","employeeId","taxYear","version");
CREATE UNIQUE INDEX "HrPayrollEmployeeRtaProfileVersion_correlation_key" ON "HrPayrollEmployeeRtaProfileVersion"("organizationId","correlationId");
CREATE INDEX "HrPayrollEmployeeRtaProfileVersion_effective_idx" ON "HrPayrollEmployeeRtaProfileVersion"("organizationId","employeeId","effectiveFrom","effectiveTo");

CREATE TABLE "HrPayrollPensionProfileVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "jurisdictionVersionId" TEXT NOT NULL, "version" INTEGER NOT NULL, "applicability" TEXT NOT NULL, "coverageReason" TEXT, "exemptionReason" TEXT, "rsaEncrypted" TEXT, "pfaCode" TEXT, "pfcReference" TEXT, "basisPolicy" JSONB NOT NULL, "contributionRuleVersion" TEXT NOT NULL, "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "HrPayrollPensionProfileVersion_logical_key" ON "HrPayrollPensionProfileVersion"("organizationId","employeeId","version");
CREATE UNIQUE INDEX "HrPayrollPensionProfileVersion_correlation_key" ON "HrPayrollPensionProfileVersion"("organizationId","correlationId");
CREATE INDEX "HrPayrollPensionProfileVersion_effective_idx" ON "HrPayrollPensionProfileVersion"("organizationId","employeeId","effectiveFrom","effectiveTo");

CREATE TABLE "HrPayrollStatutoryApplicabilityVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "legalEntityId" TEXT NOT NULL, "jurisdictionVersionId" TEXT NOT NULL, "schemeCode" TEXT NOT NULL, "version" INTEGER NOT NULL, "state" TEXT NOT NULL, "reason" TEXT NOT NULL, "evidenceReference" TEXT, "configuration" JSONB, "effectiveFrom" TIMESTAMP(3) NOT NULL, "effectiveTo" TIMESTAMP(3), "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HrPayrollStatutoryApplicabilityVersion_state_check" CHECK ("state" IN ('APPLICABLE_CONFIGURED','NOT_APPLICABLE','OUT_OF_SCOPE','REVIEW_REQUIRED')));
CREATE UNIQUE INDEX "HrPayrollStatutoryApplicabilityVersion_logical_key" ON "HrPayrollStatutoryApplicabilityVersion"("organizationId","legalEntityId","schemeCode","version");
CREATE UNIQUE INDEX "HrPayrollStatutoryApplicabilityVersion_correlation_key" ON "HrPayrollStatutoryApplicabilityVersion"("organizationId","correlationId");
CREATE INDEX "HrPayrollStatutoryApplicabilityVersion_effective_idx" ON "HrPayrollStatutoryApplicabilityVersion"("organizationId","legalEntityId","effectiveFrom","effectiveTo");

CREATE TABLE "HrPayrollRetentionPolicyVersion" ("id" TEXT PRIMARY KEY, "organizationId" TEXT NOT NULL, "jurisdictionVersionId" TEXT NOT NULL, "recordCategory" TEXT NOT NULL, "version" INTEGER NOT NULL, "minimumYears" INTEGER, "holdType" TEXT, "holdUntil" TIMESTAMP(3), "reason" TEXT NOT NULL, "effectiveFrom" TIMESTAMP(3) NOT NULL, "supersedesId" TEXT, "correlationId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "HrPayrollRetentionPolicyVersion_years_check" CHECK ("minimumYears" IS NULL OR "minimumYears" >= 0));
CREATE UNIQUE INDEX "HrPayrollRetentionPolicyVersion_logical_key" ON "HrPayrollRetentionPolicyVersion"("organizationId","jurisdictionVersionId","recordCategory","version");
CREATE UNIQUE INDEX "HrPayrollRetentionPolicyVersion_correlation_key" ON "HrPayrollRetentionPolicyVersion"("organizationId","correlationId");
