import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

export default async function CompensationAdministrationPage() {
  const auth = await requirePermission("compensation.architecture.manage");
  const organizationId = auth.user.organizationId;
  const [markets, bands, policies, cycles, budgets, recommendations, exceptions, decisions, awards, handoffs, jobs] = await Promise.all([
    prisma.hrCompMarket.count({ where: { organizationId } }), prisma.hrCompBand.count({ where: { organizationId } }), prisma.hrCompPolicy.count({ where: { organizationId } }),
    prisma.hrCompCycle.findMany({ where: { organizationId }, orderBy: { effectiveAt: "desc" }, take: 50 }), prisma.hrCompBudget.findMany({ where: { organizationId }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.hrCompRecommendation.count({ where: { organizationId } }), prisma.hrCompException.count({ where: { organizationId } }), prisma.hrCompDecision.count({ where: { organizationId } }),
    prisma.hrBonusAward.count({ where: { organizationId } }), prisma.hrPayrollCompHandoff.groupBy({ by: ["status"], where: { organizationId }, _count: { _all: true } }), prisma.hrCompJobRun.findMany({ where: { organizationId }, orderBy: { startedAt: "desc" }, take: 10 }),
  ]);
  return <><h1 className="text-3xl font-bold">Compensation &amp; rewards governance</h1><p className="mt-2 text-slate-600">Tenant-scoped markets, immutable band and policy versions, cycles, budgets, decisions, rewards, and payroll-ready handoffs.</p><div className="mt-6 grid gap-4 sm:grid-cols-3 lg:grid-cols-6">{[["Markets", markets], ["Bands", bands], ["Policies", policies], ["Recommendations", recommendations], ["Exceptions", exceptions], ["Decisions", decisions], ["Awards", awards]].map(([label,value]) => <article className="rounded-2xl bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</div><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Cycle and budget register</h2><div className="mt-4 space-y-3">{cycles.map((cycle) => <article className="rounded-xl border p-4" key={cycle.id}><strong>{cycle.name}</strong> &middot; {cycle.cycleType} &middot; {cycle.status} &middot; v{cycle.version}<p className="mt-1 text-sm text-slate-600">Effective {cycle.effectiveAt.toISOString().slice(0,10)} &middot; {budgets.filter((budget) => budget.cycleId === cycle.id).length} scoped budget(s)</p></article>)}</div></section><section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Payroll handoff states</h2>{handoffs.map((item) => <p className="mt-2 text-sm" key={item.status}>{item.status}: {item._count._all}</p>)}</article><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Operational worker evidence</h2>{jobs.map((job) => <p className="mt-2 text-sm" key={job.id}>{job.windowKey} &middot; {job.status} &middot; attempt {job.attemptCount}</p>)}</article></section></>;
}
