import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { updateOrganizationSettingsAction } from "./actions";

const days = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"] as const;
export default async function SettingsPage() {
  const auth = await requirePermission("settings.manage");
  const organization = await prisma.hrOrganization.findUniqueOrThrow({ where: { id: auth.user.organizationId }, include: { settings: true } });
  const settings = new Map(organization.settings.map(({ key, value }) => [key, value]));
  const workingDays = Array.isArray(settings.get("workingDays")) ? settings.get("workingDays") as string[] : ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"];
  return <><h1 className="text-3xl font-bold">Organization settings</h1><p className="mt-2 text-slate-600">Canonical organization, locale, calendar, and contact configuration.</p><form action={updateOrganizationSettingsAction} className="mt-6 grid gap-5 rounded-2xl bg-white p-6 md:grid-cols-2"><label className="text-sm font-semibold">Company name<input className="input mt-1" name="companyName" defaultValue={organization.name} required /></label><label className="text-sm font-semibold">Registration number<input className="input mt-1" name="registrationNumber" defaultValue={organization.registrationNumber ?? ""} /></label><label className="text-sm font-semibold">Tax identification number<input className="input mt-1" name="taxIdentificationNumber" defaultValue={organization.taxIdentificationNumber ?? ""} /></label><label className="text-sm font-semibold">Default currency<input className="input mt-1" name="defaultCurrency" defaultValue={organization.defaultCurrency} maxLength={3} required /></label><label className="text-sm font-semibold">Timezone<input className="input mt-1" name="timezone" defaultValue={String(settings.get("timezone") ?? "Africa/Lagos")} required /></label><label className="text-sm font-semibold">Contact email<input className="input mt-1" name="contactEmail" type="email" defaultValue={String(settings.get("contactEmail") ?? "")} required /></label><label className="text-sm font-semibold">Contact phone<input className="input mt-1" name="contactPhone" defaultValue={String(settings.get("contactPhone") ?? "")} required /></label><label className="text-sm font-semibold">Address<textarea className="input mt-1 min-h-24" name="address" defaultValue={String(settings.get("address") ?? "")} required /></label><fieldset className="md:col-span-2"><legend className="text-sm font-semibold">Working days</legend><div className="mt-2 flex flex-wrap gap-4">{days.map((day) => <label className="flex items-center gap-2 text-sm" key={day}><input name="workingDays" type="checkbox" value={day} defaultChecked={workingDays.includes(day)} />{day.replace("_", " ")}</label>)}</div></fieldset><button className="btn btn-primary md:col-span-2">Save organization settings</button></form></>;
}
