import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { approveSalaryRecordAction, assignPayrollComponentAction, createPayrollComponentAction, createPayrollPeriodAction, createSalaryRecordAction } from "./actions";

export default async function PayrollSetupPage() {
  const auth = await requirePermission("payroll.read");
  const organizationId = auth.user.organizationId;
  const [employees, salaries, components, assignments, periods] = await Promise.all([
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { in: ["ACTIVE", "ON_LEAVE"] } }, orderBy: { employeeNumber: "asc" } }),
    prisma.hrSalaryRecord.findMany({ where: { organizationId }, include: { employee: true, approvedBy: true }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
    prisma.hrPayrollComponent.findMany({ where: { organizationId }, orderBy: [{ type: "asc" }, { name: "asc" }] }),
    prisma.hrEmployeePayrollComponent.findMany({ where: { employee: { organizationId } }, include: { employee: true, component: true }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
    prisma.hrPayrollPeriod.findMany({ where: { organizationId }, orderBy: { startsAt: "desc" }, take: 60 }),
  ]);
  return <>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-3xl font-bold">Payroll setup</h1><p className="mt-2 text-slate-600">Effective-dated salary, configured earnings, benefits, taxes, deductions, and payroll periods.</p></div><Link className="btn btn-secondary" href="/hr/admin/payroll">Payroll runs</Link></div>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Propose salary record</h2><form action={createSalaryRecordAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className="input" name="amount" inputMode="decimal" pattern="\d+(\.\d{1,4})?" placeholder="Salary amount" required /><input className="input" name="currency" defaultValue="NGN" maxLength={3} required /></div><select className="input" name="payFrequency"><option>MONTHLY</option><option>BIWEEKLY</option><option>WEEKLY</option></select><input className="input" name="effectiveFrom" type="date" required /><input className="input" name="reason" placeholder="Change reason" required /><button className="btn btn-primary">Submit salary for approval</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Create component</h2><form action={createPayrollComponentAction} className="mt-4 grid gap-3"><input className="input" name="code" placeholder="Code, e.g. HOUSING" required /><input className="input" name="name" placeholder="Display name" required /><select className="input" name="type"><option>EARNING</option><option>DEDUCTION</option><option>TAX</option><option>BENEFIT</option></select><select className="input" name="calculationType"><option>FIXED</option><option>PERCENTAGE_OF_BASE</option><option>PERCENTAGE_OF_GROSS</option></select><label className="flex gap-2 text-sm"><input name="taxable" type="checkbox" />Taxable earning</label><label className="flex gap-2 text-sm"><input name="pensionable" type="checkbox" />Pensionable</label><button className="btn btn-primary">Create component</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Assign component</h2><form action={assignPayrollComponentAction} className="mt-4 grid gap-3"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="componentId" required><option value="">Component</option>{components.filter(({ status }) => status === "ACTIVE").map((component) => <option value={component.id} key={component.id}>{component.code} — {component.name} ({component.calculationType})</option>)}</select><input className="input" name="amount" inputMode="decimal" pattern="\d+(\.\d{1,4})?" placeholder="Fixed amount or percentage" required /><input className="input" name="effectiveFrom" type="date" required /><input className="input" name="reason" placeholder="Assignment reason" required /><button className="btn btn-primary">Assign component</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Create period</h2><form action={createPayrollPeriodAction} className="mt-4 grid gap-3"><input className="input" name="name" placeholder="July 2026" required /><div className="grid grid-cols-2 gap-3"><label className="text-sm font-semibold">Starts<input className="input mt-1" name="startsAt" type="date" required /></label><label className="text-sm font-semibold">Ends<input className="input mt-1" name="endsAt" type="date" required /></label></div><label className="text-sm font-semibold">Pay date<input className="input mt-1" name="payDate" type="date" required /></label><input className="input" name="currency" defaultValue="NGN" maxLength={3} required /><select className="input" name="payFrequency"><option>MONTHLY</option><option>BIWEEKLY</option><option>WEEKLY</option></select><button className="btn btn-primary">Create period</button></form></section>
    </div>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Salary history</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Amount</th><th>Effective</th><th>Approval</th><th>Action</th></tr></thead><tbody>{salaries.map((salary) => <tr className="border-b last:border-0" key={salary.id}><td className="py-3">{salary.employee.employeeNumber} — {salary.employee.legalFirstName} {salary.employee.lastName}</td><td>{salary.currency} {salary.amount.toFixed(2)} / {salary.payFrequency.toLowerCase()}</td><td>{salary.effectiveFrom.toLocaleDateString()} {salary.effectiveTo ? `– ${salary.effectiveTo.toLocaleDateString()}` : "onward"}</td><td>{salary.approvedAt ? `Approved ${salary.approvedAt.toLocaleDateString()}` : "Pending"}</td><td>{!salary.approvedAt && auth.permissions.has("payroll.approve") ? <form action={approveSalaryRecordAction} className="flex gap-2"><input type="hidden" name="id" value={salary.id} /><input className="input max-w-48" name="reason" placeholder="Approval reason" required /><button className="font-semibold text-teal-700">Approve</button></form> : "—"}</td></tr>)}</tbody></table></section>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Component assignments</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Employee</th><th>Component</th><th>Value</th><th>Effective</th><th>Status</th></tr></thead><tbody>{assignments.map((assignment) => <tr className="border-b last:border-0" key={assignment.id}><td className="py-3">{assignment.employee.employeeNumber} — {assignment.employee.legalFirstName} {assignment.employee.lastName}</td><td>{assignment.component.code} — {assignment.component.name}</td><td>{assignment.amount.toString()}{assignment.component.calculationType === "FIXED" ? "" : "%"}</td><td>{assignment.effectiveFrom.toLocaleDateString()}</td><td>{assignment.status}</td></tr>)}</tbody></table></section>
    <section className="mt-5 rounded-2xl bg-white p-5"><h2 className="font-bold">Periods</h2><ul className="mt-4 space-y-2 text-sm">{periods.map((period) => <li key={period.id}>{period.name} · {period.startsAt.toLocaleDateString()}–{period.endsAt.toLocaleDateString()} · pay {period.payDate.toLocaleDateString()} · {period.currency} · {period.payFrequency.toLowerCase()}</li>)}</ul></section>
  </>;
}
