import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { projectedPeriodBalance } from "@/lib/hr/leave/unit5";

export default async function LeaveReportsPage() {
  const auth = await requireAnyPermission(["leave.read_all", "leave.override", "report.read"]);
  const organizationId = auth.user.organizationId;
  const now = new Date();
  const upcomingEnd = new Date(now.getTime() + 30 * 86_400_000);
  const [versions, pending, periods, adjustments, longAbsences, jobs] = await Promise.all([
    prisma.hrLeaveRequestVersion.findMany({ where: { organizationId, segments: { some: { startsAt: { lte: upcomingEnd }, endsAt: { gt: now } } } }, include: { employee: true, leavePolicy: { include: { leaveType: true } }, segments: { orderBy: { sequence: "asc" } }, transitions: { orderBy: { createdAt: "desc" }, take: 1 } }, orderBy: { createdAt: "desc" }, take: 250 }),
    prisma.hrWorkflowInstance.findMany({ where: { organizationId, subjectType: "HrLeaveRequestVersion", status: "ACTIVE" }, include: { stageRuns: { where: { status: "ACTIVE" } } }, orderBy: { startedAt: "asc" }, take: 100 }),
    prisma.hrLeaveAccountPeriod.findMany({ where: { account: { organizationId }, periodEnd: { gt: now }, OR: [{ carriedOver: { gt: 0 } }, { expired: { gt: 0 } }] }, include: { account: { include: { employee: true, leaveType: true } }, leavePolicy: true }, orderBy: { periodEnd: "asc" }, take: 250 }),
    prisma.hrLeaveLedgerEntry.findMany({ where: { organizationId, kind: { in: ["ADJUSTMENT", "CORRECTION", "REVERSAL"] } }, include: { accountPeriod: { include: { account: { include: { employee: true, leaveType: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.hrLeaveLongAbsence.findMany({ where: { organizationId, status: { notIn: ["COMPLETED", "CANCELLED"] } }, include: { employee: true }, orderBy: { expectedReturnAt: "asc" }, take: 100 }),
    prisma.hrLeaveJobRun.findMany({ where: { organizationId }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  const activeVersions = versions.filter((item) => ["APPROVED", "SCHEDULED", "IN_PROGRESS"].includes(item.transitions[0]?.toStatus ?? item.lifecycleStatus));
  const awayToday = activeVersions.filter((item) => item.segments.some((segment) => segment.startsAt <= now && segment.endsAt > now));
  const upcoming = activeVersions.filter((item) => item.segments.some((segment) => segment.startsAt > now && segment.startsAt <= upcomingEnd));
  const failedJobs = jobs.filter(({ status }) => ["FAILED", "ABANDONED"].includes(status));
  return <main><h1 className="text-3xl font-bold">Leave operations reporting</h1><p className="mt-2 text-slate-600">Authorization-scoped operational reporting. Confidential evidence and medical contents are excluded.</p>
    <section className="mt-6 grid gap-4 md:grid-cols-3 xl:grid-cols-6">{[["Away today", awayToday.length], ["Upcoming 30 days", upcoming.length], ["Pending approvals", pending.length], ["Long absences", longAbsences.length], ["Failed jobs", failedJobs.length], ["Adjustments", adjustments.length]].map(([label, value]) => <article className="rounded-2xl bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</section>
    <section className="mt-6 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Away and upcoming</h2><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Employee</th><th>Leave</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{activeVersions.map((item) => <tr className="border-t" key={item.id}><td className="py-3">{item.employee.legalFirstName} {item.employee.lastName}</td><td>{item.leavePolicy.leaveType.name}</td><td>{item.segments[0]?.startsAt.toLocaleString() ?? "—"}</td><td>{item.segments.at(-1)?.endsAt.toLocaleString() ?? "—"}</td><td>{item.transitions[0]?.toStatus ?? item.lifecycleStatus}</td></tr>)}</tbody></table></section>
    <section className="mt-6 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-bold">Carryover and expiry</h2><table className="mt-4 w-full text-left text-sm"><thead><tr><th>Employee</th><th>Type</th><th>Available</th><th>Carried</th><th>Reserved</th><th>Expired</th><th>Period end</th></tr></thead><tbody>{periods.map((period) => <tr className="border-t" key={period.id}><td className="py-3">{period.account.employee.legalFirstName} {period.account.employee.lastName}</td><td>{period.account.leaveType.name}</td><td>{projectedPeriodBalance({ granted: Number(period.granted), accrued: Number(period.accrued), carriedOver: Number(period.carriedOver), carriedOut: Number(period.carriedOut), adjusted: Number(period.adjusted), reserved: Number(period.reserved), consumed: Number(period.consumed), expired: Number(period.expired) })}</td><td>{period.carriedOver.toString()}</td><td>{period.reserved.toString()}</td><td>{period.expired.toString()}</td><td>{period.periodEnd.toLocaleDateString()}</td></tr>)}</tbody></table></section>
    <section className="mt-6 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Returns due</h2><ul className="mt-3 space-y-2 text-sm">{longAbsences.map((item) => <li key={item.id}>{item.employee.legalFirstName} {item.employee.lastName} · {item.status} · {item.expectedReturnAt?.toLocaleDateString() ?? "date not set"}</li>)}</ul></article><article className="rounded-2xl bg-white p-5"><h2 className="font-bold">Worker failures</h2><ul className="mt-3 space-y-2 text-sm">{failedJobs.map((item) => <li key={item.id}>{item.jobType} · {item.windowKey} · attempt {item.attemptCount} · {item.safeError ?? "safe error unavailable"}</li>)}</ul>{!failedJobs.length && <p className="mt-3 text-sm text-slate-500">No recorded Unit 5 worker failures.</p>}</article></section>
  </main>;
}
