import Link from "next/link";
import type { ProvisioningPayload } from "@/lib/hr/employees/provisioning";
import { approveAndFinalizeProvisioningAction, cancelProvisioningDraftAction, saveProvisioningStepAction, submitProvisioningDraftAction } from "@/app/hr/admin/employees/new/actions";

type Option = { id: string; label: string };
type Props = { draft: { id: string; status: string; createdById: string }; payload: ProvisioningPayload; step: number; score: number; checks: Array<{ key: string; label: string; ready: boolean }>; departments: Option[]; teams: Option[]; positions: Option[]; managers: Option[]; templates: Option[]; actorId: string };
const steps = ["Personal", "Employment", "Assignment", "Compensation", "Payroll", "Access", "Onboarding", "Review"];
const value = (input: unknown) => typeof input === "string" ? input : "";

export function EmployeeProvisioningWizard(props: Props) {
  const { draft, payload, step } = props;
  const editable = draft.status === "DRAFT";
  return <div className="mt-6 grid gap-6 xl:grid-cols-[240px_1fr]">
    <aside className="rounded-2xl bg-white p-5"><p className="text-sm font-bold">Readiness {props.score}%</p><div className="mt-3 h-2 rounded bg-slate-200"><div className="h-2 rounded bg-teal-600" style={{ width: `${props.score}%` }} /></div><ol className="mt-5 space-y-2 text-sm">{steps.map((label, index) => <li key={label}><Link className={step === index + 1 ? "font-bold text-teal-700" : ""} href={`?draft=${draft.id}&step=${index + 1}`}>{index + 1}. {label}</Link></li>)}</ol></aside>
    <section className="rounded-2xl bg-white p-6"><p className="text-xs font-bold uppercase tracking-wider text-teal-700">Step {step} of 8 · {draft.status}</p><h1 className="mt-2 text-3xl font-bold">{steps[step - 1]}</h1>
      {step < 8 && editable ? <form action={saveProvisioningStepAction} className="mt-6 grid gap-4 md:grid-cols-2">
        <input type="hidden" name="draftId" value={draft.id} /><input type="hidden" name="section" value={["personal","employment","assignment","compensation","payroll","access","onboarding"][step - 1]} /><input type="hidden" name="nextStep" value={step + 1} />
        {step === 1 && <><input className="input" name="legalFirstName" defaultValue={value(payload.personal?.legalFirstName)} placeholder="Legal first name" required /><input className="input" name="middleName" defaultValue={value(payload.personal?.middleName)} placeholder="Middle name" /><input className="input" name="lastName" defaultValue={value(payload.personal?.lastName)} placeholder="Last name" required /><input className="input" name="preferredName" defaultValue={value(payload.personal?.preferredName)} placeholder="Preferred name" /><input className="input" name="dateOfBirth" type="date" defaultValue={value(payload.personal?.dateOfBirth)} /><input className="input" name="personalEmail" type="email" defaultValue={value(payload.personal?.personalEmail)} placeholder="Personal email" required /><input className="input" name="phone" defaultValue={value(payload.personal?.phone)} placeholder="Phone" /><input className="input" name="addressLine1" defaultValue={value(payload.personal?.addressLine1)} placeholder="Home address" /><input className="input" name="city" defaultValue={value(payload.personal?.city)} placeholder="City" /><input className="input" name="country" defaultValue={value(payload.personal?.country)} placeholder="Country" /><input className="input" name="emergencyName" defaultValue={value(payload.personal?.emergencyName)} placeholder="Emergency contact name" /><input className="input" name="emergencyRelationship" defaultValue={value(payload.personal?.emergencyRelationship)} placeholder="Relationship" /><input className="input" name="emergencyPhone" defaultValue={value(payload.personal?.emergencyPhone)} placeholder="Emergency phone" /></>}
        {step === 2 && <><input className="input" name="employeeNumber" defaultValue={value(payload.employment?.employeeNumber)} placeholder="Employee number (optional)" /><label>Hire date<input className="input mt-1" name="hireDate" type="date" defaultValue={value(payload.employment?.hireDate)} required /></label><label>Start date<input className="input mt-1" name="startDate" type="date" defaultValue={value(payload.employment?.startDate)} required /></label><select className="input" name="employmentType" defaultValue={payload.employment?.employmentType ?? "FULL_TIME"}><option>FULL_TIME</option><option>PART_TIME</option><option>CONTRACT</option><option>INTERN</option><option>TEMPORARY</option></select><select className="input" name="workMode" defaultValue={payload.employment?.workMode ?? "HYBRID"}><option>ONSITE</option><option>HYBRID</option><option>REMOTE</option></select><input className="input" name="location" defaultValue={value(payload.employment?.location)} placeholder="Work location" /><input className="input" name="probationEndDate" type="date" defaultValue={value(payload.employment?.probationEndDate)} /><textarea className="input md:col-span-2" name="notes" defaultValue={value(payload.employment?.notes)} placeholder="Employment notes" /></>}
        {step === 3 && <><select className="input" name="departmentId" defaultValue={payload.assignment?.departmentId ?? ""} required><option value="">Department</option>{props.departments.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select><select className="input" name="teamId" defaultValue={payload.assignment?.teamId ?? ""}><option value="">No team</option>{props.teams.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select><select className="input" name="positionId" defaultValue={payload.assignment?.positionId ?? ""} required><option value="">Position</option>{props.positions.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select><select className="input" name="primaryManagerId" defaultValue={payload.assignment?.primaryManagerId ?? ""} required><option value="">Primary manager</option>{props.managers.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select><input className="input" name="effectiveFrom" type="date" defaultValue={value(payload.assignment?.effectiveFrom)} required /><input className="input" name="reason" defaultValue={value(payload.assignment?.reason)} placeholder="Assignment reason" required /></>}
        {step === 4 && <><input className="input" name="currency" defaultValue={payload.compensation?.currency ?? "NGN"} maxLength={3} required /><input className="input" name="baseSalary" inputMode="decimal" defaultValue={value(payload.compensation?.baseSalary)} placeholder="Base salary" required /><select className="input" name="payFrequency" defaultValue={payload.compensation?.payFrequency ?? "MONTHLY"}><option>MONTHLY</option><option>BIWEEKLY</option><option>WEEKLY</option></select><input className="input" name="effectiveFrom" type="date" defaultValue={value(payload.compensation?.effectiveFrom)} required /><input className="input md:col-span-2" name="reason" defaultValue={value(payload.compensation?.reason)} placeholder="Compensation reason" required /></>}
        {step === 5 && <><input className="input" name="bankName" defaultValue={value(payload.payroll?.bankName)} placeholder="Bank name" required /><input className="input" name="accountName" defaultValue={value(payload.payroll?.accountName)} placeholder="Account name" required /><input className="input" name="accountNumber" defaultValue={value(payload.payroll?.accountNumber)} autoComplete="off" placeholder="Full account number" required /><input className="input" name="taxCountry" defaultValue={payload.payroll?.taxCountry ?? "Nigeria"} placeholder="Payroll/tax country" required /><input className="input" name="taxId" defaultValue={value(payload.payroll?.taxId)} autoComplete="off" placeholder="Tax ID" /><input className="input" name="pensionProvider" defaultValue={value(payload.payroll?.pensionProvider)} placeholder="Pension provider" /><input className="input" name="pensionId" defaultValue={value(payload.payroll?.pensionId)} autoComplete="off" placeholder="Pension ID" /></>}
        {step === 6 && <><label className="flex items-center gap-2"><input name="boolean:createUser" type="hidden" value="false" /><input name="boolean:createUser" type="checkbox" value="true" defaultChecked={payload.access?.createUser} />Create user account</label><input className="input" name="email" type="email" defaultValue={value(payload.access?.email)} placeholder="Login email" /><select className="input" name="role" defaultValue={payload.access?.role ?? "EMPLOYEE"}><option>EMPLOYEE</option><option disabled>Privileged roles require approval</option></select><label className="flex items-center gap-2"><input name="boolean:sendInvitation" type="hidden" value="false" /><input name="boolean:sendInvitation" type="checkbox" value="true" defaultChecked={payload.access?.sendInvitation} />Send invitation</label><label className="flex items-center gap-2"><input name="boolean:requireMfa" type="hidden" value="false" /><input name="boolean:requireMfa" type="checkbox" value="true" defaultChecked={payload.access?.requireMfa} />Require MFA</label></>}
        {step === 7 && <><label className="flex items-center gap-2"><input name="boolean:start" type="hidden" value="false" /><input name="boolean:start" type="checkbox" value="true" defaultChecked={payload.onboarding?.start} />Start onboarding</label><select className="input" name="templateId" defaultValue={payload.onboarding?.templateId ?? ""}><option value="">Onboarding template</option>{props.templates.map(o => <option key={o.id} value={o.id}>{o.label}</option>)}</select><input className="input" name="orientationDate" type="date" defaultValue={value(payload.onboarding?.orientationDate)} /></>}
        <button className="btn btn-primary md:col-span-2">Save and continue</button></form> : null}
      {step === 8 && <div className="mt-6"><div className="grid gap-3 sm:grid-cols-2">{props.checks.map(check => <div className={`rounded-xl border p-3 ${check.ready ? "border-teal-200 bg-teal-50" : "border-amber-200 bg-amber-50"}`} key={check.key}>{check.ready ? "✓" : "○"} {check.label}</div>)}</div><div className="mt-6 flex flex-wrap gap-3">{draft.status === "DRAFT" && <form action={submitProvisioningDraftAction}><input type="hidden" name="draftId" value={draft.id} /><button className="btn btn-primary">Submit for approval</button></form>}{draft.status === "PENDING_APPROVAL" && draft.createdById !== props.actorId && <form action={approveAndFinalizeProvisioningAction}><input type="hidden" name="draftId" value={draft.id} /><button className="btn btn-primary">Approve and activate</button></form>}<form action={cancelProvisioningDraftAction}><input type="hidden" name="draftId" value={draft.id} /><button className="btn btn-secondary text-red-700">Cancel</button></form></div>{draft.status === "PENDING_APPROVAL" && draft.createdById === props.actorId ? <p className="mt-4 text-sm text-amber-700">A different authorized administrator must approve and activate this employee.</p> : null}</div>}
    </section>
  </div>;
}
