"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Bell, CheckCircle2, ChevronLeft, ChevronRight, FileText, Filter, MoreVertical, Search, Settings, ShieldCheck, Users, WalletCards, Workflow } from "lucide-react";
import { markAllNotificationsReadAction, markNotificationReadAction } from "@/app/hr/notifications/actions";
import { HrModal } from "./HrModal";
export type NotificationItem = { id: string; category: string; title: string; body: string; href: string | null; readAt: string | null; createdAt: string };
const categories = ["All Notifications", "Unread", "Action Required", "System Updates", "Workflows", "HR & People", "Payroll", "Documents"];
const iconFor = (c:string) => /payroll/i.test(c)?WalletCards:/document/i.test(c)?FileText:/workflow/i.test(c)?Workflow:/hr|people|onboard/i.test(c)?Users:ShieldCheck;
const toneFor = (c:string) => /payroll/i.test(c)?"purple":/leave|access/i.test(c)?"orange":/document|onboard/i.test(c)?"blue":"green";
export function HrNotificationCenter({ unread, notifications }: { unread:number; notifications:NotificationItem[] }) {
 const [open,setOpen]=useState(false),[category,setCategory]=useState("All Notifications"),[query,setQuery]=useState(""),[page,setPage]=useState(1);
 const filtered=useMemo(()=>notifications.filter(n=>(category==="All Notifications"||(category==="Unread"?!n.readAt:n.category.toLowerCase().includes(category.split(" ")[0].toLowerCase())))&&`${n.title} ${n.body}`.toLowerCase().includes(query.toLowerCase())),[notifications,category,query]); const pages=Math.max(1,Math.ceil(filtered.length/8)),shown=filtered.slice((page-1)*8,page*8);
 return <><button className="hr-notification" type="button" onClick={()=>setOpen(true)} aria-label={`${unread} unread notifications`}><Bell/>{unread>0&&<span>{unread>99?"99+":unread}</span>}</button><HrModal open={open} title="Notifications" onClose={()=>setOpen(false)} wide><form action={markAllNotificationsReadAction} className="hr-notification-mark"><button className="btn btn-secondary"><CheckCircle2/> Mark all as read</button></form><div className="hr-notification-layout"><aside className="hr-notification-nav"><nav>{categories.map(x=><button className={category===x?"active":""} key={x} onClick={()=>{setCategory(x);setPage(1)}}><span>{x}</span><b>{x==="Unread"?unread:x==="All Notifications"?notifications.length:notifications.filter(n=>n.category.toLowerCase().includes(x.split(" ")[0].toLowerCase())).length}</b></button>)}</nav><p>QUICK FILTERS</p><nav>{["High Priority","Due Today","This Week"].map(x=><button key={x}><span>{x}</span><b>0</b></button>)}</nav><Link href="/hr/notifications"><Settings/> Notification settings</Link></aside><section className="hr-notification-content"><div className="hr-notification-tools"><label><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search notifications..."/></label><button className="btn btn-secondary"><Filter/> Filter</button></div><div className="hr-notification-list">{shown.map(n=>{const Icon=iconFor(n.category),d=new Date(n.createdAt);return <article key={n.id} className={!n.readAt?"unread":""}><i/><span className={`hr-notification-icon ${toneFor(n.category)}`}><Icon/></span><div><strong>{n.title}</strong><p>{n.body}</p><small>{d.toLocaleDateString()} <b>•</b> {d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})} <b>•</b> {n.category}</small></div><div className="hr-notification-side"><span className={`hr-category ${toneFor(n.category)}`}>{n.category}</span><small>{d.toLocaleDateString()}</small><div>{n.href?<Link className="btn btn-secondary" href={n.href}>View</Link>:!n.readAt?<form action={markNotificationReadAction}><input type="hidden" name="id" value={n.id}/><button className="btn btn-secondary">Mark read</button></form>:null}<button aria-label="More notification actions"><MoreVertical/></button></div></div></article>})}{!shown.length&&<p className="hr-empty">No notifications match this filter.</p>}</div><footer className="hr-modal-pagination"><span>Showing {filtered.length?(page-1)*8+1:0} to {Math.min(page*8,filtered.length)} of {filtered.length} notifications</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/></button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button className={n===page?"active":""} key={n} onClick={()=>setPage(n)}>{n}</button>)}<button disabled={page===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight/></button></div></footer></section></div></HrModal></>;
}
