import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

export default async function AuditPage({ searchParams }: { searchParams: Promise<{ action?: string; entityType?: string }> }) {
  const auth = await requirePermission("audit.read");
  const params = await searchParams;
  const action = params.action?.trim().slice(0, 120);
  const entityType = params.entityType?.trim().slice(0, 120);
  const events = await prisma.hrAuditEvent.findMany({ where: { organizationId: auth.user.organizationId, ...(action ? { action: { contains: action, mode: "insensitive" } } : {}), ...(entityType ? { entityType: { equals: entityType, mode: "insensitive" } } : {}) }, include: { actor: { select: { email: true } } }, orderBy: { createdAt: "desc" }, take: 250 });
  return <><h1 className="text-3xl font-bold">Audit trail</h1><p className="mt-2 text-slate-600">Immutable security and business events. Sensitive values are redacted before storage.</p><form className="mt-6 grid gap-3 rounded-2xl bg-white p-5 md:grid-cols-[1fr_1fr_auto]"><input className="input" name="action" defaultValue={action} placeholder="Filter action" /><input className="input" name="entityType" defaultValue={entityType} placeholder="Filter entity type" /><button className="btn btn-secondary">Filter</button></form><div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Time</th><th className="p-4">Actor</th><th className="p-4">Action</th><th className="p-4">Entity</th><th className="p-4">Reason</th><th className="p-4">Correlation</th></tr></thead><tbody>{events.map((event) => <tr className="border-b last:border-0 align-top" key={event.id}><td className="whitespace-nowrap p-4">{event.createdAt.toLocaleString()}</td><td className="p-4">{event.actor?.email ?? event.actorRole ?? "System"}</td><td className="p-4 font-mono">{event.action}</td><td className="p-4">{event.entityType}{event.entityId ? <span className="block max-w-48 break-all text-xs text-slate-500">{event.entityId}</span> : null}</td><td className="max-w-80 whitespace-pre-wrap p-4">{event.reason ?? "—"}</td><td className="max-w-56 break-all p-4 font-mono text-xs">{event.correlationId}</td></tr>)}</tbody></table>{!events.length ? <p className="p-6 text-slate-500">No matching audit events.</p> : null}</div></>;
}
