'use client';

import { useRef, useState } from 'react';
import { Check, ChevronDown } from 'lucide-react';
import styles from './FeaturedSolutions.module.css';

type PreviewType = 'analytics' | 'support' | 'workflow' | 'research' | 'cloud';
type Solution = { label: string; title: string; summary: string; challenge: string; response: string; outcomes: string[]; technologies: string[]; previewType: PreviewType };

const solutions: Solution[] = [
  { label: 'Business Intelligence', title: 'Business Intelligence and Performance Dashboard', summary: 'A centralized analytics environment that transforms fragmented operational data into clear, actionable business insight.', challenge: 'Organizations often depend on disconnected spreadsheets, manual reporting, and inconsistent performance metrics, making it difficult to understand what is happening across the business.', response: 'We design secure analytics platforms that consolidate information, automate reporting, and provide decision-makers with reliable dashboards and performance indicators.', outcomes: ['Faster and more confident decision-making', 'Reduced manual reporting workload', 'Improved visibility across teams and operations'], technologies: ['React', 'Next.js', 'TypeScript', 'Python', 'PostgreSQL', 'Power BI'], previewType: 'analytics' },
  { label: 'AI Customer Support', title: 'AI-Assisted Customer Support Platform', summary: 'An intelligent support environment that helps customers find answers quickly while preserving clear paths to human assistance.', challenge: 'Support teams frequently handle repetitive questions, disconnected knowledge sources, and growing request volumes that reduce response speed.', response: 'We build AI-assisted support systems that retrieve approved information, automate routine interactions, organize conversations, and escalate complex cases to human teams.', outcomes: ['Faster response times', 'Reduced repetitive support work', 'More consistent customer experiences'], technologies: ['Next.js', 'Node.js', 'Python', 'OpenAI', 'PostgreSQL', 'Redis'], previewType: 'support' },
  { label: 'Workflow Automation', title: 'Internal Workflow Automation System', summary: 'A custom operational platform that replaces repetitive manual processes with structured and measurable digital workflows.', challenge: 'Manual approvals, spreadsheet-based tracking, and fragmented communication can create delays, errors, and limited accountability.', response: 'We design internal workflow systems that automate task routing, approvals, notifications, status tracking, and operational reporting.', outcomes: ['Reduced process delays', 'Improved operational accuracy', 'Clearer ownership and accountability'], technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'GitHub Actions'], previewType: 'workflow' },
  { label: 'Research Analytics', title: 'Research Data and Analytics Platform', summary: 'A secure platform for collecting, managing, analyzing, and communicating complex research information.', challenge: 'Research teams often work with disconnected datasets, manual analysis processes, and reporting tools that are difficult to maintain or scale.', response: 'We build research platforms that support structured data collection, validation, analysis, visualization, and controlled reporting.', outcomes: ['More reliable research data', 'Faster analysis and reporting', 'Improved collaboration across research teams'], technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Power BI', 'Docker'], previewType: 'research' },
  { label: 'Cloud Operations', title: 'Cloud Infrastructure and Operations Platform', summary: 'A unified operational view for monitoring digital infrastructure, deployments, reliability, and technical performance.', challenge: 'Growing systems can become difficult to monitor when cloud resources, deployment processes, and operational alerts are spread across multiple tools.', response: 'We design cloud operations environments that centralize system health, deployment visibility, alerts, and infrastructure performance.', outcomes: ['Improved infrastructure visibility', 'Faster response to technical issues', 'More reliable deployment operations'], technologies: ['AWS', 'Azure', 'Docker', 'GitHub Actions', 'Node.js', 'PostgreSQL'], previewType: 'cloud' },
];

const Dot = () => <span className={styles.dot} />;
function PreviewShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className={styles.preview} aria-hidden="true"><div className={styles.previewBar}><span><Dot /> Zentric workspace</span><b>{title}</b></div>{children}</div>;
}
function AnalyticsPreview() { return <PreviewShell title="Performance overview"><div className={styles.metrics}><span>Revenue view<b>£482K</b><em>↗ 8.4%</em></span><span>Active operations<b>128</b></span><span>Reporting cycle<b>92%</b></span></div><div className={styles.chartArea}><div><small>Performance trend</small><svg viewBox="0 0 420 105" preserveAspectRatio="none"><path d="M5 87 C65 82 75 56 130 64 S210 35 260 48 S340 12 415 20" /><line x1="0" y1="103" x2="420" y2="103" /></svg></div><div className={styles.dataRows}><small>Recent performance</small><span>Operations <b>94%</b></span><span>Delivery <b>89%</b></span><span>Quality <b>97%</b></span></div></div></PreviewShell>; }
function SupportPreview() { return <PreviewShell title="Support assistant"><div className={styles.support}><div className={styles.conversation}><span className={styles.customer}>How can I update my service access?</span><span className={styles.assistant}>I found the approved access guide. I can walk you through the steps.</span><span className={styles.customer}>I also need help with permissions.</span></div><aside><small>KNOWLEDGE SOURCES</small><b><Dot /> 3 sources verified</b><span>Access guide</span><span>Permissions policy</span><hr/><small>ESCALATION</small><b>Human support ready</b></aside></div></PreviewShell>; }
function WorkflowPreview() { return <PreviewShell title="Operations workflow"><div className={styles.stages}>{['Submitted','Review','Approval','Complete'].map((x,i)=><span className={i===1?styles.activeStage:''} key={x}><i>{i+1}</i>{x}</span>)}</div><div className={styles.taskList}><small>ACTIVE TASKS</small><span><Dot /> Validate request details <b>In review</b></span><span><i /> Confirm department owner <b>Queued</b></span><span><i /> Prepare approval record <b>Queued</b></span></div></PreviewShell>; }
function ResearchPreview() { return <PreviewShell title="Study reporting"><div className={styles.researchTop}><span><small>DATASET</small><b>Operational study 04</b><em>2,480 validated records</em></span><span><small>DATA QUALITY</small><b>96.8%</b><div className={styles.progress}><i /></div></span></div><div className={styles.distribution}><small>RESPONSE DISTRIBUTION</small>{[48,72,58,90,64,80,55,68].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div><div className={styles.dataRows}><span>Validation review <b>Complete</b></span><span>Analysis model <b>Running</b></span><span>Final report <b>76%</b></span></div></PreviewShell>; }
function CloudPreview() { return <PreviewShell title="Cloud operations"><div className={styles.metrics}><span>System health<b><Dot /> Healthy</b></span><span>Uptime<b>99.98%</b></span><span>Deployments<b>12</b></span></div><div className={styles.cloudRows}><small>SERVICE ACTIVITY</small><span><Dot /><b>API services</b><em>Operational</em><small>42 ms</small></span><span><Dot /><b>Data pipeline</b><em>Operational</em><small>8 min ago</small></span><span><Dot /><b>Web deployment</b><em>Completed</em><small>v2.8.1</small></span></div></PreviewShell>; }
function SolutionPreview({ type }: { type: PreviewType }) { return type === 'analytics' ? <AnalyticsPreview /> : type === 'support' ? <SupportPreview /> : type === 'workflow' ? <WorkflowPreview /> : type === 'research' ? <ResearchPreview /> : <CloudPreview />; }

function SolutionContent({ solution, id }: { solution: Solution; id: string }) {
  return <div className={styles.content} id={id}><header><p className={styles.previewType}>{solution.previewType.replace(/^./, c => c.toUpperCase())}</p><h3>{solution.title}</h3><p>{solution.summary}</p></header><SolutionPreview type={solution.previewType}/><div className={styles.explanation}><div><h4>Business Challenge</h4><p>{solution.challenge}</p></div><div><h4>Zentric Solution</h4><p>{solution.response}</p></div></div><div className={styles.outcomes}><h4>Business Outcomes</h4>{solution.outcomes.map(x=><p key={x}><Check size={15}/>{x}</p>)}</div><div className={styles.technologies}><h4>Technologies</h4><p>{solution.technologies.map((x,i)=><span key={x}>{i > 0 && <i>•</i>}{x}</span>)}</p></div></div>;
}

export function FeaturedSolutions() {
  const [active, setActive] = useState(0);
  const hoverTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const selectOnHover = (index: number) => { hoverTimer.current = setTimeout(() => setActive(index), 180); };
  const cancelHover = () => { if (hoverTimer.current) clearTimeout(hoverTimer.current); };
  return <section className={styles.section} aria-labelledby="featured-solutions-heading"><div className={styles.container}><header className={styles.sectionHeader}><p>FEATURED SOLUTIONS</p><h2 id="featured-solutions-heading">Solutions Built Around Real Business Needs</h2><span>Explore how Zentric combines software engineering, artificial intelligence, data, and cloud technologies to solve complex operational challenges.</span></header>
    <div className={styles.desktopWorkspace}><div className={styles.selector} role="tablist" aria-label="Featured solutions">{solutions.map((s,i)=><button role="tab" aria-selected={active===i} aria-controls="solution-workspace" tabIndex={active===i?0:-1} key={s.label} onPointerEnter={(e)=>{if(e.pointerType==='mouse')selectOnHover(i)}} onPointerLeave={cancelHover} onFocus={()=>setActive(i)} onClick={()=>setActive(i)}>{s.label}</button>)}</div><div className={styles.panel} id="solution-workspace" role="tabpanel" key={active}><SolutionContent solution={solutions[active]} id="active-solution" /></div></div>
    <div className={styles.mobileList}>{solutions.map((s,i)=>{const open=active===i; return <div className={styles.disclosure} key={s.label}><button aria-expanded={open} aria-controls={`mobile-solution-${i}`} onClick={()=>setActive(i)}><span>{s.label}</span><ChevronDown size={18}/></button><div className={styles.mobilePanel} data-open={open} id={`mobile-solution-${i}`} aria-hidden={!open}>{open&&<SolutionContent solution={s} id={`mobile-content-${i}`}/>}</div></div>})}</div>
  </div></section>;
}
