'use client';

import { useRef, useState } from 'react';
import { Check } from 'lucide-react';
import styles from './FeaturedSolutions.module.css';

type PreviewType = 'analytics' | 'support' | 'workflow' | 'research' | 'cloud';
type Solution = { label: string; title: string; summary: string; challenge: string; response: string; outcomes: string[]; technologies: string[]; previewType: PreviewType };

const solutions: Solution[] = [
  { label: 'Business Intelligence', title: 'Business Intelligence and Performance Dashboard', summary: 'A centralized analytics environment that turns fragmented operational data into clear, actionable insight.', challenge: 'Disconnected reporting, manual analysis, and inconsistent performance metrics.', response: 'Secure dashboards that consolidate data, automate reporting, and provide reliable performance indicators.', outcomes: ['Faster decision-making', 'Less manual reporting', 'Better operational visibility'], technologies: ['React', 'Next.js', 'TypeScript', 'Python', 'PostgreSQL', 'Power BI'], previewType: 'analytics' },
  { label: 'AI Customer Support', title: 'AI-Assisted Customer Support Platform', summary: 'An intelligent support environment that delivers quick answers while maintaining a clear path to human assistance.', challenge: 'Repetitive questions, disconnected knowledge, and growing request volumes slow support teams.', response: 'AI-assisted support that retrieves approved information, handles routine requests, and escalates complex cases.', outcomes: ['Faster response times', 'Less repetitive support work', 'More consistent experiences'], technologies: ['Next.js', 'Node.js', 'Python', 'OpenAI', 'PostgreSQL', 'Redis'], previewType: 'support' },
  { label: 'Workflow Automation', title: 'Internal Workflow Automation System', summary: 'A custom operational platform that replaces repetitive processes with structured, measurable digital workflows.', challenge: 'Manual approvals, spreadsheet tracking, and fragmented communication create delays and errors.', response: 'Digital workflows that automate routing, approvals, notifications, status tracking, and reporting.', outcomes: ['Fewer process delays', 'Improved operational accuracy', 'Clearer ownership'], technologies: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker', 'GitHub Actions'], previewType: 'workflow' },
  { label: 'Research Analytics', title: 'Research Data and Analytics Platform', summary: 'A secure platform for collecting, managing, analyzing, and communicating complex research information.', challenge: 'Disconnected datasets and manual analysis make research reporting difficult to maintain and scale.', response: 'Structured tools for data collection, validation, analysis, visualization, and controlled reporting.', outcomes: ['More reliable research data', 'Faster analysis and reporting', 'Better team collaboration'], technologies: ['Python', 'Django', 'PostgreSQL', 'React', 'Power BI', 'Docker'], previewType: 'research' },
  { label: 'Cloud Operations', title: 'Cloud Infrastructure and Operations Platform', summary: 'A unified operational view of digital infrastructure, deployments, reliability, and technical performance.', challenge: 'Cloud resources, deployments, and alerts spread across tools make growing systems hard to monitor.', response: 'A centralized environment for system health, deployment visibility, alerts, and infrastructure performance.', outcomes: ['Improved infrastructure visibility', 'Faster issue response', 'More reliable deployments'], technologies: ['AWS', 'Azure', 'Docker', 'GitHub Actions', 'Node.js', 'PostgreSQL'], previewType: 'cloud' },
];

const Dot = () => <span className={styles.dot} />;
function PreviewShell({ title, children }: { title: string; children: React.ReactNode }) {
  return <div className={styles.preview} aria-hidden="true"><div className={styles.previewBar}><span><Dot /> Zentric workspace</span><b>{title}</b></div>{children}</div>;
}
function Metrics({ items }: { items: [string, React.ReactNode][] }) { return <div className={styles.metrics}>{items.map(([label, value]) => <span key={label}>{label}<b>{value}</b></span>)}</div>; }
function AnalyticsPreview() { return <PreviewShell title="Performance overview"><Metrics items={[["Revenue", "£482K"], ["Operations", "128"], ["Reporting", "92%"]]} /><div className={styles.chartArea}><div><small>Performance trend</small><svg viewBox="0 0 420 90" preserveAspectRatio="none"><path d="M5 77 C65 72 75 46 130 54 S210 25 260 38 S340 8 415 16" /><line x1="0" y1="88" x2="420" y2="88" /></svg></div><DataRows items={[["Operations", "94%"], ["Delivery", "89%"], ["Quality", "97%"]]} /></div></PreviewShell>; }
function DataRows({ items }: { items: [string, string][] }) { return <div className={styles.dataRows}>{items.map(([label, value]) => <span key={label}>{label}<b>{value}</b></span>)}</div>; }
function SupportPreview() { return <PreviewShell title="Support assistant"><div className={styles.support}><div className={styles.conversation}><span className={styles.customer}>How can I update my service access?</span><span className={styles.assistant}>I found the approved guide and can walk you through it.</span></div><aside><b><Dot /> 3 sources verified</b><span>Knowledge is up to date</span><hr /><b>Human support ready</b><span>Escalation available</span></aside></div></PreviewShell>; }
function WorkflowPreview() { return <PreviewShell title="Operations workflow"><div className={styles.stages}>{['Submitted', 'Review', 'Approval', 'Complete'].map((x, i) => <span className={i === 1 ? styles.activeStage : ''} key={x}><i>{i + 1}</i>{x}</span>)}</div><div className={styles.taskList}><DataRows items={[["Validate request details", "In review"], ["Confirm department owner", "Queued"], ["Prepare approval record", "Queued"]]} /></div></PreviewShell>; }
function ResearchPreview() { return <PreviewShell title="Study reporting"><div className={styles.researchTop}><span><small>Operational study 04</small><b>2,480 records</b></span><span><small>Data quality</small><b>96.8%</b></span></div><div className={styles.distribution}>{[48, 72, 58, 90, 64, 80, 55, 68].map((height, i) => <i style={{ height: `${height}%` }} key={i} />)}</div><DataRows items={[["Validation", "Complete"], ["Analysis", "Running"], ["Report", "76%"]]} /></PreviewShell>; }
function CloudPreview() { return <PreviewShell title="Cloud operations"><Metrics items={[["System health", "Healthy"], ["Uptime", "99.98%"], ["Deployments", "12"]]} /><div className={styles.cloudRows}><DataRows items={[["API services", "Operational"], ["Data pipeline", "Operational"], ["Web deployment", "v2.8.1"]]} /><p><Dot /> Deployment completed successfully</p></div></PreviewShell>; }
function SolutionPreview({ type }: { type: PreviewType }) { return type === 'analytics' ? <AnalyticsPreview /> : type === 'support' ? <SupportPreview /> : type === 'workflow' ? <WorkflowPreview /> : type === 'research' ? <ResearchPreview /> : <CloudPreview />; }

function SolutionContent({ solution }: { solution: Solution }) {
  return <div className={styles.content}><div className={styles.copy}><header><h3>{solution.title}</h3><p>{solution.summary}</p></header><div className={styles.info}><div><h4>Challenge</h4><p>{solution.challenge}</p></div><div><h4>What we build</h4><p>{solution.response}</p></div><div><h4>Expected impact</h4>{solution.outcomes.map(x => <p className={styles.outcome} key={x}><Check size={14} />{x}</p>)}</div></div><div className={styles.technologies}><h4>Technologies</h4><p>{solution.technologies.join(' • ')}</p></div></div><SolutionPreview type={solution.previewType} /></div>;
}

export function FeaturedSolutions() {
  const [active, setActive] = useState(0);
  const tabs = useRef<Array<HTMLButtonElement | null>>([]);
  const select = (index: number) => { setActive(index); tabs.current[index]?.focus(); };
  const onKeyDown = (event: React.KeyboardEvent, index: number) => {
    if (event.key !== 'ArrowLeft' && event.key !== 'ArrowRight' && event.key !== 'Home' && event.key !== 'End') return;
    event.preventDefault();
    const next = event.key === 'Home' ? 0 : event.key === 'End' ? solutions.length - 1 : (index + (event.key === 'ArrowRight' ? 1 : -1) + solutions.length) % solutions.length;
    select(next);
  };
  return <section className={styles.section} aria-labelledby="featured-solutions-heading"><div className={styles.container}><header className={styles.sectionHeader}><p>FEATURED SOLUTIONS</p><h2 id="featured-solutions-heading">Solutions Built Around Real Business Needs</h2><span>Explore how Zentric combines software engineering, artificial intelligence, data, and cloud technologies to solve complex operational challenges.</span></header><div className={styles.selector} role="tablist" aria-label="Featured solutions">{solutions.map((solution, i) => <button ref={element => { tabs.current[i] = element; }} id={`solution-tab-${i}`} role="tab" aria-selected={active === i} aria-controls="solution-panel" tabIndex={active === i ? 0 : -1} key={solution.label} onKeyDown={event => onKeyDown(event, i)} onClick={() => setActive(i)}>{solution.label}</button>)}</div><div className={styles.panel} id="solution-panel" role="tabpanel" aria-labelledby={`solution-tab-${active}`} key={active}><SolutionContent solution={solutions[active]} /></div></div></section>;
}
