import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { cancelWorkflowAction, decideWorkflowStageAction, publishWorkflowDefinitionAction, startWorkflowAction } from "./actions";

const exampleStages = JSON.stringify([
  { key: "manager", name: "Manager review", assigneeType: "SUPERVISOR", assigneeUserIds: [], approvalMode: "ANY", dueOffsetHours: 48 },
  { key: "hr", name: "HR approval", assigneeType: "PERMISSION", assigneeUserIds: [], assigneePermissionKey: "workflow.review", approvalMode: "QUORUM", quorum: 1, routingCondition: { field: "requiresHr", operator: "EQUALS", value: true }, dueOffsetHours: 72 },
], null, 2);

export default async function WorkflowsAdminPage() {
  const auth = await requireAnyPermission(["workflow.create", "workflow.assign", "workflow.review", "workflow.override"]);
  const [definitions, employees, instances] = await Promise.all([
    prisma.hrWorkflowDefinition.findMany({ where: { organizationId: auth.user.organizationId, active: true }, orderBy: [{ key: "asc" }, { version: "desc" }] }),
    prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId, archivedAt: null }, orderBy: { lastName: "asc" } }),
    prisma.hrWorkflowInstance.findMany({ where: { organizationId: auth.user.organizationId }, include: { definition: true, stageRuns: { include: { approvals: { include: { approver: true } } }, orderBy: { sortOrder: "asc" } } }, orderBy: { startedAt: "desc" }, take: 100 }),
  ]);
  return <main><h1 className="text-3xl font-bold">Workflow engine</h1><p className="mt-2 text-slate-600">Reusable, versioned conditional approvals with exact assignees and immutable decisions.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-2">
      {auth.permissions.has("workflow.create") && <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Publish definition version</h2><form action={publishWorkflowDefinitionAction} className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-3"><input className="input" name="key" placeholder="expense-approval" required /><input className="input" name="name" placeholder="Expense approval" required /></div><div className="grid grid-cols-2 gap-3"><input className="input" name="module" placeholder="Expenses" required /><input className="input" name="subjectType" placeholder="ExpenseClaim" required /></div><textarea className="input" name="description" placeholder="Definition purpose" /><label className="text-sm font-semibold">Stages JSON<textarea className="input mt-1 min-h-80 font-mono text-xs" name="stages" defaultValue={exampleStages} required /></label><button className="btn btn-primary">Publish immutable version</button></form></section>}
      {auth.permissions.has("workflow.assign") && <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Start workflow</h2><form action={startWorkflowAction} className="mt-4 grid gap-3"><select className="input" name="definitionId" required><option value="">Definition</option>{definitions.map((definition) => <option value={definition.id} key={definition.id}>{definition.key} v{definition.version} · {definition.name}</option>)}</select><input className="input" name="subjectId" placeholder="Subject record ID" required /><select className="input" name="subjectEmployeeId"><option value="">Subject employee (required for supervisor routing)</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><label className="text-sm font-semibold">Safe routing context JSON<textarea className="input mt-1 min-h-36 font-mono text-xs" name="context" defaultValue={'{\n  "requiresHr": true\n}'} required /></label><button className="btn btn-primary">Start workflow</button></form></section>}
    </div>
    <section className="mt-6 space-y-5">{instances.length === 0 ? <div className="rounded-2xl bg-white p-6 text-slate-600">No workflow instances yet.</div> : instances.map((instance) => <article className="rounded-2xl bg-white p-5" key={instance.id}><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{instance.definition.name} · {instance.subjectType} {instance.subjectId}</h2><p className="text-sm text-slate-600">Definition {instance.definition.key} v{instance.definition.version} · started {instance.startedAt.toLocaleString()}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{instance.status}</span>{instance.status === "ACTIVE" && auth.permissions.has("workflow.override") && <form action={cancelWorkflowAction} className="flex gap-2"><input type="hidden" name="instanceId" value={instance.id} /><input className="input max-w-44" name="reason" placeholder="Cancellation reason" required /><button className="font-semibold text-red-700">Cancel</button></form>}</div></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Stage</th><th>Rule</th><th>Status</th><th>Decisions</th><th>Action</th></tr></thead><tbody>{instance.stageRuns.map((run) => <tr className="border-b last:border-0 align-top" key={run.id}><td className="py-3">{run.stageName}<br /><span className="text-xs text-slate-500">{run.dueAt ? `Due ${run.dueAt.toLocaleString()}` : "No deadline"}</span></td><td>{run.approvalMode} · {run.requiredApprovals}/{run.approverUserIds.length}</td><td>{run.status}</td><td>{run.approvals.length ? run.approvals.map((approval) => <div key={approval.id}>{approval.approver.email}: {approval.decision} — {approval.reason}</div>) : "—"}</td><td>{run.status === "ACTIVE" && (run.approverUserIds.includes(auth.user.id) || auth.permissions.has("workflow.override")) ? <form action={decideWorkflowStageAction} className="grid min-w-52 gap-2"><input type="hidden" name="stageRunId" value={run.id} /><select className="input" name="decision"><option>APPROVED</option><option>REJECTED</option></select><input className="input" name="reason" placeholder="Decision reason" required /><button className="text-left font-semibold text-teal-700">Record decision</button></form> : "—"}</td></tr>)}</tbody></table></div></article>)}</section>
  </main>;
}
