import crypto from "node:crypto";
import { CalendarDays, CheckCircle2, Clock3, Users } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { applyWorkforceEventAction, approveWorkforceEventAction, attachWorkforceWorkflowAction, createWorkforceEventAction } from "./actions";

const eventTypes = ["PROMOTION","TRANSFER","POSITION_CHANGE","DEPARTMENT_CHANGE","TEAM_CHANGE","MANAGER_CHANGE","LOCATION_CHANGE","LEGAL_ENTITY_TRANSFER","GRADE_CHANGE","JOB_CHANGE","EMPLOYMENT_TYPE_CHANGE","WORK_ARRANGEMENT_CHANGE","CONTRACT_CHANGE","PROBATION_CONFIRMATION","PROBATION_EXTENSION"];
export default async function WorkforceEventsPage() {
  const auth = await requirePermission("workforce_event.create"); const organizationId = auth.user.organizationId;
  const [events, employees, positions, departments, teams, locations, legalEntities, grades, jobProfiles, workflows] = await Promise.all([
    prisma.hrWorkforceEvent.findMany({ where: { organizationId }, include: { employee: true, executionAttempts: true }, orderBy: { createdAt: "desc" }, take: 100 }),
    prisma.hrEmployee.findMany({ where: { organizationId, employmentStatus: { notIn: ["TERMINATED", "ARCHIVED"] } }, orderBy: [{ legalFirstName: "asc" }, { lastName: "asc" }] }),
    prisma.hrPosition.findMany({ where: { organizationId, status: "ACTIVE" }, include: { department: true }, orderBy: { title: "asc" } }), prisma.hrDepartment.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.hrTeam.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.hrLocation.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.hrLegalEntity.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.hrGrade.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }), prisma.hrJobProfile.findMany({ where: { organizationId, status: "ACTIVE" }, orderBy: { title: "asc" } }), prisma.hrWorkflowInstance.findMany({ where: { organizationId, subjectType: "HrWorkforceEvent" }, orderBy: { startedAt: "desc" }, take: 100 })
  ]);
  const applied = events.filter((event) => event.status === "APPLIED").length;
  const pending = events.filter((event) => !["APPLIED", "CANCELLED", "REJECTED"].includes(event.status)).length;
  return <><h1 className="text-3xl font-bold">Workforce events</h1><p className="mt-2 text-slate-600">One effective-dated register for promotions, transfers, manager changes, position and employment changes.</p>
    <div className="hr-grid-4">{[{label:"Total events",value:events.length,icon:Users},{label:"Applied",value:applied,icon:CheckCircle2},{label:"Pending",value:pending,icon:Clock3},{label:"As of today",value:new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date()),icon:CalendarDays}].map(({label,value,icon:Icon}) => <article className="hr-card hr-stat" key={label}><span className="hr-icon"><Icon /></span><span><strong>{value}</strong><p>{label}</p></span></article>)}</div>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create and submit governed event</h2><form action={createWorkforceEventAction} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="idempotencyKey" value={crypto.randomUUID()} />
      <select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((e) => <option value={e.id} key={e.id}>{e.employeeNumber} — {e.legalFirstName} {e.lastName}</option>)}</select><select className="input" name="type">{eventTypes.map((type) => <option key={type}>{type}</option>)}</select><input className="input" name="requestedEffectiveAt" type="date" required />
      <select className="input" name="positionId"><option value="">Position unchanged</option>{positions.map((p) => <option value={p.id} key={p.id}>{p.department.name} — {p.title}</option>)}</select><select className="input" name="departmentId"><option value="">Department unchanged</option>{departments.map((d) => <option value={d.id} key={d.id}>{d.name}</option>)}</select><select className="input" name="teamId"><option value="">Team unchanged</option>{teams.map((t) => <option value={t.id} key={t.id}>{t.name}</option>)}</select>
      <select className="input" name="managerEmployeeId"><option value="">Manager unchanged</option>{employees.map((e) => <option value={e.id} key={e.id}>{e.legalFirstName} {e.lastName}</option>)}</select><select className="input" name="locationId"><option value="">Location unchanged</option>{locations.map((l) => <option value={l.id} key={l.id}>{l.name}</option>)}</select><select className="input" name="legalEntityId"><option value="">Legal entity unchanged</option>{legalEntities.map((l) => <option value={l.id} key={l.id}>{l.name}</option>)}</select>
      <select className="input" name="gradeId"><option value="">Grade unchanged</option>{grades.map((g) => <option value={g.id} key={g.id}>{g.name}</option>)}</select><select className="input" name="jobProfileId"><option value="">Job profile unchanged</option>{jobProfiles.map((j) => <option value={j.id} key={j.id}>{j.title}</option>)}</select><select className="input" name="employmentType"><option value="">Employment type unchanged</option>{["FULL_TIME","PART_TIME","CONTRACT","INTERN","TEMPORARY","CONSULTANT"].map((v) => <option key={v}>{v}</option>)}</select><select className="input" name="workMode"><option value="">Work mode unchanged</option><option>ONSITE</option><option>HYBRID</option><option>REMOTE</option></select><input className="input md:col-span-2" name="reason" placeholder="Business reason" required/><button className="btn btn-primary">Create and submit</button>
    </form></section>
    <section className="mt-6 space-y-4"><h2 className="text-xl font-bold">Event register</h2>{events.map((event) => { const workflow = workflows.find((item) => item.subjectId === event.id); return <article className="rounded-2xl bg-white p-5" key={event.id}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-bold">{event.reference} · {event.type.replaceAll("_", " ")}</h3><p className="text-sm text-slate-600">{event.employee.legalFirstName} {event.employee.lastName} · effective {event.requestedEffectiveAt.toLocaleDateString()} · v{event.version}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-800">{event.status.replaceAll("_", " ")}</span></div><p className="mt-3 text-sm">{event.reason}</p><details className="mt-3 rounded border border-slate-200 p-3"><summary className="cursor-pointer text-sm font-semibold text-teal-700">View proposed changes</summary><pre className="mt-3 overflow-auto p-3 text-xs">{JSON.stringify(event.proposedSnapshot, null, 2)}</pre></details>
      {event.status === "SUBMITTED" && workflow ? <form action={attachWorkforceWorkflowAction} className="mt-3"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="expectedVersion" value={event.version}/><input type="hidden" name="workflowInstanceId" value={workflow.id}/><button className="btn btn-secondary">Attach workflow ({workflow.status})</button></form> : null}
      {event.status === "SUBMITTED" && !workflow ? <a className="btn btn-secondary mt-3 inline-flex" href={`/hr/admin/workforce-events/${event.id}/review`}>Start governed review</a> : null}
      {event.status === "UNDER_REVIEW" && workflow?.status === "APPROVED" ? <form action={approveWorkforceEventAction} className="mt-3 flex gap-2"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="expectedVersion" value={event.version}/><input className="input" name="reason" placeholder="Approval reason" required/><button className="btn btn-primary">Record approval</button></form> : null}
      {["APPROVED","SCHEDULED","FAILED"].includes(event.status) ? <form action={applyWorkforceEventAction} className="mt-3"><input type="hidden" name="eventId" value={event.id}/><button className="btn btn-primary">Apply if effective</button></form> : null}<p className="mt-3 text-xs text-slate-500">Workflow: {workflow?.status ?? "not attached"} · attempts: {event.executionAttempts.length}</p></article>; })}</section></>;
}
