import Link from "next/link";
import { BriefcaseBusiness, Search, UserPlus, Users } from "lucide-react";
import type { HrEmploymentStatus, Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";

const statuses: HrEmploymentStatus[] = ["DRAFT", "ACTIVE", "ON_LEAVE", "SUSPENDED", "TERMINATED", "ARCHIVED"];
export default async function EmployeesPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string; page?: string }> }) {
  const auth = await requirePermission("employee.read_all"); const params = await searchParams; const q = params.q?.trim().slice(0, 100) ?? ""; const status = statuses.includes(params.status as HrEmploymentStatus) ? params.status as HrEmploymentStatus : undefined; const page = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1); const perPage = 50;
  const where: Prisma.HrEmployeeWhereInput = { organizationId: auth.user.organizationId, ...(status ? { employmentStatus: status } : {}), ...(q ? { OR: [{ employeeNumber: { contains: q, mode: "insensitive" } }, { legalFirstName: { contains: q, mode: "insensitive" } }, { lastName: { contains: q, mode: "insensitive" } }, { companyEmail: { contains: q, mode: "insensitive" } }] } : {}) };
  const [employees, total, activeCount, leaveCount, draftCount] = await Promise.all([
    prisma.hrEmployee.findMany({ where, include: { employmentAssignments: { where: { status: "ACTIVE", OR: [{ effectiveTo: null }, { effectiveTo: { gt: new Date() } }] }, include: { department: true, position: true, team: true }, orderBy: { effectiveFrom: "desc" }, take: 1 } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }], skip: (page - 1) * perPage, take: perPage }), prisma.hrEmployee.count({ where }), prisma.hrEmployee.count({ where: { organizationId: auth.user.organizationId, employmentStatus: "ACTIVE" } }), prisma.hrEmployee.count({ where: { organizationId: auth.user.organizationId, employmentStatus: "ON_LEAVE" } }), prisma.hrEmployee.count({ where: { organizationId: auth.user.organizationId, employmentStatus: "DRAFT" } }),
  ]);
  const pages = Math.max(1, Math.ceil(total / perPage)); const pageHref = (target: number) => `?${new URLSearchParams({ ...(q ? { q } : {}), ...(status ? { status } : {}), page: String(target) })}`;
  const stats = [{ label: "Matching employees", value: total, icon: Users }, { label: "Active employees", value: activeCount, icon: BriefcaseBusiness }, { label: "On leave", value: leaveCount, icon: Users }, { label: "Draft records", value: draftCount, icon: UserPlus }];
  return <main><div className="hr-page-heading"><div><h1 className="hr-page-title">Employees</h1><p className="hr-page-subtitle">Complete employee records with effective-dated organization assignments.</p></div>{auth.permissions.has("employee.create") && <Link className="btn btn-primary" href="/hr/admin/employees/new"><UserPlus size={16}/> Provision employee</Link>}</div>
    <div className="hr-grid-4">{stats.map(({ label, value, icon: Icon }) => <article className="hr-card hr-stat" key={label}><span className="hr-icon"><Icon /></span><div><strong>{value}</strong><p>{label}</p></div></article>)}</div>
    <form className="hr-card hr-filterbar"><label><Search size={17}/><input name="q" defaultValue={q} placeholder="Search name, number, or company email" /></label><select className="input" name="status" defaultValue={status ?? ""} aria-label="Employment status"><option value="">All statuses</option>{statuses.map(value => <option key={value}>{value}</option>)}</select><button className="btn btn-secondary">Apply filters</button>{(q || status) && <Link className="btn btn-quiet" href="/hr/admin/employees">Clear</Link>}</form>
    {auth.permissions.has("employee.create") && <section className="hr-card hr-callout"><span className="hr-icon"><UserPlus /></span><div><h2>Provision an employee</h2><p>Create the personnel record, assignment, manager, compensation, payroll details, access, and onboarding through one controlled workflow.</p></div><Link className="btn btn-primary" href="/hr/admin/employees/new">Start provisioning wizard</Link></section>}
    <section className="hr-card hr-register"><div className="hr-register-heading"><div><h2>Employee directory</h2><p>Current contact, assignment, position, and employment status.</p></div><span>{total} records</span></div><div className="hr-table-wrap"><table><thead><tr><th>Employee</th><th>Number</th><th>Contact</th><th>Department</th><th>Position</th><th>Assignment</th><th>Status</th><th></th></tr></thead><tbody>{employees.map(employee => { const assignment = employee.employmentAssignments[0]; return <tr key={employee.id}><td><Link className="hr-person" href={`/hr/admin/employees/${employee.id}`}><span>{employee.legalFirstName[0]}{employee.lastName[0]}</span><strong>{employee.legalFirstName} {employee.middleName} {employee.lastName}</strong></Link></td><td><code>{employee.employeeNumber}</code></td><td><strong>{employee.companyEmail ?? "No company email"}</strong><small>{employee.phone ?? "No phone"}</small></td><td>{assignment?.department.name ?? "Unassigned"}</td><td>{assignment?.position.title ?? "Unassigned"}</td><td>{assignment ? <><strong>{assignment.team?.name ?? "No team"}</strong><small>From {assignment.effectiveFrom.toLocaleDateString()}</small></> : "No active assignment"}</td><td><span className={`hr-status ${employee.employmentStatus === "ACTIVE" ? "success" : "neutral"}`}>{employee.employmentStatus.replaceAll("_", " ")}</span></td><td><Link className="hr-link" href={`/hr/admin/employees/${employee.id}`}>View</Link></td></tr>; })}</tbody></table></div>{!employees.length && <p className="hr-empty">No employees match these filters.</p>}</section>
    <nav aria-label="Employee pages" className="hr-pagination"><span>Showing page {Math.min(page, pages)} of {pages} · {total} records</span><div>{page > 1 && <Link className="btn btn-secondary" href={pageHref(page - 1)}>Previous</Link>}{page < pages && <Link className="btn btn-secondary" href={pageHref(page + 1)}>Next</Link>}</div></nav>
  </main>;
}
