import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { createEmployeeAction } from "./actions";

export default async function EmployeesPage() {
  const auth = await requirePermission("employee.read_all");
  const employees = await prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId }, include: { employmentAssignments: { where: { status: "ACTIVE", OR: [{ effectiveTo: null }, { effectiveTo: { gt: new Date() } }] }, include: { department: true, position: true }, orderBy: { effectiveFrom: "desc" }, take: 1 } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }] });
  return <><h1 className="text-3xl font-bold">Employees</h1><p className="mt-2 text-slate-600">Complete employee records with effective-dated organization assignments.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create employee</h2><form action={createEmployeeAction} className="mt-4 grid gap-3 md:grid-cols-4"><input className="input" name="employeeNumber" placeholder="Employee number" required /><input className="input" name="legalFirstName" placeholder="Legal first name" required /><input className="input" name="middleName" placeholder="Middle name" /><input className="input" name="lastName" placeholder="Last name" required /><input className="input" name="preferredName" placeholder="Preferred name" /><input className="input" name="companyEmail" type="email" placeholder="Company email" /><input className="input" name="personalEmail" type="email" placeholder="Personal email" /><input className="input" name="phone" placeholder="Phone" /><input className="input" name="hireDate" type="date" required /><select className="input" name="employmentStatus" defaultValue="ACTIVE"><option>ACTIVE</option><option>DRAFT</option><option>ON_LEAVE</option><option>SUSPENDED</option><option>TERMINATED</option></select><button className="btn btn-primary md:col-span-2">Create employee</button></form></section>
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Employee</th><th className="p-4">Number</th><th className="p-4">Contact</th><th className="p-4">Department</th><th className="p-4">Position</th><th className="p-4">Status</th></tr></thead><tbody>{employees.map((employee) => { const assignment = employee.employmentAssignments[0]; return <tr className="border-b last:border-0" key={employee.id}><td className="p-4"><Link className="font-semibold text-teal-700 underline-offset-2 hover:underline" href={`/hr/admin/employees/${employee.id}`}>{employee.legalFirstName} {employee.middleName} {employee.lastName}</Link></td><td className="p-4 font-mono">{employee.employeeNumber}</td><td className="p-4"><p>{employee.companyEmail ?? "No company email"}</p><p className="text-slate-500">{employee.phone ?? "No phone"}</p></td><td className="p-4">{assignment?.department.name ?? "Unassigned"}</td><td className="p-4">{assignment?.position.title ?? "Unassigned"}</td><td className="p-4">{employee.employmentStatus}</td></tr>; })}</tbody></table>{!employees.length ? <p className="p-6 text-slate-500">No employees yet.</p> : null}</div></>;
}
