import { prisma } from "@/lib/prisma";
import { requireAuthenticatedUser } from "@/lib/hr/permissions/authorize";
import { requestProfileChangeAction, updateSelfProfileAction } from "./actions";

export default async function EmployeeProfilePage() {
  const auth = await requireAuthenticatedUser();
  if (!auth.user.employee) throw new Error("An employee profile is required.");
  const employee = await prisma.hrEmployee.findFirstOrThrow({
    where: { id: auth.user.employee.id, organizationId: auth.user.organizationId },
    include: {
      addresses: { orderBy: [{ isPrimary: "desc" }, { createdAt: "desc" }] },
      emergencyContacts: { orderBy: [{ isPrimary: "desc" }, { createdAt: "desc" }] },
      employmentAssignments: { include: { department: true, team: true, position: true }, orderBy: { effectiveFrom: "desc" } },
      bankAccounts: { where: { isPrimary: true }, take: 1 },
      assignedToAssignments: { where: { status: "ACTIVE" }, include: { supervisorEmployee: true }, take: 1 },
      workRelationships: { orderBy: { startedAt: "desc" } },
      workforceEvents: { orderBy: { createdAt: "desc" }, take: 20 },
      profileChangeRequests: { orderBy: { createdAt: "desc" }, take: 20 },
      statusHistory: { orderBy: { effectiveAt: "desc" } },
    },
  });
  const current = employee.employmentAssignments.find(({ status }) => status === "ACTIVE") ?? employee.employmentAssignments[0];
  return <main><h1 className="text-3xl font-bold">My profile</h1><p className="mt-2 text-slate-600">Your complete employment record and self-service contact details.</p>
    <div className="mt-6 grid gap-5 lg:grid-cols-2">
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Identity and employment</h2><dl className="mt-4 grid grid-cols-[minmax(8rem,auto)_1fr] gap-x-4 gap-y-2 text-sm"><dt>Employee number</dt><dd>{employee.employeeNumber}</dd><dt>Legal name</dt><dd>{employee.legalFirstName} {employee.middleName} {employee.lastName}</dd><dt>Company email</dt><dd className="break-all">{employee.companyEmail ?? "—"}</dd><dt>Status</dt><dd>{employee.employmentStatus}</dd><dt>Hire date</dt><dd>{employee.hireDate?.toLocaleDateString() ?? "—"}</dd><dt>Department</dt><dd>{current?.department.name ?? "—"}</dd><dt>Team</dt><dd>{current?.team?.name ?? "—"}</dd><dt>Position</dt><dd>{current?.position.title ?? "—"}</dd><dt>Location</dt><dd>{current?.location ?? "—"}</dd><dt>Supervisor</dt><dd>{employee.assignedToAssignments[0] ? `${employee.assignedToAssignments[0].supervisorEmployee.legalFirstName} ${employee.assignedToAssignments[0].supervisorEmployee.lastName}` : "—"}</dd></dl></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Contact details</h2><form action={updateSelfProfileAction} className="mt-4 grid gap-3"><label className="text-sm font-semibold">Preferred name<input className="input mt-1" name="preferredName" defaultValue={employee.preferredName ?? ""} /></label><label className="text-sm font-semibold">Personal email<input className="input mt-1" name="personalEmail" type="email" defaultValue={employee.personalEmail ?? ""} /></label><label className="text-sm font-semibold">Preferred notification email<input className="input mt-1" name="preferredNotificationEmail" type="email" defaultValue={employee.preferredNotificationEmail ?? ""} /></label><label className="text-sm font-semibold">Phone<input className="input mt-1" name="phone" defaultValue={employee.phone ?? ""} /></label><button className="btn btn-primary">Save contact details</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Request a protected change</h2><p className="mt-2 text-sm text-slate-600">Identity, address, bank, tax, and work-authorization changes require independent review and do not overwrite your current record.</p><form action={requestProfileChangeAction} className="mt-4 grid gap-3"><input type="hidden" name="expectedEmployeeUpdatedAt" value={employee.updatedAt.toISOString()} /><label className="text-sm font-semibold">Change type<select className="input mt-1" name="fieldKey"><option value="address">Address</option><option value="legalName">Legal name</option><option value="dateOfBirth">Date of birth</option><option value="nationalIdentifier">National identifier</option><option value="workAuthorization">Work authorization</option><option value="bankAccount">Bank account</option><option value="taxProfile">Tax profile</option></select></label><label className="text-sm font-semibold">Proposed value<textarea className="input mt-1" name="proposedValue" required /></label><label className="text-sm font-semibold">Exact supporting document version ID<input className="input mt-1" name="evidenceVersionId" required /></label><label className="text-sm font-semibold">Requested effective date<input className="input mt-1" name="effectiveAt" type="date" /></label><button className="btn btn-primary">Submit for review</button></form></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Addresses</h2><div className="mt-3 space-y-3 text-sm">{employee.addresses.map((address) => <address className="not-italic" key={address.id}><strong>{address.type}{address.isPrimary ? " · Primary" : ""}</strong><br />{address.line1}{address.line2 ? <><br />{address.line2}</> : null}<br />{address.city}{address.state ? `, ${address.state}` : ""} {address.postalCode}<br />{address.country}</address>)}{!employee.addresses.length && <p className="text-slate-500">No address recorded.</p>}</div></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="font-bold">Emergency contacts and payment account</h2><div className="mt-3 space-y-3 text-sm">{employee.emergencyContacts.map((contact) => <p key={contact.id}><strong>{contact.fullName}</strong> · {contact.relationship}<br />{contact.phone}{contact.email ? ` · ${contact.email}` : ""}</p>)}{!employee.emergencyContacts.length && <p className="text-slate-500">No emergency contact recorded.</p>}<hr /><p><strong>Primary bank account:</strong> {employee.bankAccounts[0] ? `${employee.bankAccounts[0].bankName} · ending ${employee.bankAccounts[0].accountNumberLastFour}` : "Not recorded"}</p><p className="text-xs text-slate-500">Full banking credentials are restricted to authorized payroll administrators.</p></div></section>
    </div>
    <section className="mt-5 rounded-2xl bg-white p-5"><h2 className="font-bold">My governed requests</h2><div className="mt-4 space-y-3">{employee.profileChangeRequests.map((request) => <article className="rounded-xl border p-4 text-sm" key={request.id}><p className="font-semibold">{request.fieldKey} · {request.status}</p><p className="mt-1 text-slate-600">Version {request.version} · Submitted {request.submittedAt?.toLocaleString() ?? "Draft"}</p>{request.reviewReason ? <p className="mt-2">Decision note: {request.reviewReason}</p> : null}</article>)}{!employee.profileChangeRequests.length ? <p className="text-sm text-slate-500">No profile change requests.</p> : null}</div></section>
    <section className="mt-5 rounded-2xl bg-white p-5"><h2 className="font-bold">Employment timeline</h2><ol className="mt-4 border-l-2 border-slate-200 pl-5">{[
      ...employee.statusHistory.map((item) => ({ id: `status-${item.id}`, at: item.effectiveAt, title: item.newStatus, detail: item.reason })),
      ...employee.workforceEvents.map((event) => ({ id: `event-${event.id}`, at: event.appliedAt ?? event.requestedEffectiveAt, title: event.type, detail: `${event.status} · ${event.reason}` })),
    ].sort((a, b) => b.at.getTime() - a.at.getTime()).map((item) => <li className="relative mb-5 text-sm" key={item.id}><span className="absolute -left-[1.7rem] top-1 h-3 w-3 rounded-full bg-indigo-600" /><p className="font-semibold">{item.title}</p><p className="text-slate-600">{item.at.toLocaleDateString()} · {item.detail}</p></li>)}</ol></section>
  </main>;
}
