import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { initializePerformanceFrameworkAction } from "./actions";

export default async function PerformanceAdministrationPage() {
  const auth = await requirePermission("performance.framework.manage");
  const [levels, tracks, functions, profiles, competencies, scales, templates, cycles, calibration, promotionCases, jobs] = await Promise.all([
    prisma.hrCompanyLevel.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrCareerTrack.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrJobFunction.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrJobProfileVersion.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrCompetency.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrRatingScale.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrReviewTemplate.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrPerformanceCycle.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrCalibrationSession.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrPromotionCase.count({ where: { organizationId: auth.user.organizationId } }), prisma.hrPerformanceJobRun.findMany({ where: { organizationId: auth.user.organizationId }, orderBy: { startedAt: "desc" }, take: 10 }),
  ]);
  const cards = [["Levels", levels], ["Career tracks", tracks], ["Job functions", functions], ["Job-profile versions", profiles], ["Competencies", competencies], ["Rating scales", scales], ["Review templates", templates], ["Cycles", cycles], ["Calibration sessions", calibration], ["Promotion cases", promotionCases]] as const;
  return <><h1 className="text-3xl font-bold">Performance &amp; career administration</h1><p className="mt-2 text-slate-600">Versioned frameworks, review cycles, calibration, development, and governed promotion cases.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <article className="rounded-2xl bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</div><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Locked company framework defaults</h2><p className="mt-2 text-sm text-slate-600">Initializes Z1–Z8, Individual Contributor and People Manager tracks, and the five descriptive rating categories. Published versions remain immutable.</p><form action={initializePerformanceFrameworkAction} className="mt-4"><button className="btn btn-primary">Initialize missing defaults</button></form></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Performance worker evidence</h2><div className="mt-3 space-y-2">{jobs.length ? jobs.map((job) => <p className="rounded-xl border p-3 text-sm" key={job.id}>{job.jobType} · {job.windowKey} · {job.status} · attempt {job.attemptCount}</p>) : <p className="text-sm text-slate-600">No Unit 7 worker run recorded yet.</p>}</div></section></>;
}
