import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { createPerformanceCycleAction, initializePerformanceFrameworkAction, openPerformanceCycleAction } from "./actions";

export default async function PerformanceAdministrationPage() {
  const auth = await requirePermission("performance.framework.manage");
  const organizationId = auth.user.organizationId;
  const [levels, tracks, functions, profiles, competencies, scales, templateCount, cycles, calibration, promotionCases, jobs, templates] = await Promise.all([
    prisma.hrCompanyLevel.count({ where: { organizationId } }), prisma.hrCareerTrack.count({ where: { organizationId } }), prisma.hrJobFunction.count({ where: { organizationId } }), prisma.hrJobProfileVersion.count({ where: { organizationId } }), prisma.hrCompetency.count({ where: { organizationId } }), prisma.hrRatingScale.count({ where: { organizationId } }), prisma.hrReviewTemplate.count({ where: { organizationId } }), prisma.hrPerformanceCycle.findMany({ where: { organizationId }, orderBy: { startsAt: "desc" }, take: 50 }), prisma.hrCalibrationSession.count({ where: { organizationId } }), prisma.hrPromotionCase.count({ where: { organizationId } }), prisma.hrPerformanceJobRun.findMany({ where: { organizationId }, orderBy: { startedAt: "desc" }, take: 10 }), prisma.hrReviewTemplateVersion.findMany({ where: { organizationId, status: "PUBLISHED" }, orderBy: { publishedAt: "desc" } }),
  ]);
  const reviewCounts = new Map((await prisma.hrPerformanceReview.groupBy({ by: ["cycleId"], where: { organizationId, cycleId: { in: cycles.map(({ id }) => id) } }, _count: { _all: true } })).map((item) => [item.cycleId, item._count._all]));
  const cards = [["Levels", levels], ["Career tracks", tracks], ["Job functions", functions], ["Job-profile versions", profiles], ["Competencies", competencies], ["Rating scales", scales], ["Review templates", templateCount], ["Cycles", cycles.length], ["Calibration sessions", calibration], ["Promotion cases", promotionCases]] as const;
  return <><h1 className="text-3xl font-bold">Performance &amp; career administration</h1><p className="mt-2 text-slate-600">Versioned frameworks, review cycles, calibration, development, and governed promotion cases.</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <article className="rounded-2xl bg-white p-5" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></article>)}</div>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Locked company framework defaults</h2><p className="mt-2 text-sm text-slate-600">Initializes Z1–Z8, Individual Contributor and People Manager tracks, legacy job-profile versions, the standard review template, and five descriptive rating categories. Published versions remain immutable.</p><form action={initializePerformanceFrameworkAction} className="mt-4"><button className="btn btn-primary">Initialize missing defaults</button></form></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create review cycle</h2>{templates.length ? <form action={createPerformanceCycleAction} className="mt-4 grid gap-3 md:grid-cols-3"><input className="input" name="code" placeholder="Unique cycle code" required/><input className="input" name="name" placeholder="Cycle name" required/><select className="input" name="cycleType"><option value="ANNUAL">Annual</option><option value="MID_YEAR">Mid-year</option><option value="PROBATION">Probation</option><option value="AD_HOC">Ad hoc</option><option value="PROMOTION">Promotion-focused</option></select><input className="input" name="startsAt" type="date" required/><input className="input" name="endsAt" type="date" required/><select className="input" name="reviewTemplateVersionId" required>{templates.map((template) => <option value={template.id} key={template.id}>Template v{template.version}</option>)}</select><button className="btn btn-primary md:col-span-3">Create cycle</button></form> : <p className="mt-3 text-sm text-amber-800">Initialize the governed defaults before creating a cycle.</p>}</section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Cycle register</h2><div className="mt-4 space-y-3">{cycles.map((cycle) => { const reviewCount = reviewCounts.get(cycle.id) ?? 0; return <article className="rounded-xl border p-4" key={cycle.id}><p><strong>{cycle.name}</strong> · {cycle.cycleType} · {cycle.status} · v{cycle.version}</p><p className="mt-1 text-sm text-slate-600">{cycle.startsAt.toLocaleDateString()} – {cycle.endsAt.toLocaleDateString()} · {reviewCount} snapshotted review{reviewCount === 1 ? "" : "s"}</p>{cycle.status === "DRAFT" && <form action={openPerformanceCycleAction} className="mt-3"><input type="hidden" name="cycleId" value={cycle.id}/><input type="hidden" name="expectedVersion" value={cycle.version}/><button className="btn btn-primary">Open self-review and snapshot population</button></form>}</article>; })}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Performance worker evidence</h2><div className="mt-3 space-y-2">{jobs.length ? jobs.map((job) => <p className="rounded-xl border p-3 text-sm" key={job.id}>{job.jobType} · {job.windowKey} · {job.status} · attempt {job.attemptCount}</p>) : <p className="text-sm text-slate-600">No Unit 7 worker run recorded yet.</p>}</div></section>
  </>;
}
