import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { unsealHrCredential } from "@/lib/hr/auth/crypto";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { saveEmployeeBankAccountAction } from "../actions";

export default async function EmployeeProfilePage({ params }: { params: Promise<{ id: string }> }) {
  const auth = await requirePermission("employee.read_all");
  const { id } = await params;
  const employee = await prisma.hrEmployee.findFirst({ where: { id, organizationId: auth.user.organizationId }, include: { addresses: true, emergencyContacts: true, identifiers: true, bankAccounts: { orderBy: [{ isPrimary: "desc" }, { createdAt: "desc" }] }, taxProfile: true, employmentAssignments: { include: { department: true, team: true, position: true }, orderBy: { effectiveFrom: "desc" } }, supervisedAssignments: { include: { assignedEmployee: true }, orderBy: { effectiveFrom: "desc" } } } });
  if (!employee) notFound();
  const mayReadBank = auth.permissions.has("payroll.read_bank_details");
  return <><h1 className="text-3xl font-bold">{employee.legalFirstName} {employee.middleName} {employee.lastName}</h1><p className="mt-2 font-mono text-slate-600">{employee.employeeNumber}</p>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Personal and employment information</h2><dl className="mt-4 grid grid-cols-[minmax(9rem,auto)_1fr] gap-x-4 gap-y-3 text-sm"><dt className="font-semibold">Preferred name</dt><dd>{employee.preferredName ?? "—"}</dd><dt className="font-semibold">Company email</dt><dd className="break-all">{employee.companyEmail ?? "—"}</dd><dt className="font-semibold">Personal email</dt><dd className="break-all">{employee.personalEmail ?? "—"}</dd><dt className="font-semibold">Phone</dt><dd>{employee.phone ?? "—"}</dd><dt className="font-semibold">Hire date</dt><dd>{employee.hireDate?.toLocaleDateString() ?? "—"}</dd><dt className="font-semibold">Status</dt><dd>{employee.employmentStatus}</dd></dl></section>
      <section className="rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Bank details</h2>{mayReadBank ? <>{employee.bankAccounts.map((account) => <dl className="mt-4 grid grid-cols-[minmax(9rem,auto)_1fr] gap-x-4 gap-y-3 text-sm" key={account.id}><dt className="font-semibold">Bank</dt><dd>{account.bankName}</dd><dt className="font-semibold">Account name</dt><dd>{account.accountName}</dd><dt className="font-semibold">Account number</dt><dd className="break-all font-mono">{unsealHrCredential(account.accountNumberEncrypted)}</dd><dt className="font-semibold">Currency</dt><dd>{account.currency}</dd></dl>)}<form action={saveEmployeeBankAccountAction} className="mt-5 grid gap-3"><input type="hidden" name="employeeId" value={employee.id} /><input className="input" name="bankName" placeholder="Bank name" required /><input className="input" name="accountName" placeholder="Account name" required /><input className="input" name="accountNumber" autoComplete="off" placeholder="Full account number" required /><input className="input" name="currency" defaultValue="NGN" maxLength={3} required /><button className="btn btn-primary">Save new primary account</button></form></> : <p className="mt-3 text-sm text-slate-600">Bank details require payroll banking permission.</p>}</section>
    </div>
    <section className="mt-5 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="text-lg font-bold">Assignment history</h2><table className="mt-4 w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Effective</th><th>Department</th><th>Team</th><th>Position</th><th>Type</th><th>Status</th><th>Reason</th></tr></thead><tbody>{employee.employmentAssignments.map((assignment) => <tr className="border-b last:border-0" key={assignment.id}><td className="py-3">{assignment.effectiveFrom.toLocaleDateString()} – {assignment.effectiveTo?.toLocaleDateString() ?? "Current"}</td><td>{assignment.department.name}</td><td>{assignment.team?.name ?? "—"}</td><td>{assignment.position.title}</td><td>{assignment.employmentType}</td><td>{assignment.status}</td><td>{assignment.reason}</td></tr>)}</tbody></table>{!employee.employmentAssignments.length ? <p className="mt-3 text-slate-500">No assignment history yet.</p> : null}</section></>;
}
