'use client';

import { useActionState, useState } from 'react';
import { countryPhoneOptions } from '@/lib/phone';
import { roleAppliedForOptions } from '@/lib/recruitment-options';
import { employmentTypeOptions, genderOptions, rightToWorkOptions, stage1WorkModeOptions, yesNoOptions } from '@/lib/stage1-fields';
import { submitStage1Application } from './actions';
import { initialStage1FormState, type Stage1Field, type Stage1FormState } from './form-state';

const uploadAccept = ['.pdf','.doc','.docx','.jpg','.jpeg','.png','.webp','image/jpeg','image/png','image/webp','application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/octet-stream'].join(',');
function errorFor(state: Stage1FormState, field: Stage1Field) { return state.fieldErrors[field]; }
function inputClass(state: Stage1FormState, field: Stage1Field) { return `input ${errorFor(state, field) ? 'border-red-400 bg-red-50/40' : ''}`; }
function FieldError({ state, field }: { state: Stage1FormState; field: Stage1Field }) { const error = errorFor(state, field); return error ? <p className="min-w-0 break-words text-sm font-medium text-red-700">{error}</p> : null; }
function Required() { return <span className="text-red-600" aria-label="required">*</span>; }
function FormSection({ number, title, helper, children }: { number: string; title: string; helper: string; children: React.ReactNode }) { return <section className="w-full min-w-0 overflow-hidden rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5 md:p-7"><div className="mb-6 flex min-w-0 gap-3 border-b border-slate-100 pb-5"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand text-sm font-bold text-white">{number}</span><div className="min-w-0"><h2 className="min-w-0 break-words text-xl font-bold text-ink">{title}</h2><p className="mt-1 min-w-0 break-words text-sm leading-6 text-slate-600">{helper}</p></div></div><div className="grid min-w-0 grid-cols-1 gap-4 md:grid-cols-12 md:gap-5">{children}</div></section>; }
function SelectField({ state, name, label, options, required = true, span = 'md:col-span-4' }: { state: Stage1FormState; name: Stage1Field; label: string; options: readonly string[]; required?: boolean; span?: string }) { return <label className={`field ${span}`}>{label} {required ? <Required /> : null}<select className={inputClass(state, name)} name={name} required={required} defaultValue={state.values[name] || options[0]}>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select><FieldError state={state} field={name} /></label>; }

export function Stage1ApplicationForm() {
  const [state, formAction, pending] = useActionState(submitStage1Application, initialStage1FormState);
  const [selectedFile, setSelectedFile] = useState('');
  const values = state.values; const selectedRole = values.role || roleAppliedForOptions[0]; const otherRoleIsSelected = selectedRole === 'Other';
  return <form action={formAction} className="w-full min-w-0 space-y-6">
    {/* Stage 1 PDF field keys: name="firstName" name="middleInitial" name="lastName" name="preferredName" name="residentialAddress" name="email" name="phoneCountryIso" name="phoneNational" name="stateOfResidence" name="lgaOfResidence" name="nationality" name="rightToWorkNigeria" name="genderForHr" name="role" name="otherRole" name="employmentType" name="workMode" name="availableStartDate" name="noticePeriod" name="salaryExpectation" name="salaryNegotiable" name="canWorkMondayFriday" name="preferredWorkingTime" name="heardAboutUs" name="cv" name="portfolioAvailable" name="certificatesAvailable" name="certificatesNote" name="otherDocumentNote" name="educationHistory" name="skills" name="portfolioUrl" name="employmentHistory" name="referee1Name" name="referee1CompanyRole" name="referee1Relationship" name="referee1Phone" name="referee1Email" name="referee1MayContact" name="referee2Name" name="referee2CompanyRole" name="referee2Relationship" name="referee2Phone" name="referee2Email" name="referee2MayContact" name="declarationAccuracy" name="privacyConsent" name="signatureName" name="signatureConsent" */}

    {state.message ? <div className="min-w-0 break-words rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-800" role="alert">{state.message}</div> : null}
    <FormSection number="1" title="Candidate Details" helper="These fields match the applicant-fillable candidate details section in the official PDF.">
      <label className="field md:col-span-4">First Name <Required /><input className={inputClass(state,'firstName')} name="firstName" autoComplete="given-name" defaultValue={values.firstName} required /><FieldError state={state} field="firstName" /></label>
      <label className="field md:col-span-4">Middle Name / Initial<input className={inputClass(state,'middleInitial')} name="middleInitial" autoComplete="additional-name" maxLength={50} defaultValue={values.middleInitial} /><FieldError state={state} field="middleInitial" /></label>
      <label className="field md:col-span-4">Last Name <Required /><input className={inputClass(state,'lastName')} name="lastName" autoComplete="family-name" defaultValue={values.lastName} required /><FieldError state={state} field="lastName" /></label>
      <label className="field md:col-span-4">Preferred Name<input className={inputClass(state,'preferredName')} name="preferredName" defaultValue={values.preferredName} /><FieldError state={state} field="preferredName" /></label>
      <label className="field md:col-span-8">Residential Address <Required /><input className={inputClass(state,'residentialAddress')} name="residentialAddress" autoComplete="street-address" defaultValue={values.residentialAddress} required /><FieldError state={state} field="residentialAddress" /></label>
      <label className="field md:col-span-6">Email <Required /><input className={inputClass(state,'email')} name="email" type="email" autoComplete="email" defaultValue={values.email} required /><FieldError state={state} field="email" /></label>
      <div className="field md:col-span-6"><span>Phone <Required /></span><div className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,14rem)_minmax(0,1fr)]"><select className={inputClass(state,'phoneCountryIso')} name="phoneCountryIso" aria-label="Phone country" required defaultValue={values.phoneCountryIso || 'NG'}>{countryPhoneOptions.map((country)=><option key={country.iso} value={country.iso}>{country.name} {country.dialCode}</option>)}</select><input className={inputClass(state,'phoneNational')} name="phoneNational" inputMode="tel" autoComplete="tel" defaultValue={values.phoneNational} required /></div><FieldError state={state} field="phoneCountryIso" /><FieldError state={state} field="phoneNational" /></div>
      <label className="field md:col-span-4">State of Residence <Required /><input className={inputClass(state,'stateOfResidence')} name="stateOfResidence" defaultValue={values.stateOfResidence} required /><FieldError state={state} field="stateOfResidence" /></label>
      <label className="field md:col-span-4">LGA of Residence <Required /><input className={inputClass(state,'lgaOfResidence')} name="lgaOfResidence" defaultValue={values.lgaOfResidence} required /><FieldError state={state} field="lgaOfResidence" /></label>
      <label className="field md:col-span-4">Nationality <Required /><input className={inputClass(state,'nationality')} name="nationality" defaultValue={values.nationality || 'Nigerian'} required /><FieldError state={state} field="nationality" /></label>
      <SelectField state={state} name="rightToWorkNigeria" label="Right to work in Nigeria" options={rightToWorkOptions} />
      <SelectField state={state} name="genderForHr" label="Gender for HR record" options={genderOptions} span="md:col-span-5" />
    </FormSection>
    <FormSection number="2" title="Role Interest and Availability" helper="Role, employment type, work mode, availability, salary and source information.">
      <label className="field md:col-span-7">Position / Role Applied For <Required /><select className={inputClass(state,'role')} name="role" required defaultValue={selectedRole}>{roleAppliedForOptions.map((role)=><option key={role} value={role}>{role}</option>)}</select><FieldError state={state} field="role" /></label>
      <label className={`field md:col-span-5 ${otherRoleIsSelected ? '' : 'opacity-75'}`}>If Other, specify role<input className={inputClass(state,'otherRole')} name="otherRole" defaultValue={values.otherRole} /><FieldError state={state} field="otherRole" /></label>
      <SelectField state={state} name="employmentType" label="Employment Type" options={employmentTypeOptions} span="md:col-span-4" />
      <SelectField state={state} name="workMode" label="Preferred Work Mode" options={stage1WorkModeOptions} span="md:col-span-4" />
      <label className="field md:col-span-4">Available Start Date<input className={inputClass(state,'availableStartDate')} name="availableStartDate" type="date" defaultValue={values.availableStartDate} /><FieldError state={state} field="availableStartDate" /></label>
      <label className="field md:col-span-4">Notice Period<input className={inputClass(state,'noticePeriod')} name="noticePeriod" defaultValue={values.noticePeriod} /></label>
      <label className="field md:col-span-4">Salary Expectation<input className={inputClass(state,'salaryExpectation')} name="salaryExpectation" defaultValue={values.salaryExpectation} /></label>
      <SelectField state={state} name="salaryNegotiable" label="Salary Negotiable" options={yesNoOptions} span="md:col-span-4" />
      <SelectField state={state} name="canWorkMondayFriday" label="Can work Monday-Friday" options={yesNoOptions} span="md:col-span-4" />
      <label className="field md:col-span-4">Preferred Working Time<input className={inputClass(state,'preferredWorkingTime')} name="preferredWorkingTime" defaultValue={values.preferredWorkingTime} /></label>
      <label className="field md:col-span-8">How did you hear about us?<input className={inputClass(state,'heardAboutUs')} name="heardAboutUs" defaultValue={values.heardAboutUs} /></label>
    </FormSection>
    <FormSection number="3" title="Documents Submitted" helper="Upload your CV/resume and note other documents shown on the official PDF.">
      <div className="min-w-0 rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-4 sm:p-5 md:col-span-12 md:p-6"><label className="field min-w-0 cursor-pointer gap-3"><span className="text-base font-bold text-ink">CV / Resume upload <Required /></span><input className="sr-only" name="cv" type="file" accept={uploadAccept} required onChange={(event)=>setSelectedFile(event.currentTarget.files?.[0]?.name ?? '')} /><span className="btn btn-secondary w-fit">Choose file</span><span className="text-sm leading-6 text-slate-600">Accepted formats: PDF, DOC, DOCX, JPG, JPEG, PNG, or WEBP. Maximum file size: 20MB.</span>{selectedFile ? <span className="max-w-full break-words rounded-lg bg-white px-3 py-2 text-sm font-semibold text-brand shadow-sm">Selected: {selectedFile}</span> : null}<FieldError state={state} field="cv" /></label></div>
      <SelectField state={state} name="portfolioAvailable" label="Portfolio / work samples included" options={yesNoOptions} required={false} />
      <SelectField state={state} name="certificatesAvailable" label="Certificates included" options={yesNoOptions} required={false} />
      <label className="field md:col-span-6">Certificate upload note<input className={inputClass(state,'certificatesNote')} name="certificatesNote" defaultValue={values.certificatesNote} /></label>
      <label className="field md:col-span-6">Other document note<input className={inputClass(state,'otherDocumentNote')} name="otherDocumentNote" defaultValue={values.otherDocumentNote} /></label>
    </FormSection>
    <FormSection number="4" title="Education, Skills and Experience" helper="Qualification rows, skills/tools, portfolio URL, and employment or project history.">
      <label className="field md:col-span-12">Education / Qualification Rows <Required /><textarea className={`${inputClass(state,'educationHistory')} min-h-28 resize-y leading-6`} name="educationHistory" defaultValue={values.educationHistory} required /></label>
      <label className="field md:col-span-12">Skills and Tools <Required /><input className={inputClass(state,'skills')} name="skills" defaultValue={values.skills} required /></label>
      <label className="field md:col-span-10">Portfolio / Work Sample URL<input className={inputClass(state,'portfolioUrl')} name="portfolioUrl" type="url" defaultValue={values.portfolioUrl} placeholder="https://" /></label>
      <label className="field md:col-span-12">Employment or Project History <Required /><textarea className={`${inputClass(state,'employmentHistory')} min-h-32 resize-y leading-6`} name="employmentHistory" defaultValue={values.employmentHistory} required /></label>
      <label className="field md:col-span-12">Additional application message<textarea className={`${inputClass(state,'message')} min-h-24 resize-y leading-6`} name="message" defaultValue={values.message} /></label>
    </FormSection>
    <FormSection number="5" title="References, Declaration and Consent" helper="Referees, declarations, data privacy acknowledgement, and electronic signature.">
      {([1,2] as const).map((n)=><div key={n} className="grid min-w-0 grid-cols-1 gap-4 rounded-2xl border border-slate-100 bg-slate-50 p-4 md:col-span-12 md:grid-cols-12"><h3 className="font-bold text-ink md:col-span-12">Referee {n}</h3><label className="field md:col-span-4">Full name<input className={inputClass(state,`referee${n}Name`)} name={`referee${n}Name`} defaultValue={values[`referee${n}Name`]} /></label><label className="field md:col-span-4">Company / Role<input className={inputClass(state,`referee${n}CompanyRole`)} name={`referee${n}CompanyRole`} defaultValue={values[`referee${n}CompanyRole`]} /></label><label className="field md:col-span-4">Relationship<input className={inputClass(state,`referee${n}Relationship`)} name={`referee${n}Relationship`} defaultValue={values[`referee${n}Relationship`]} /></label><label className="field md:col-span-4">Phone<input className={inputClass(state,`referee${n}Phone`)} name={`referee${n}Phone`} defaultValue={values[`referee${n}Phone`]} /></label><label className="field md:col-span-4">Email<input className={inputClass(state,`referee${n}Email`)} name={`referee${n}Email`} type="email" defaultValue={values[`referee${n}Email`]} /></label><SelectField state={state} name={`referee${n}MayContact`} label="May contact" options={yesNoOptions} required={false} span="md:col-span-4" /></div>)}
      <label className="flex min-w-0 gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 leading-6 md:col-span-12"><input name="declarationAccuracy" type="checkbox" defaultChecked={values.declarationAccuracy === 'on'} required /><span>I declare that the information provided is true and complete. <Required /><FieldError state={state} field="declarationAccuracy" /></span></label>
      <label className="flex min-w-0 gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 leading-6 md:col-span-12"><input name="privacyConsent" type="checkbox" defaultChecked={values.privacyConsent === 'on'} required /><span>I acknowledge Zentric Analytics Ltd may process my application data for recruitment review and records. <Required /><FieldError state={state} field="privacyConsent" /></span></label>
      <label className="field md:col-span-7">Electronic signature typed name <Required /><input className={inputClass(state,'signatureName')} name="signatureName" defaultValue={values.signatureName} required /></label>
      <label className="flex min-w-0 gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 leading-6 md:col-span-12"><input name="signatureConsent" type="checkbox" defaultChecked={values.signatureConsent === 'on'} required /><span>I confirm this typed name is my electronic signature. <Required /><FieldError state={state} field="signatureConsent" /></span></label>
      <div className="min-w-0 rounded-2xl bg-ink p-4 text-white sm:p-5 md:col-span-12 md:flex md:items-center md:justify-between md:gap-6"><p className="text-sm leading-6 text-slate-200">Admin-only “For Zentric Use Only” PDF fields are not collected here.</p><button className="btn mt-4 w-full min-w-0 bg-white text-ink md:mt-0 md:w-auto" type="submit" disabled={pending}>{pending ? 'Submitting...' : 'Submit Stage 1 Application'}</button></div>
    </FormSection>
  </form>;
}
