import { prisma } from "@/lib/prisma";
import { requireAnyPermission } from "@/lib/hr/permissions/authorize";
import { createEmployeeAssignmentAction, createScopedSupervisorAssignmentAction, createSupervisorAssignmentAction, endEmployeeAssignmentAction, endSupervisorAssignmentAction } from "./actions";

export default async function AssignmentsPage() {
  const auth = await requireAnyPermission(["assignment.create", "assignment.update", "assignment.end"]);
  const [assignments, supervisorAssignments, employees, departments, positions, teams] = await Promise.all([
    prisma.hrEmployeeAssignment.findMany({ where: { organizationId: auth.user.organizationId }, include: { employee: true, department: true, team: true, position: true }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
    prisma.hrSupervisorAssignment.findMany({ where: { organizationId: auth.user.organizationId }, include: { supervisorEmployee: true, assignedEmployee: true, departmentScope: true, teamScope: true }, orderBy: { effectiveFrom: "desc" }, take: 250 }),
    prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId, employmentStatus: { notIn: ["TERMINATED", "ARCHIVED"] } }, orderBy: [{ lastName: "asc" }, { legalFirstName: "asc" }] }),
    prisma.hrDepartment.findMany({ where: { organizationId: auth.user.organizationId, status: "ACTIVE" }, orderBy: { name: "asc" } }),
    prisma.hrPosition.findMany({ where: { organizationId: auth.user.organizationId, status: "ACTIVE", lifecycleStatus: { in: ["OPEN", "PARTIALLY_FILLED"] } }, orderBy: { title: "asc" } }),
    prisma.hrTeam.findMany({ where: { organizationId: auth.user.organizationId, status: "ACTIVE" }, include: { department: true }, orderBy: { name: "asc" } }),
  ]);
  return <><h1 className="text-3xl font-bold">Employment assignments</h1><p className="mt-2 text-slate-600">Transfers close the prior record and preserve the full department and position history.</p>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create assignment or transfer</h2><form action={createEmployeeAssignmentAction} className="mt-4 grid gap-3 md:grid-cols-4"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.employeeNumber} — {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="departmentId" required><option value="">Department</option>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><select className="input" name="teamId"><option value="">No team</option>{teams.map((team) => <option value={team.id} key={team.id}>{team.department.name} — {team.name}</option>)}</select><select className="input" name="positionId" required><option value="">Position</option>{positions.map((position) => <option value={position.id} key={position.id}>{position.title}</option>)}</select><select className="input" name="employmentType" defaultValue="FULL_TIME"><option>FULL_TIME</option><option>PART_TIME</option><option>CONTRACT</option><option>INTERN</option><option>TEMPORARY</option></select><input className="input" name="fte" type="number" min="0.01" max="2" step="0.01" defaultValue="1" aria-label="FTE"/><input type="hidden" name="isPrimary" value="true"/><input className="input" name="location" placeholder="Location" /><input className="input" name="effectiveFrom" type="date" required /><input className="input" name="reason" placeholder="Reason for assignment/transfer" required /><button className="btn btn-primary">Save assignment</button></form></section>
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-4">Employee</th><th className="p-4">Department</th><th className="p-4">Position</th><th className="p-4">Effective period</th><th className="p-4">Status</th><th className="p-4">Reason</th><th className="p-4">Action</th></tr></thead><tbody>{assignments.map((assignment) => <tr className="border-b last:border-0" key={assignment.id}><td className="p-4 font-semibold">{assignment.employee.legalFirstName} {assignment.employee.lastName}</td><td className="p-4">{assignment.department.name}</td><td className="p-4">{assignment.position.title}</td><td className="p-4">{assignment.effectiveFrom.toLocaleDateString()} – {assignment.effectiveTo?.toLocaleDateString() ?? "Current"}</td><td className="p-4">{assignment.status}</td><td className="p-4">{assignment.reason}</td><td className="p-4">{assignment.status === "ACTIVE" ? <form action={endEmployeeAssignmentAction} className="grid gap-2"><input type="hidden" name="id" value={assignment.id} /><input className="input" name="effectiveTo" type="date" required /><input className="input" name="reason" placeholder="End reason" required /><button className="text-left font-semibold text-red-700">End assignment</button></form> : "History retained"}</td></tr>)}</tbody></table>{!assignments.length ? <p className="p-6 text-slate-500">No assignments yet.</p> : null}</div>
    <section className="mt-8 rounded-2xl bg-white p-5"><h2 className="text-xl font-bold">Supervisor assignments</h2><p className="mt-1 text-sm text-slate-600">Supervisor capability comes from effective-dated assignments, never a permanent role.</p><form action={createSupervisorAssignmentAction} className="mt-4 grid gap-3 md:grid-cols-4"><select className="input" name="supervisorEmployeeId" required><option value="">Supervisor</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="assignedEmployeeId" required><option value="">Direct report</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.legalFirstName} {employee.lastName}</option>)}</select><input className="input" name="effectiveFrom" type="date" required /><input className="input" name="reason" placeholder="Assignment reason" required /><button className="btn btn-primary md:col-span-4">Assign supervisor</button></form>
      <form action={createScopedSupervisorAssignmentAction} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-4"><select className="input" name="supervisorEmployeeId" required><option value="">Scoped supervisor</option>{employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="assignmentType" defaultValue="DEPARTMENT"><option>DEPARTMENT</option><option>TEAM</option></select><select className="input" name="departmentScopeId" required><option value="">Department scope</option>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select><select className="input" name="teamScopeId"><option value="">No team (department scope)</option>{teams.map((team) => <option value={team.id} key={team.id}>{team.department.name} — {team.name}</option>)}</select><input className="input" name="effectiveFrom" type="date" required /><input className="input md:col-span-2" name="reason" placeholder="Scoped assignment reason" required /><button className="btn btn-primary">Assign scope</button></form>
      <div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3">Supervisor</th><th>Employee or scope</th><th>Effective</th><th>Status</th><th>Reason</th><th>Action</th></tr></thead><tbody>{supervisorAssignments.map((assignment) => <tr className="border-b last:border-0" key={assignment.id}><td className="py-3 font-semibold">{assignment.supervisorEmployee.legalFirstName} {assignment.supervisorEmployee.lastName}</td><td>{assignment.assignedEmployee ? `${assignment.assignedEmployee.legalFirstName} ${assignment.assignedEmployee.lastName}` : assignment.teamScopeId ? `Team scope ${assignment.teamScopeId}` : assignment.departmentScopeId ? `Department scope ${assignment.departmentScopeId}` : "Workflow scope"}</td><td>{assignment.effectiveFrom.toLocaleDateString()} – {assignment.effectiveTo?.toLocaleDateString() ?? "Current"}</td><td>{assignment.status}</td><td>{assignment.reason}</td><td>{assignment.status === "ACTIVE" ? <form action={endSupervisorAssignmentAction} className="flex gap-2"><input type="hidden" name="id" value={assignment.id} /><input className="input" name="reason" placeholder="End reason" required /><button className="font-semibold text-red-700">End</button></form> : assignment.endReason ?? "History retained"}</td></tr>)}</tbody></table></div></section></>;
}
