import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/hr/permissions/authorize";
import { assignShiftAction, assignTimePolicyAction, createAttendancePeriodAction, createShiftTemplateAction, createTimePolicyAction, recoverTimeWorkerAction, reviewTimeCorrectionAction, transitionAttendancePeriodAction } from "./actions";

export default async function AdminTimePage() {
  const auth = await requirePermission("time.read_all");
  const [policies, employees, policyAssignments, events, exceptions, periods, corrections, workers, shifts] = await Promise.all([
    prisma.hrTimePolicy.findMany({ where: { organizationId: auth.user.organizationId }, include: { versions: { orderBy: { version: "desc" }, take: 1 } }, orderBy: { code: "asc" } }),
    prisma.hrEmployee.findMany({ where: { organizationId: auth.user.organizationId, employmentStatus: "ACTIVE", employmentAssignments: { some: { status: "ACTIVE" } }, workRelationships: { some: { status: "ACTIVE" } } }, select: { id: true, employeeNumber: true, legalFirstName: true, lastName: true }, orderBy: { employeeNumber: "asc" }, take: 500 }),
    prisma.hrTimePolicyAssignment.findMany({ where: { organizationId: auth.user.organizationId, effectiveTo: null }, orderBy: { effectiveFrom: "desc" }, take: 100 }),
    prisma.hrTimeEvent.count({ where: { organizationId: auth.user.organizationId } }),
    prisma.hrAttendanceDay.count({ where: { organizationId: auth.user.organizationId, currentOutcome: { notIn: ["PRESENT", "APPROVED_LEAVE", "HOLIDAY", "NON_WORKING_DAY"] } } }),
    prisma.hrAttendancePeriod.findMany({ where: { organizationId: auth.user.organizationId }, orderBy: { startsOn: "desc" }, take: 20 }),
    prisma.hrTimeCorrection.findMany({ where: { organizationId: auth.user.organizationId, status: { in: ["SUBMITTED", "IN_REVIEW"] } }, orderBy: { createdAt: "asc" }, take: 50 }),
    prisma.hrTimeWorkerRun.findMany({ where: { organizationId: auth.user.organizationId }, orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.hrShiftTemplate.findMany({ where: { organizationId: auth.user.organizationId }, include: { versions: { where: { publishedAt: { not: null } }, orderBy: { version: "desc" }, take: 1 }, assignments: { orderBy: { startsAt: "desc" }, take: 10 } }, orderBy: { code: "asc" } }),
  ]);
  return <><h1 className="text-3xl font-bold">Time &amp; attendance</h1><p className="mt-2 text-slate-600">Policy, exception, approval, lock, and authoritative handoff controls.</p>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">Policies</p><p className="text-3xl font-bold">{policies.length}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">Immutable events</p><p className="text-3xl font-bold">{events}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">Open exceptions</p><p className="text-3xl font-bold">{exceptions}</p></div></div>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Effective time policies</h2><form action={createTimePolicyAction} className="mt-3 grid gap-3 md:grid-cols-4"><input className="input" name="code" placeholder="Policy code" required/><input className="input" name="name" placeholder="Policy name" required/><select className="input" name="trackingMode" required><option value="EXCEPTION_BASED">Exception based</option><option value="CLOCK">Clock</option><option value="TIMESHEET">Timesheet</option><option value="NONE">None</option></select><input className="input" name="timezone" defaultValue="Africa/Lagos" required/><input className="input" type="datetime-local" name="effectiveFrom" required/><input className="input" type="number" min="0" name="graceBeforeMinutes" placeholder="Early grace minutes"/><input className="input" type="number" min="0" name="graceAfterMinutes" placeholder="Late grace minutes"/><input className="input" type="number" min="0" name="maximumOfflineDelayMin" defaultValue="1440"/><input className="input" type="number" min="0" name="maximumFutureSkewMin" defaultValue="5"/><button className="btn btn-primary md:col-span-3">Create and publish</button></form><div className="mt-5 space-y-2">{policies.map((policy) => <p className="text-sm" key={policy.id}>{policy.code} · {policy.name} · {policy.versions[0]?.trackingMode ?? "NO VERSION"} · v{policy.versions[0]?.version ?? 0}</p>)}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Create weekly period</h2><form action={createAttendancePeriodAction} className="mt-3 grid gap-3 md:grid-cols-4"><input className="input" name="timezone" defaultValue="Africa/Lagos" required/><input className="input" type="datetime-local" name="startsOn" required/><input className="input" type="datetime-local" name="endsOn" required/><button className="btn btn-primary">Create</button></form><div className="mt-5 space-y-3">{periods.map((period) => <form action={transitionAttendancePeriodAction} className="flex flex-wrap items-center gap-3 rounded-xl border p-3" key={period.id}><input type="hidden" name="periodId" value={period.id}/><input type="hidden" name="expectedVersion" value={period.version}/><p className="mr-auto text-sm">{period.startsOn.toLocaleDateString()}–{period.endsOn.toLocaleDateString()} · {period.status} · v{period.version}</p>{period.status === "OPEN" ? <button className="btn btn-secondary" name="decision" value="SUBMIT">Submit</button> : null}{period.status === "SUBMITTED" ? <button className="btn btn-secondary" name="decision" value="APPROVE">Approve</button> : null}{period.status === "APPROVED" ? <button className="btn btn-primary" name="decision" value="LOCK">Lock authoritative time</button> : null}</form>)}</div></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Correction review</h2>{corrections.map((correction) => <form action={reviewTimeCorrectionAction} className="mt-3 grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_2fr_auto_auto_auto]" key={correction.id}><input type="hidden" name="correctionId" value={correction.id}/><input type="hidden" name="expectedVersion" value={correction.version}/><p className="text-sm">Employee {correction.employeeId.slice(-6)} · v{correction.version}</p><input className="input" name="reason" placeholder="Decision reason" required/><button className="btn btn-primary" name="decision" value="APPROVED">Approve</button><button className="btn btn-secondary" name="decision" value="RETURNED">Return</button><button className="btn btn-secondary" name="decision" value="REJECTED">Reject</button></form>)}{!corrections.length ? <p className="mt-3 text-sm text-slate-500">No corrections awaiting review.</p> : null}</section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Worker evidence</h2>{workers.map((run) => <div className="mt-2 flex flex-wrap items-center gap-3" key={run.id}><p className="text-sm">{run.jobType} · {run.windowKey} · {run.status} · attempts {run.attemptCount}</p>{run.status === "DEAD_LETTER" ? <form action={recoverTimeWorkerAction} className="flex gap-2"><input type="hidden" name="runId" value={run.id}/><input type="hidden" name="expectedAttemptCount" value={run.attemptCount}/><input className="input" name="reason" placeholder="Recovery reason" required/><button className="btn btn-secondary">Recover</button></form> : null}</div>)}</section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Assign effective policy</h2><form action={assignTimePolicyAction} className="mt-3 grid gap-3 md:grid-cols-4"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employeeNumber} · {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="timePolicyVersionId" required><option value="">Published policy</option>{policies.flatMap((policy) => policy.versions.map((version) => <option key={version.id} value={version.id}>{policy.code} · {version.trackingMode} · v{version.version}</option>))}</select><input className="input" type="datetime-local" name="effectiveFrom" required/><input className="input" name="reason" placeholder="Assignment reason" required/><button className="btn btn-primary md:col-span-4">Assign policy</button></form><p className="mt-3 text-sm text-slate-500">{policyAssignments.length} current policy assignments.</p></section>
    <section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-bold">Published shifts</h2><form action={createShiftTemplateAction} className="mt-3 grid gap-3 md:grid-cols-4"><input className="input" name="code" placeholder="Shift code" required/><input className="input" name="name" placeholder="Shift name" required/><input className="input" name="timezone" defaultValue="Africa/Lagos" required/><input className="input" type="datetime-local" name="effectiveFrom" required/><input className="input" type="datetime-local" name="startsAt" required/><input className="input" type="datetime-local" name="endsAt" required/><button className="btn btn-primary md:col-span-2">Publish shift</button></form><form action={assignShiftAction} className="mt-5 grid gap-3 md:grid-cols-4"><select className="input" name="employeeId" required><option value="">Employee</option>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.employeeNumber} · {employee.legalFirstName} {employee.lastName}</option>)}</select><select className="input" name="shiftTemplateVersionId" required><option value="">Published shift</option>{shifts.flatMap((shift) => shift.versions.map((version) => <option key={version.id} value={version.id}>{shift.code} · v{version.version}</option>))}</select><input className="input" type="date" name="businessDate" required/><input className="input" type="datetime-local" name="startsAt" required/><input className="input" type="datetime-local" name="endsAt" required/><input className="input" name="reason" placeholder="Shift assignment reason" required/><button className="btn btn-primary md:col-span-2">Assign shift</button></form><p className="mt-3 text-sm text-slate-500">{shifts.length} published shift templates · {shifts.reduce((total, shift) => total + shift.assignments.length, 0)} recent assignments.</p></section>
  </>;
}
